Prevent plugins from crashing setup (#9030)
modxcms/revolution pull request #13271
Opened 2017-02-01 06:22 UTC by BobRay

### What does it do?

Checks for xPDO::OPT_SETUP === true

### Why is it needed?
If an upgrade saves a user or resource and a plugin connected to an invoked event calls get() on one of these, Setup will crash if these are not set. This change prevents plugins from executing during setup.

I've checked all event invocations in the code and the only ones where false would not be acceptable involve RTE events, which would never execute during setup.

### Related issue(s)/PR(s)
   issue #9030

2017-02-08 18:21 UTC, Mark-H commented
Sorry if I'm being daft, but I don't understand what this achieves... xPDO::OPT_SETUP is a constant that's defined as a value of `setup` - that would never get a value of `true`?

2017-02-08 19:07 UTC, pixelchutes commented
I think it gets set during setup in **setup/includes/modinstall.class.php:**  [here](https://github.com/modxcms/revolution/blob/2.x/setup/includes/modinstall.class.php#L444) or maybe [here](https://github.com/modxcms/revolution/blob/2.x/setup/includes/modinstall.class.php#L473) ?

2017-02-08 19:34 UTC, Mark-H commented
The PR only tests the constant though, not an option with that key. Probably should be a check on getOption instead?

2017-02-08 23:40 UTC, pixelchutes commented
Ah, I'm with you now. Thoughts @BobRay?

2017-02-09 07:51 UTC, Jako requested changes
```
if (!$eventName || $this->getOption(xPDO::OPT_SETUP) === true)
```

2017-03-03 17:02 UTC, Mark-H commented
@BobRay Could you please update the PR to do what it's supposed to do per Jako's review?

2017-03-04 18:38 UTC, BobRay commented
Mark, I just did that yesterday, unless I did something wrong.

Let me know.

2017-03-04 18:43 UTC, Mark-H commented
Thanks @BobRay!

2017-03-28 13:58 UTC, closed without merging