#6142 Added abbility to see which plugins attached to the event #modxbughunt
modxcms/revolution pull request #13324
Opened 2017-03-03 11:24 UTC by Alroniks

### What does it do?
It allows to see which plugins attached to system event on the events page.

### Why is it needed?
When in the system a lot of plugins sometimes it can be useful so see which of them attached to events from events page. Or when we try to see which plugins work with specific event.

![system settings - modx revolution](https://cloud.githubusercontent.com/assets/303498/23549381/1040e64a-001d-11e7-9f99-1ca6a9196c7d.png)

### Related issue(s)/PR(s)
Partially fix for https://github.com/modxcms/revolution/issues/6142

2017-03-06 10:41 UTC, rtripault requested changes
Added a small note about short array syntax (which is PHP 5.4+).

Also, i was wondering if we should display only active plugin (`where(array('disabled' => false))` or style disabled plugins differently (rendered in the grid).

Otherwise :+1:

2017-03-06 10:41 UTC, rtripault commented on core/model/modx/processors/system/event/getlist.class.php
> +                $c->where(['modPluginEvent.event' => $eventArray['name']]);
While i would love to use the short array syntax, this would break compatibility to PHP 5.3.x

2017-03-06 13:10 UTC, Alroniks commented on core/model/modx/processors/system/event/getlist.class.php
> +                $c->where(['modPluginEvent.event' => $eventArray['name']]);
Agree, It's a hard to follow when it has become a habit. :)

2017-03-06 13:13 UTC, Alroniks commented
@rtripault I thought about to add marks for plugins, like `Ace (disabled, locked), pdoTools (locked)` and to avoid to change styles. My assumptions, that here we will have only readable info and disabled mostly applicable to form elements.

2017-06-15 20:42 UTC, Mark-H commented
This looks useful, but can't be merged until the short array syntax is fixed ;)

2017-06-22 08:25 UTC, Alroniks commented
@Mark-H @rtripault Fixed short arrays and add statuses for plugins (see screnshot below)
![system settings - modx revolution 1](https://user-images.githubusercontent.com/303498/27424369-72fa6686-573d-11e7-95e2-6c81e69e5b48.png)

2017-06-22 19:31 UTC, rtripault approved these changes

2017-07-07 12:01 UTC, rtripault commented on core/model/modx/processors/system/event/getlist.class.php
> +            $eventArray['plugins'] = json_encode($eventArray['plugins']);
What is the benefit of json encoding here and having to parse the json client side later ?

2017-07-07 12:06 UTC, rtripault commented
All working as expected.
Just added a question about json encoding a value that would be json encoded later anyway

2017-07-07 12:59 UTC, Alroniks commented on core/model/modx/processors/system/event/getlist.class.php
> +            $eventArray['plugins'] = json_encode($eventArray['plugins']);
You are right, it's obsolete. I've fixed and removed this encoding/decoding.

2017-07-07 13:05 UTC, merged

2017-07-07 13:06 UTC, rtripault commented
Many thanks for your work and patience ;)

2017-07-07 18:43 UTC, gpsietzema commented
#modxbughunt #1point to @rtripault