Fixed bug 11269 with wrong parsing if add sign inside output filter.
modxcms/revolution pull request #13522
Opened 2017-07-07 16:02 UTC by wuuti

### What does it do?
Fixes the wrong parser behaviour if an @ is used inside output filter.

### Why is it needed?
Issues #11269 and (closed) #12159. Parsers xpdo call to escSplit works not as proposed, the string is split inside escaped parts, which causes the bug.

The split of the string to find the property set is now managed by a preg_match regex call. The benefit is, that this also replaces the second split there, which only splits PropertySet:outputFilters. Might be even quicker at all.

### Remarks
Besides the fact, that the regex imho is the more elegant solution, this seems to be a bug in the xpdo->escSplit method. The method is intended _not_ to go into escaped content, but it does here. Therefore, additionally further tests with xpdo might have to be done.

2017-07-07 16:10 UTC, sonicpunk commented
#modxbughunt #3points to @wuuti

2017-07-07 16:11 UTC, sonicpunk commented
#modxbughunt #1point to @rtripault

2017-07-07 20:09 UTC, OptimusCrime commented
For your information: The `@` is an _at_ sign, and `+` is an _add_  sign. Other than that, looks good :)

2017-08-30 08:00 UTC, sdrenth commented
Tested and can confirm this works!

2017-08-30 21:34 UTC, opengeek commented
I'm reviewing this and the `xPDO::escSplit()` method to see if there is a better solution.

2017-09-01 19:56 UTC, opengeek commented
FWIW, the problem in `xPDO::escSplit()` is due to the embedded escape characters. I'm really torn on adopting this solution without more exhaustive tests that prove this works as expected with all existing tag usage. The alternative is to document that you should never use embedded escape characters. For instance, the tag sequence:

```A[[*pagetitle:isnot=`Y`:then=`C[[$Z?&mail=`ab@de`]]E`:else=`F`]]B```

works fine without the embedded escape characters, e.g.:

```A[[*pagetitle:isnot=`Y`:then=`C[[$Z?&mail=ab@de]]E`:else=`F`]]B```

This tag sequence is violating recommended usage of conditionals already: the tag sequence in the `then` is *always* evaluated regardless if the condition is matched or not. But I would like to consider any dissenting opinions before making a final decision to reject or accept this change.

2017-09-01 20:53 UTC, pixelchutes commented
I'd be interested to know if the introduction of the regex has any negative performance impact?

I realize this could be tricky to quantify / vary depending on use case, but I guess it probably depends on the frequency of `getPropertySet()` gets called. If somehow performance is _improved_, then no objections from me.

I will note that I've bumped into this particular issue before, and solved it the same way Jason is recommending (removing the double-nested backticks: ``` ` ```)

2017-09-02 15:21 UTC, OptimusCrime commented
Regex-calls are somewhat expensive, so I guess this increases the parsing time. However, I think the increase in total is marginal, especially when you compare it against database calls.

I am all in favor of this implementation, as the other options (add exceptions to the syntax) makes everything more confusing that it already is. Also, I am confused why this seemingly utility method is placed in the ORM code, and not the MODX class itself. I searched the repository and it is used once in xPDO and twice in MODX only. It could be better to extract the method and place it in the MODX code instead. Or, dont use it at all.

Too bad we dont have a decent unit test suit that could test this implementation for us.

2017-09-02 22:57 UTC, wuuti commented
@pixelchutes @OptimusCrime I just wrote a small (and surely silly) benchmark script, which just repeats the splitting operation with both variants a million times. Turns out that the regex variant is factor 7.5 quicker (!) than the escSplit method in this case (I only tested the example from opengeek). But to be honest, thats no wonder: a regex is not expensive per se, and compared to what is done here (split the string at the first @ before a colon), the escSplit method is like taking a sledgehammer to crack a nut (as far as I understand whats going on in that method). 

I wonder if it would be possible to generically replace the escSplit with such a simple regex...

2017-09-03 00:34 UTC, opengeek commented
@wuuti Replacing the `xPDO::escSplit()` implementation with a solution that works in all cases would be my preference.

2017-09-03 11:38 UTC, OptimusCrime commented
I guess that would be best. I have no idea how this method works or what it is supposed to do, so I guess I am of no help here.

2017-09-03 16:06 UTC, wuuti commented
Who implemented that method? Anyone here ready for an archaeological research? 

I volunteer for some more work on this. Besides, this PR might be merged in the meantime, as it solves a special edge case of the use of the escSplit method where an issue occurs.

2017-09-03 16:41 UTC, OptimusCrime commented
I agree. And I guess it was originally written by @opengeek (?)

2017-09-05 19:47 UTC, opengeek commented
I think I have found some issues with this regex. For instance, a dash (`-`) character in the element name seems to break this. I'm researching if there is an easy way to fix the expression.

2017-09-06 12:26 UTC, wuuti commented
@opengeek That should be quite easy to solve. The \w* just has to be replaced with [\w\-]*, possibly enhanced with all other characters being allowed for element names and for set names. 

Do we have any official restriction (also in the docs) on the allowed characters? I know there are some other issues dangling around with that (e.g. the #13381). I fear there are some other places in the code where some kind of checks for that occur (creating a new element?), and we should have a central pattern for that (constant?) which all other places consume...

2017-09-06 13:34 UTC, OptimusCrime commented
I have kind of concluded for issue #13381 that it is a wontfix and such "hacking" is beyond the scope of what we are able to handle during parsing. I see no reason to take it into account in the regex posed above.

2017-09-06 13:47 UTC, opengeek commented
There is regex for validation of element names in the database schema, e.g.

`/^(?!\\s)[a-zA-Z0-9\\x2d-\\x2f\\x7f-\\xff-_\\s]+(?!\\s)$/`

2017-09-08 05:06 UTC, wuuti commented
@opengeek Thats an interesting regex. Online tools like https://www.debuggex.com do show errors for this regex.

2017-09-08 08:42 UTC, OptimusCrime commented
Regex101 also reports errors about the ordering of the character ranges. Are we sure this regex is correct?

2017-09-08 12:19 UTC, wuuti commented
Well, it is correct without the double backslashes for the online services: 

`/^(?!\s)[a-zA-Z0-9\x2d-\x2f\x7f-\xff-_\s]+(?!\s)$/`

The regex will also include spaces in the element name. _Is that what we want here???_ Without the spaces, simplified and internationalized it _could_ be:

`^[\w\d\-\.\/\x{a1}-\x{2af}]+$`

Which will include more letters, remove controls and remove the negative lookaheads for whitespace. This validates crude names like `abc./DEʬD3-¸_df¶` (note, it's not a comma , but U+00B8 "cedilla").  And it might be better in performance here.

2017-09-08 12:21 UTC, OptimusCrime commented
Might be that the double backslashes are only there as it needs to escape the backslashes in strings in PHP/JS.

2017-09-08 12:38 UTC, wuuti commented
Mh... as the pattern is noted in single quotes in the map, there is no need to escape anything but a ' or \

2017-09-08 12:42 UTC, OptimusCrime commented
You're right. Then I don't know.

https://3v4l.org/k9RRV

2018-06-05 05:59 UTC, bezumkin approved these changes
Tested in production on modx.pro - no problems found

2018-07-31 22:01 UTC, opengeek requested changes
Unless this is going to be updated to match the regex for valid element names, this is not going to be merged.

2018-10-13 16:06 UTC, Jako commented
@wuuti Could you somehow add that valid element names regex or help us otherwise to get this merged?

2019-01-22 13:30 UTC, JoshuaLuckers commented
@wuuti is it possible to help us getting this merged?

2019-02-08 10:51 UTC, wuuti commented
working on that right now @ grünenwald/engelberg

2019-02-08 20:12 UTC, JoshuaLuckers commented
@opengeek are the changes and arguments enough to get this merged?

2019-02-09 16:22 UTC, opengeek commented
I don't understand why:
> It matches the same names as in db validation, but also more (unicode) characters.

I had also asked this to be worked into the escSplit method in xPDO instead of bypassing it. I'm a little hesitant to integrate this as is. This really needs some additional testing and exploration before I'll feel comfortable with it. But if there are enough confirmation from others using this change on large-scale sites with no problems, I'd be okay with moving forward as is for now.

2019-02-09 17:20 UTC, wuuti commented
Well, imho there is no need to use escsplit method here. The code only needs to check if there is one propertyset being used for the current element. Besides the fact that the escsplit is failing here, the regex should be much more efficient for this particular use case, and its more transparent what is happening compared to the escsplit which is more like a blackbox...

2019-02-10 08:13 UTC, JoshuaLuckers commented
Adding a Unit Test for it would be a good way to test it.

2019-09-06 15:54 UTC, opengeek commented
This needs to be rebased or applied to the 3.x branch to be considered still. Closing PR.

2019-09-06 15:54 UTC, closed without merging

2019-09-09 10:56 UTC, Jako commented
Lately I tried to work with the following template chunk part that won't work because of this issue:

```
[[[[+resource_id:notempty=`getResources? &resources=`[[+resource_id]]` &parents=`-1` &tpl=`@INLINE Resource ID: [[+id]]``:default=``]]]]
```

I hope this is a strong example for adopting this patch into 3.x

2019-09-09 12:52 UTC, sottwell commented
I found that in complex usage like this it was almost always a problem if @INLINE was used, the solution being for a chunk to be used for the tpl.