Implement output filter that calls the parser
modxcms/revolution pull request #13589
Opened 2017-09-04 20:26 UTC by OptimusCrime

### What does it do?
Add a new output filter that calls the MODX parser.

### Why is it needed?
It is a special edge case, but in certain scenarios you might want to call the MODX parser before any other output filters are applied, such as the problem reported in the original PR and forum post (see below).

Also see original PR for test case.

### Related issue(s)/PR(s)
First attempted solved in PR #13306.
Issue reported in [forum post](https://forums.modx.com/thread/96866/ellipsis-not-working-as-expected#dis-post-524087).

2017-12-14 20:07 UTC, Jako commented
Could you enhance the PR with my comment? With that you could restrict the modifier with ```[[+field:parse=`cached_only`]]``` to parse only cached tags.

2017-12-14 20:08 UTC, Jako requested changes

2017-12-14 20:08 UTC, Jako commented on core/model/modx/filters/modoutputfilter.class.php
> +                                $this->modx->parser->processElementTags('', $output, true, true, '[[', ']]', array(), $maxIterations);
Could you enhance the PR with my comment? With that you could restrict the modifier with [[+field:parse=`cached_only`]] to parse only cached tags.

2017-12-15 09:29 UTC, OptimusCrime commented on core/model/modx/filters/modoutputfilter.class.php
> +                                $this->modx->parser->processElementTags('', $output, true, true, '[[', ']]', array(), $maxIterations);
Sure can do!

2018-01-29 21:58 UTC, Mark-H commented on core/model/modx/filters/modoutputfilter.class.php
> +                                $this->modx->parser->processElementTags('', $output, true, true, '[[', ']]', array(), $maxIterations);
Doesn't look like you did :D

2018-05-23 08:54 UTC, gpsietzema commented on core/model/modx/filters/modoutputfilter.class.php
> +                                $this->modx->parser->processElementTags('', $output, true, true, '[[', ']]', array(), $maxIterations);
@OptimusCrime any chance you can change that on short term, so we can get going with 2.7? If not, that's also fine of course, we'll just include it in something else than 2.7 ;-)

2018-05-23 18:33 UTC, OptimusCrime commented on core/model/modx/filters/modoutputfilter.class.php
> +                                $this->modx->parser->processElementTags('', $output, true, true, '[[', ']]', array(), $maxIterations);
Sorry no, I do not have access to any computer in a week.

2018-06-05 07:11 UTC, bezumkin commented
Hm.

When I try to test this PR I see that everything is already parsed before run `parse` filter. My page:
```
[[!test]]
[[!+test:parse=`1`]]
```

Snippet `test`
```php
$modx->setPlaceholder('test', '[[!*id:prepend=`111`]]');
```

Filter in `modoutputfilter.class.php`
```php
case 'parse':
    var_dump($this->modx->placeholders['test']);
    var_dump($output);
    die;
```

And I see this on the page with id = 1:
```
string(22) "[[!*id:prepend=`111`]]" 
string(4) "1111"
```
So, `$output` is already parsed somewhere even it is uncached.

2018-06-05 10:07 UTC, OptimusCrime commented
@bezumkin Yeah, I had some problems debugging this myself, and I think the problem is actually solved. Closing this one?

2018-06-05 10:16 UTC, bezumkin commented
I think we can close it until somebody will provide any useful case for this `parse` tag that we could check.

2018-06-05 10:16 UTC, closed without merging