Add context filter in tree resource
modxcms/revolution pull request #13662
Opened 2017-11-01 16:40 UTC by tillpaid

### What does it do?
Add context filter in resource tree

### Why is it needed?
When I have a lot of context on my site, I spend a lot of time searching for the right context. It is not comfortable

### Related issue(s)/PR(s)
No

2017-11-01 17:01 UTC, lawrenz1337 requested changes

2017-11-01 17:01 UTC, lawrenz1337 commented on core/model/modx/processors/resource/getnodes.class.php
> +        $c= $this->modx->newQuery($this->itemClass, array('key:!=' => 'mgr', 'name:LIKE' => "%{$this->getProperty('contextFilter', '')}%"));
I think it would be better to separate this from the base query. Having ```LIKE %%``` on every query in no property sent seems not optimal.

2017-11-01 17:17 UTC, lawrenz1337 reviewed
The code seems fine but the looks of the input need some work and love

2017-11-02 15:29 UTC, zaigham commented
Could this be done as an Extra?

2017-11-02 21:40 UTC, tillpaid commented
this feature changes the system files, I do not think that the extra is a good idea

2017-11-02 23:19 UTC, Jako commented
Ext.override the MODx.tree.Resource function to extend the functionality before it is displayed. That should be an option to build that thing as an extra. The script needed for this could be added with a plugin during OnManagerPageInit.

It makes no sense to have the filter input always displayed and it seems to be a quite special need, that you are covering.

2017-11-25 10:55 UTC, Jako commented
@tillpaid I think you should do this in an installable extra.

2017-11-25 10:55 UTC, closed without merging