You cant delete/unpublish the start_page anymore by the checkboxes on update resource page #10218 #modxbughunt
modxcms/revolution pull request #13760
Opened 2018-02-09 09:58 UTC by Oetzie

### What does it do?
This fix checks the site_start, error_page and site_unavailable_page context settings to prevent that a user can delete/unpublish the site_start, error_page and site_unavailable_page page.

### Why is it needed?
The resource delete, update and unpublished processors did not check for the context settings site_start, error_page and site_unavailable_page. So you could delete the site_start, error_page and site_unavailable_page pages.

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/10218 and https://github.com/modxcms/revolution/pull/13366

2018-02-09 10:16 UTC, gpsietzema commented
Will test this now at the bug hunt.

2018-02-09 10:42 UTC, gpsietzema commented
It partly works.

In my test environment, I have set the following **system settings**:
- site_start: 3
- error_page: 4
- site_unavailable_page: 5

I tested removing/unpublishing Resource ID3/4/5 I get your new notices, which is good.

After that, I made these three context-settings in my web-context:
- site_start: 6
- error_page: 7
- site_unavailable_page: 8

If I try to remove/unpublish Resource ID 6/7/8 I get your messages again.

However, when I try to remove/unpublish Resource ID 3/4/5, I still get that message, so it is still remembering the System Settings. Shouldn't the Context-settings overrule the system settings? I should be able to remove/unpublish Resource ID 3/4/5 in this example I think.

2018-02-09 10:51 UTC, Oetzie commented
@gpsietzema there is a check that checks if the current resource ID is the same as the context setting OR the system setting. Do you think its better to check if context setting is set then only check the context setting otherwise check the system setting. So not check both settings, agree?

2018-02-09 11:04 UTC, gpsietzema commented
I agree :)

2018-02-09 11:43 UTC, Mark-H commented
I disagree.

When you have a single context, it doesn't really make sense to configure it on the context level, so your test @gpsietzema does not really reflect how it would be used. MODX may still use the system settings if you have multiple contexts, and don't define the settings for web for example. What you're defining now doesn't make much sense - why would you set system settings to one thing, and context settings to another, with a single context?

Based on your description of the test, I think it's behaving as it should. It checks both context and system settings.

2018-02-09 11:46 UTC, Oetzie commented
@Mark-H @gpsietzema I made a fix, the fix checks if the current context has a context setting 'site_start', 'error_page' or 'site_unavailable_page'. If the context setting does not exists or is empty the default system setting will be checked. It works in a multi and single context site.

2018-02-09 11:51 UTC, gpsietzema commented
@Mark-H Those system settings are already there, by default. So if we're overruling with context-settings the system settings should be ignored. Especially in multi-context environments. So I'm guessing we're having the same opinion and @Oetzie latest changes fix that :)

2018-02-09 12:02 UTC, Mark-H commented
As long as a resource is mentioned in the system setting, it should not be deletable/unpublishable. That seems like a different opinion than not checking the system settings at all if a context setting is set?

2018-02-09 12:56 UTC, Oetzie commented
@gpsietzema @Mark-H when you both come with the same solution I can fix that :-)

2018-02-09 13:04 UTC, gpsietzema commented
@Oetzie we discussed it, @Mark-H wins :) So we have to check both 👍  So your initial PR was right.

2018-02-09 13:20 UTC, Oetzie commented
@gpsietzema changed back to the first commit ;-)

2018-03-26 17:02 UTC, opengeek requested changes

2018-03-26 17:02 UTC, opengeek commented on core/model/modx/processors/resource/unpublish.class.php
> -    /**
Removing this public API function is a BC break. This cannot be merged in this current state until 3.x.

2018-05-01 09:21 UTC, gpsietzema commented
@opengeek @Oetzie we could target 3.x then... ?

2018-05-25 19:50 UTC, opengeek commented on core/model/modx/processors/resource/unpublish.class.php
> -    /**
The point of my review was to suggest the public API method `isSiteStart()` should not be removed at all. This change is not necessary and should not be done, even in 3.x without first releasing it with a deprecated mark. But again, I don't see removing this method to be necessary in the first place. Just don't use it for the purpose it was used prior to the other changes this PR makes. This SHOULD be integrated into 2.x for 2.7 release and can be if we can make that change.

2018-11-02 20:54 UTC, Mark-H commented
If the `isSiteStart` method is removed this could be merged into 2.x - for now this is unfortunately not suitable and has been waiting for an update for a while. Please reopen when that's back :)

2018-11-02 20:54 UTC, closed without merging