Remove obsolete system settings
modxcms/revolution pull request #13859
Opened 2018-04-10 15:13 UTC by Alroniks

### What does it do?
Removes obsolete system settings.

### Why is it needed?
They not used in the system anymore and are messing up the code.

### Related issue(s)/PR(s)
#13858

2018-04-10 19:36 UTC, Mark-H commented
They should probably also be removed in an upgrade script in the setup - just removing them from the build is not enough to make them actually go away.

2018-04-11 10:01 UTC, bezumkin requested changes
I think we also need to delete these settings when updating the site.

2018-04-11 12:20 UTC, alroniks commented
Good catch @Mark-H. I will update the pr.

2018-04-14 18:40 UTC, Alroniks commented
@bezumkin @Mark-H PR is updated. Please, have a look.

2018-04-15 10:13 UTC, bezumkin submitted a review, later dismissed

2018-04-18 21:49 UTC, opengeek submitted a review, later dismissed

2018-04-19 09:30 UTC, Alroniks commented
@opengeek @bezumkin Excuse me for troubling but I updated upgrading script to avoid silence mode. Now it says what was removed and errors in the case when system settings cannot be removed.

2018-04-19 21:07 UTC, opengeek commented on setup/includes/upgrades/common/3.0.0-cleanup-system-settings.php
> +            $this->runner->addResult(modInstallRunner::RESULT_FAILURE,
I don't think we want this be a failure if it doesn't remove a system setting. Do we?

2018-04-19 21:09 UTC, opengeek commented on setup/includes/upgrades/common/3.0.0-cleanup-system-settings.php
> +            $this->runner->addResult(modInstallRunner::RESULT_FAILURE,
I think warning there, and nothing if the setting doesn't exist. A warning if it has already been removed is unnecessary in my opinion.

2018-04-20 08:03 UTC, Alroniks commented on setup/includes/upgrades/common/3.0.0-cleanup-system-settings.php
> +            $this->runner->addResult(modInstallRunner::RESULT_FAILURE,
Yes, make sense. I updated this part.

2018-04-23 08:04 UTC, gpsietzema reviewed
I can't seem to get this to work on PHP7.2/Mariadb 10.2.14 (mysql 5.5.5).

I do get the message in the setup that the 2 settings have been removed, but they are still there.

Another thing: shouldn't compress_js also be removed. And what about compress_css, we are keeping that one I think?

2018-04-23 09:27 UTC, Alroniks commented
@gpsietzema Did you try to rebuild core package after checkout? Because it removes settings during the upgrade but if core package is not rebuilt it sets up these settings from the package again.

2018-04-23 09:48 UTC, gpsietzema approved these changes
@Alroniks You are right, rebuilding the core did the job!

Still wondering about compress_js settings. Shouldn't it be removed as well?

2018-04-23 10:15 UTC, bezumkin commented
@gpsietzema `compress_js` is still in use, because we have [minified version](https://github.com/modxcms/revolution/blob/2.x/manager/assets/modext/modx.jsgrps-min.js)

2018-04-23 10:41 UTC, gpsietzema commented
@bezumkin but it was removed from the installer somehow... or is that totally unrelated?

2018-04-23 10:48 UTC, bezumkin commented
@gpsietzema https://github.com/modxcms/revolution/pull/13785#issuecomment-380115763 - looks like we use minified versions by default, but can disable it for development.

So, this settings don`t need in setup.

2018-04-23 14:51 UTC, Mark-H approved these changes

2018-04-23 15:08 UTC, merged