Text javascript
modxcms/revolution pull request #13850
Opened 2018-04-04 13:27 UTC by Jako

### What does it do?
Remove an obsolete type="text/javascript" attribute from script tags.

### Why is it needed?
The attribute is not needed anymore in HTML5. See the [answers](https://stackoverflow.com/questions/5265202/do-you-need-text-javascript-specified-in-your-script-tags) on StackOverflow. It should be safe with modern browsers and IE7+.

### Related issue(s)/PR(s)
#13846

2018-04-04 13:39 UTC, Jako commented
There are two changes in the tests in this PR, since the `type="text/javascript" ` appearance is checked in _build/test/Tests/Model/Filters/modOutputFilterTest.php

2018-04-05 21:31 UTC, opengeek commented
If you fixed the tests, why are they still failing?

2018-04-05 21:37 UTC, opengeek commented
```1) modOutputFilterTest::testJsToHead with data set #0 ('assets/js/hscript.js', true, false)
Failed asserting that an array contains '<script type="text/javascript" src="assets/js/hscript.js"></script>'.
/home/travis/build/modxcms/revolution/_build/test/Tests/Model/Filters/modOutputFilterTest.php:779```

I think you just missed one.

2018-04-06 15:09 UTC, opengeek commented
I have a couple of concerns. First, you modified smarty files. These should not be modified directly. Second, while I have no concern with removing this from the manager UI, you are changing the entire way registering scripts works in the MODX core API, which means that this will change behavior for existing sites/extras that use the `regClient*Script()` methods. While we can assume this is fine for the manager UI, I'm not convinced this is a good idea to modify for front-ends that might need to support older browsers for one reason or another. I'd like some feedback on these concerns.

2018-04-06 15:12 UTC, opengeek reviewed
I have a couple of concerns. First, you modified smarty files. These should not be modified directly. Second, while I have no concern with removing this from the manager UI, you are changing the entire way registering scripts works in the MODX core API, which means that this will change behavior for existing sites/extras that use the regClient*Script() methods. While we can assume this is fine for the manager UI, I'm not convinced this is a good idea to modify for front-ends that might need to support older browsers for one reason or another. I'd like some feedback on these concerns.

2018-04-06 17:31 UTC, Jako commented
I will remove the smarty changes.

The PR fixes a validating issue in #13846 which is a frontend issue with regClient*Script() methods. Maybe we a doctype context/system setting that switches the `type="text/javascript"` in the regClient*Script() method on for XHTML and off for all other doctypes.

2018-04-06 18:25 UTC, opengeek commented
Maybe. I'd honestly like to see those methods deprecated and removed for 3.x.

2018-04-06 18:25 UTC, opengeek commented
Did not mean to close this, sorry.

2018-04-11 08:37 UTC, gpsietzema commented
Also did a test and still see a lot of text/javascripts floating around...

2018-05-01 08:40 UTC, gpsietzema commented
@opengeek @Jako what do you want to do with this?

> Maybe. I'd honestly like to see those methods deprecated and removed for 3.x.

Are you talking about the manager text/javascript mentions or something else?

2018-06-05 07:50 UTC, bezumkin requested changes
I believe we should have a system setting to enable this new behaviour in 2.7 or target it to 3.x only.

There are a lot of legacy corporate websites and we can't just change script tags because of w3c validator don't like it.

2018-06-07 07:22 UTC, closed without merging

2019-05-08 20:17 UTC, OptimusCrime commented
Do we really need a system setting for this? We already have a million system settings. For 3.x we are allowed to break stuff. Making MODX do HTML5 seem like a logical step in the right direction.

2019-05-08 21:30 UTC, Jako commented
This PR was closed last year.