Log setlocale errors
modxcms/revolution pull request #13868
Opened 2018-04-13 10:58 UTC by Jako

### What does it do?
An error is logged, when the locale functionality is not implemented or the specified locale does not exist on the system.

### Why is it needed?
Avoid issues like in #13854

### Related issue(s)/PR(s)
#13854

2018-04-13 11:16 UTC, bezumkin submitted a review, later dismissed

2018-04-13 12:45 UTC, Mark-H submitted a review, later dismissed

2018-04-13 14:49 UTC, opengeek reviewed
Should this not go into 2.6.x?

2018-04-13 22:15 UTC, Jako commented
It could, but I thought that 2.6.2/3 would be the last 2.6.x.

2018-04-14 01:30 UTC, opengeek commented
@Jako: it is and that's why I thought it would be good to include this in 2.6.3 since the update to Smarty in 2.6.2 is what inspired this PR.

2018-04-15 18:47 UTC, Jako commented
Should I create a new PR or could this be cherry picked?

2018-04-16 13:37 UTC, opengeek commented
Don't create a new PR, just apply it to the 2.6.x branch and force push it.

2018-04-19 02:16 UTC, opengeek approved these changes

2018-04-19 02:30 UTC, opengeek requested changes
I'm not sure what is wrong but when I try to merge this it merges all of the changes outstanding from 2.x. I'm releasing 2.6.3 without this for now and we'll have to figure it out for 2.x.

2018-04-19 06:08 UTC, Jako commented
I will recreate that PR

2018-04-23 14:48 UTC, Mark-H commented
Closing as a new PR will be created.

2018-04-23 14:48 UTC, closed without merging

2018-04-25 19:48 UTC, Jako commented
I recreate it in 2.x