Add template icon for resources in serch results.
modxcms/revolution pull request #13882
Opened 2018-04-28 12:47 UTC by SintezCode

### What does it do?
Add template icon for resources in uberbar serch results.

### Why is it needed?
If we have some resources with same names, but different templates, in search results we see its icons to distinguish them.

### Related issue(s)/PR(s)
![result](https://i.imgur.com/nD3y7kk.png "Result")

PR to 2.6.x branch:
#13869

2018-04-29 20:59 UTC, alroniks requested changes

2018-04-29 20:59 UTC, Alroniks commented on core/model/modx/processors/search/search.class.php
> +            if($this->results['icon'])$this->results['icon']=str_replace('icon-','',$this->results['icon']);
Please, do not use such short `if` statements. It is difficult to read such code and find errors in case of any issues in the future.

2018-04-29 20:59 UTC, Alroniks commented on core/model/modx/processors/search/search.class.php
> +                'icon' => $record->get('icon')?:false,
Minor, but variant (with spaces) `$record->get('icon') ?: false` more readable. I would recommend use PSR rules.

2018-06-06 12:34 UTC, alroniks approved these changes
Fixed some code styles and issue with removing icon- prefix by myself, but other parts of the code work pretty well.

2018-06-06 12:35 UTC, Alroniks commented
How it looks now:
![screenshot 2018-06-06 15 31 24](https://user-images.githubusercontent.com/303498/41038534-2ee1de0a-699f-11e8-96f1-326bc4173e56.png)

2018-06-06 12:36 UTC, Alroniks commented
Code owners attention required :-P @opengeek @Mark-H

2018-06-06 12:40 UTC, Mark-H approved these changes

2018-06-06 13:37 UTC, merged