Fix some minor XSS issues reported in security ticket 69
modxcms/revolution pull request #13887
Opened 2018-05-01 22:01 UTC by Mark-H

### What does it do?
Applies htmlspecialchars to some processors which were exposing 3 stored XSS issues. 

### Why is it needed?
Tighten security a bit. 

None of these XSS issues should have any far-reaching consequences. They all require manager access for starters. Also

- The one in the recently edited dashboard widget would only be useful to XSS yourself, as the resource list only shows resources you personally edited. Perhaps a problem when sharing user accounts. 
- Access to edit the top menu (actions) is needed for number 2. That's an advanced permission that only full admins should have.
- Adding/editing setting permission is needed for number 3. Also, that should already be limited to full admin users.

### Related issue(s)/PR(s)
Security inbox ticket number 69. Reported by Aman Sahey on April 25th.

2018-05-02 06:54 UTC, Jako commented
Maybe you should use `$modx->getOption('modx_charset', $options, 'UTF-8')`

2018-05-02 20:30 UTC, opengeek requested changes
I concur with @Jako in that you should be using `$modx->getOption('modx_charset', $options, 'UTF-8')` rather than hardcoding UTF-8.

2018-05-19 08:17 UTC, Omeryl commented
Just a minor note, looks like we're going to need to go back and fix this up in a number of other places: https://github.com/modxcms/revolution/blob/4e82a449ca7e152e6bad6507d4b705539af1ae0f/core/model/modx/processors/security/group/getnodes.class.php#L134

2018-05-24 21:54 UTC, opengeek approved these changes

2018-05-24 22:07 UTC, merged