Template picker
modxcms/revolution pull request #13905
Opened 2018-05-18 11:32 UTC by Oetzie

### What does it do?
The new template picker feature. Before you create a new resource you will get a window where you can choose the 'pagetitle' and preview the 'template' (if screenshot is available). This PR also includes the new 'parent field combo' and 'template field combo'.

2018-05-19 07:49 UTC, Jako commented
Nice solution! But could you remove the css changes from the PR and mark it with 'build required'. The scss changes are enough and don't lead to large merge conflicts.

2018-06-04 09:26 UTC, wax100 commented
@Oetzie 
If I upload printscreen of Full page,  I receiver cropped image. 
![e069208c-ff4e-4476-8670-10117bc8c579](https://user-images.githubusercontent.com/4846064/40909257-6c61e3ae-67e9-11e8-9ddc-33361969f2ee.png)
 
![screenshot_2](https://user-images.githubusercontent.com/4846064/40909571-2bd9ceae-67ea-11e8-9cf0-54118e481115.png)
Is it possible to add magnific popup ? 
Or something like http://verstaemvse.ru/demo/zoom/ ?

2018-06-05 09:56 UTC, bezumkin commented
You need to rebase this PR with current 3.x branch. 

Right now there a lot of old code, for example you can't upload image in the root of media source because of old media sources. This will stop many people from test it.

2018-08-09 20:26 UTC, Mark-H requested changes
Few small tweaks needed, but overall this looks like a solid improvement that especially end-users should find useful.

2018-08-09 20:26 UTC, Mark-H commented on core/model/modx/processors/resource/gettoolbar.class.php
> +            $record = '{context_key: \"' . $this->modx->getOption('default_context') . '\", parent: 0}';
Probably safer to turn this into a `json_encode` to ensure it's valid JSON.

2018-08-09 20:26 UTC, Mark-H commented on core/model/modx/processors/resource/gettoolbar.class.php
> +            $record = '{class_key: \"modWebLink\", context_key: \"' . $this->modx->getOption('default_context') . '\", parent: 0}';
Same as [above](https://github.com/modxcms/revolution/pull/13905/review_comment/create#r209064301)

2018-08-09 20:26 UTC, Mark-H commented on core/model/modx/processors/resource/gettoolbar.class.php
> +            $record = '{class_key: \"modSymLink\", context_key: \"' . $this->modx->getOption('default_context') . '\", parent: 0}';
Same as [above](https://github.com/modxcms/revolution/pull/13905/review_comment/create#r209064301)

2018-08-09 20:26 UTC, Mark-H commented on core/model/modx/processors/resource/gettoolbar.class.php
> +            $record = '{class_key: \"modSymLink\", context_key: \"' . $this->modx->getOption('default_context') . '\", parent: 0}';
Same as [above](https://github.com/modxcms/revolution/pull/13905/review_comment/create#r209064301)

2018-08-09 20:26 UTC, Mark-H commented on manager/assets/modext/core/modx.js
> +                        console.log(data2);
These `console.log` statements should be replaced with "proper" error handling. That could be as simple as an alert showing the failure reason or a `MODx.Msg`

2018-08-09 20:26 UTC, Mark-H commented on manager/assets/modext/widgets/core/modx.combo.js
> +            getGroup : function(label, time) {
Help me out here - why is this including the time? What's that for?

2018-08-09 20:26 UTC, Mark-H commented on manager/assets/modext/widgets/core/modx.combo.js
> +                '<div class="x-combo-list-group">{this.label}</div>' +
As the `label` appears to be coming from a remote source , please add `htmlEncode` as filter to it to prevent persistent XSS.

2018-08-09 20:26 UTC, Mark-H commented on manager/assets/modext/widgets/core/modx.combo.js
> +                '<div class="x-combo-list-group">{this.label}</div>' +
Same as earlier, please add `htmlEncode` to `this.label` to prevent potential XSS.

2019-01-15 07:38 UTC, Oetzie commented
Sorry for late response, I will try to fix the feedback from @Mark-H thursday

2019-01-22 13:34 UTC, JoshuaLuckers commented
Let us know if we can help you @Oetzie

2019-05-04 11:07 UTC, Ibochkarev commented
@Oetzie Is there time to finish the job you have started?

2019-08-15 19:33 UTC, Ibochkarev commented
@Oetzie ping...

2019-09-01 14:35 UTC, Mark-H commented
@gpsietzema I know this is something Sterc was really excited about, but it's conflicting massively against latest 3.x, and there has not been movement in 9 months on any of the requested changes. 

If you're still excited about this feature, can you please work it into your internal planning to keep this moving? For now I'm going to close the PR, but I hope to see a fresh one opened again soon. :)

2019-09-01 14:35 UTC, closed without merging