Added phpunit/phpunit ^5 as development requirement.
modxcms/revolution pull request #13913
Opened 2018-05-26 14:04 UTC by JoshuaLuckers

### What does it do?
It marks phpunit/phpunit ^5 as development requirement in composer.json

### Why is it needed?
To help new contributors set up a development environment it would be helpful if the development packages were included in composer.json. 
In this case it's only phpunit.

### Related issue(s)/PR(s)
#13910

2018-05-27 11:52 UTC, alroniks submitted a review, later dismissed
It works perfectly.

2018-05-27 13:54 UTC, opengeek requested changes
This actually does not work for PHP 7.2. See the xPDO composer.json for an example of how to specify the dependency to work on 5.6 through 7.2.

```    "require-dev": {
        "phpunit/phpunit": "~5.7|~6.5"
    },
```

2018-05-27 19:35 UTC, JoshuaLuckers reviewed
Thanks! I've made the necessary changes.

2018-05-29 13:42 UTC, opengeek approved these changes

2018-05-29 13:44 UTC, merged