Add ID number to manager pages (resources and elements)
modxcms/revolution pull request #13914
Opened 2018-05-26 15:11 UTC by JoshuaLuckers

### What does it do?
It makes the ID of the object on various manager pages visible after the title/name.
This improves usability of the current manager design.

### Why is it needed?
It makes it easier to find the ID of a certain object (like the ID of a page). More discussion about this can be found in issue #11096.

MODX 3 is right around the corner, but it would still be very helpful to have this in a 2.* release. 

### Related issue(s)/PR(s)
#11096

2018-05-26 15:48 UTC, JoshuaLuckers commented
I didn't check and/or add permissions as suggested by [wuuti](https://github.com/modxcms/revolution/issues/11096#issuecomment-285280918) in issue #11096

2018-06-04 12:28 UTC, Mark-H requested changes
Per the discussion about this in #11096, this should be configurable. 

Could be a setting or the mentioned permissions. I think the permissions would be best as those already toggle similar behavior. Perhaps the permissions are already available to check with `MODx.perm.tree_show_element_ids`, or they would need to be checked for in the controller first. 

Thanks for working on this - always good to see an issue from 2014 (or before!) being addressed!

2018-06-04 12:46 UTC, JoshuaLuckers commented
Thanks @Mark-H. I'm not sure if the permission is useful (since a user can still see it in the URL but that would be worth it's own issue/discussion). For now I will check the permissions like you suggested.

I love cleaning and fixing some old bugs. It's the small things that improve the product.

2018-06-04 13:52 UTC, Alroniks commented
System settings now overloaded enough in MODX. Permissions also not a simple thing in MODX but according to show/hide something it better place to describe behavior. I would review existing system settings somehow to move some of them to permissions area.

2018-06-05 04:54 UTC, JoshuaLuckers commented
The ID's are now only visible when the user has "tree_show_element_ids" permission.

2018-06-05 07:22 UTC, alroniks requested changes
All looks good except that for resources need to use more suitable permission.

2018-06-05 07:22 UTC, alroniks commented on manager/assets/modext/widgets/resource/modx.panel.resource.js
> +                if (MODx.perm.tree_show_element_ids === 1) {
For resources need to use proper permissions according to resources instead of elements. This one `tree_show_resource_ids`

2018-06-05 07:22 UTC, alroniks commented on manager/assets/modext/widgets/resource/modx.panel.resource.js
> +                    if (MODx.request.a !== 'resource/create' && MODx.perm.tree_show_element_ids === 1) {
tree_show_resource_ids

2018-06-05 07:22 UTC, alroniks commented on manager/controllers/default/resource/update.class.php
> +        MODx.perm.tree_show_element_ids = '.($this->modx->hasPermission('tree_show_element_ids') ? 1 : 0).';
tree_show_resource_ids

2018-06-05 08:00 UTC, JoshuaLuckers commented on manager/assets/modext/widgets/resource/modx.panel.resource.js
> +                if (MODx.perm.tree_show_element_ids === 1) {
I changed it, thanks for reviewing!

2018-06-06 08:11 UTC, alroniks approved these changes

2018-06-06 08:14 UTC, Alroniks commented
I've tested this PR. All works fine, ids showing/hiding depends on permissions, resources and elements uses proper permissions.
Also, I found an issue with undefined on template pages but I've already fixed (see the last commit).
So, ready for merging I guess.
@opengeek @Mark-H

2018-06-06 08:21 UTC, Mark-H approved these changes

2018-06-06 11:00 UTC, merged