Load all mgr permissions at once to MODx.perm
modxcms/revolution pull request #13924
Opened 2018-06-10 07:22 UTC by JoshuaLuckers

### What does it do?
Load all mgr permissions at once to MODx.perm and removes related JS code scattered around. 

### Why is it needed?
Manager permissions are concentrated in one place. This means that developers do not have to do this manually every time they want to check for a permission using JavaScript.

### Related issue(s)/PR(s)
Fixes #12211

2018-06-10 07:24 UTC, JoshuaLuckers commented
This should target 3.x, however since the 3.x branch is a bit to far behind I decided to target 2.x.
When the 3.x branch is more up to date I will retarget this PR.

2018-06-25 12:21 UTC, Mark-H submitted a review, later dismissed
Nice one!

2018-06-25 14:10 UTC, alroniks requested changes

2018-06-25 14:10 UTC, Alroniks commented on manager/assets/modext/widgets/security/modx.panel.groups.roles.js
> +        if (MODx.perm.usergroup_view1) {
Look like here a typo after removing `==1`

2018-07-09 13:15 UTC, JoshuaLuckers commented
@Alroniks should There is a conflicting file. Should I fix this or is this something an integrator should do?

2018-07-09 15:13 UTC, Alroniks commented
@JoshuaLuckers Diffs looks easy but there are a lot of stings in diff. It would be nice to do rebase and fix conflict from your side to be sure that we don't miss something.

2018-07-10 14:04 UTC, JoshuaLuckers commented
@Alroniks done! 👍

2018-07-10 20:59 UTC, alroniks approved these changes

2018-07-27 22:39 UTC, Alroniks commented
@Mark-H Could you reapprove it, please? There was a minor issue with the typo that fixed and also code was rebased to avoid conflicts. Nothing more.

2018-08-09 06:37 UTC, JoshuaLuckers commented
@Mark-H ping

2018-08-09 20:12 UTC, Mark-H approved these changes
Pong!

2018-08-13 15:14 UTC, Alroniks commented
It's already approved but I am wondering shouldn't it be targeted to 2.x because no any BC is broken?
@Mark-H @opengeek

2018-08-13 15:29 UTC, JoshuaLuckers commented
I decided to target 3.x because it would be a good opportunity for extra developers when they are testing and/or modifying their extra's to be compatibly with version 3.x to also clean up their code if they manually add those permissions as described in issue #12211.

2018-08-14 07:27 UTC, Alroniks commented
Yes, make sense according to extras. Merging.

2018-08-14 07:29 UTC, merged