Design updates
modxcms/revolution pull request #13934
Opened 2018-06-25 10:14 UTC by bezumkin

### What does it do?
- Added new system setting "manager_logo"
- Design updates

### Why is it needed?
To release MODX 3

### Related issue(s)/PR(s)
#13875

![screen1](https://user-images.githubusercontent.com/1257284/41844676-20752f2e-789b-11e8-92bc-461b8fd67bfd.png)

2018-06-25 10:30 UTC, sottwell commented
Sweet!

2018-06-25 12:15 UTC, Mark-H commented on manager/assets/modext/core/modx.layout.js
> +                            header.on('click', function() {
Can we just make this a plain old link so it's accessible and things like ctrl+click work out of the box?

2018-07-04 13:57 UTC, Mark-H requested changes
Link should be a link, as commented.

2018-07-04 14:11 UTC, bezumkin commented
@Mark-H problem with js link solved

2018-07-04 16:00 UTC, Mark-H approved these changes

2018-07-04 16:02 UTC, Mark-H commented
Deleting it is not really the same as turning it into a proper link, but I guess that does do away with the a11y concerns of it not being the right semantic element too ¯\_(ツ)_/¯

2018-07-27 22:37 UTC, alroniks approved these changes

2018-07-28 09:20 UTC, alroniks approved these changes

2018-07-28 09:21 UTC, merged