Login forgotten password improvements
modxcms/revolution pull request #13987
Opened 2018-07-10 16:39 UTC by JoshuaLuckers

### What does it do?
If a password reset is done for a non-existing user it also shows the success message. 
The style for is-success is also being added.

### Why is it needed?
It's a fix for issue #13976

### Related issue(s)/PR(s)
#13976

2018-07-16 14:01 UTC, Mark-H commented
This might cause a conflict with part of #13984 depending on what is merged in what order. This PR seems to fix the problem where the response might indicate if a user existed or not (which would be seen as a potential security issue) while both address missing styling for success messages.

2018-07-16 14:07 UTC, JoshuaLuckers commented
Didn't see that PR. I will remove my changes for the style change.

2018-07-16 15:08 UTC, opengeek commented
Why is this not targeting 2.x?

2018-07-16 18:30 UTC, JoshuaLuckers commented
@opengeek solved

2018-07-27 21:38 UTC, alroniks approved these changes

2018-07-27 21:48 UTC, alroniks requested changes
It seems that you should bring from 3.x code from the template, because now message disappears at all because in curent template not user placeholder `success_message`.
It may cause conflicts after but it shouldn't bring new bugs into 2.x I guess.

2018-07-28 10:34 UTC, JoshuaLuckers commented
Good catch @Alroniks! I was too rushed and did not check it myself. Thanks.

2018-08-09 20:06 UTC, Mark-H approved these changes

2018-08-10 10:43 UTC, alroniks approved these changes

2018-08-10 10:43 UTC, merged