[3.x] [ReUp] Changed status message appearance and position
modxcms/revolution pull request #14003
Opened 2018-07-19 13:10 UTC by jonleverrier

### What does it do?
This PR changes the default appearance and position of the status notification (the one you receive after saving a resource).

![modx3_message_save2](https://user-images.githubusercontent.com/2373940/42943719-dcccb1d0-8b63-11e8-9158-6abddea8f52c.gif)

![screen shot 2018-07-19 at 14 32 47](https://user-images.githubusercontent.com/2373940/42943740-e850c604-8b63-11e8-808a-09f8b83cc582.png)

Based on feedback from Slack, this PR also adds some css utility styles so you can position the status message in different positions on the screen. These are `.modx-status-msg.has-position-center-center`, `.modx-status-msg.has-position-center-top`, and `.modx-status-msg.has-position-right-top`. 

If one day, somebody decides to create a system setting for the position, they can hook into these css utility classes.

**Screen shot of `.modx-status-msg.has-position-right-top`**
![screen shot 2018-07-19 at 14 26 41](https://user-images.githubusercontent.com/2373940/42943755-f1292f3c-8b63-11e8-8621-256e9504b448.png)
**Screen shot of `.modx-status-msg.has-position-center-top`**
![screen shot 2018-07-19 at 14 26 16](https://user-images.githubusercontent.com/2373940/42943756-f1405a36-8b63-11e8-9870-60f24920b4de.png)
**Screen shot of `.modx-status-msg.has-position-center-center`**
![screen shot 2018-07-19 at 14 25 35](https://user-images.githubusercontent.com/2373940/42943757-f156dc0c-8b63-11e8-82be-a3990133fd80.png)

### Why is it needed?
In 2.x the status message was almost invisible. In MODX 3 we have lots of new styles - styling up the status message makes the product feel more consistent. 

It also moves the status message away from the action buttons at the top, which are unusable whilst the message is in display.

### Related issue(s)/PR(s)
Mentioned in #13988, #13942

2018-07-19 17:55 UTC, JoshuaLuckers requested changes
It might be a good idea to define the variables in `_colors-and-vars.scss` like `$modx-status-msg-bg: $white`.

It’s makes it easier to customize if those variables are in one file.

2018-07-19 18:40 UTC, jonleverrier commented
@JoshuaLuckers The background colour is being defined from the default success colour, which i think is `$green`. You're saying it's worth creating a variable just for the status message background colour?

2018-07-19 18:47 UTC, JoshuaLuckers commented
All color variables should be defined in `_colors-and-vars.scss`. The background color was just a little example.

2018-07-19 19:02 UTC, jonleverrier commented
Understood. The status message colour (text, icon, background) is using variables from `_colors-and-vars.scss`. If you think I should create new variables specific to the status message, let me know and i'll get this changed!

2018-07-20 07:13 UTC, JoshuaLuckers commented
I do not know what the core team prefers. It's my personal preference to have variables for specific components to be in a "variables" file.
For example, I want to the text to be black and no border radius for this specific component. I now have to modify the "core" component file and increase the risk of my custom modifications to be overwritten when updating MODX. If those specific variables where in the "variables" file I could create a custom variables file "overruling" the "core" variables and thus reducing the risk of my changes being overwritten. 

TLTR: It makes it easier to theme core components.

2018-07-29 15:39 UTC, jonleverrier commented
@JoshuaLuckers added specific sass variables for the status message

2018-08-10 09:14 UTC, jonleverrier commented
@Mark-H @Alroniks - is this likely to get merged into 3.x or does it require more discussion?

2018-08-10 11:45 UTC, OptimusCrime commented
This looks fine by me.

2018-08-10 13:02 UTC, Alroniks commented
I like this solution but have not check yet how it works, so cannot approve right now. But will try today.

2018-08-13 12:57 UTC, Mark-H submitted a review, later dismissed

2018-08-13 13:22 UTC, alroniks commented on _build/templates/default/sass/index.scss
>    width: 25%;
It seems 25% too much. On wide screens, it looks strange. I guess it can be solved by adding max-width property.
![](https://i.imgur.com/kOFgGsx.png)

2018-08-13 13:33 UTC, jonleverrier commented on _build/templates/default/sass/index.scss
>    width: 25%;
happy to add a max-width to the message. I guess the original thinking behind the 25% width, is that is takes up 1 quarter of your screen, regardless of how wide.

2018-08-13 13:42 UTC, Alroniks commented on _build/templates/default/sass/index.scss
>    width: 25%;
Yes, of course. But on too wide screens it looks not so awesome as expected.

2018-08-13 13:50 UTC, jonleverrier commented
Should be good to go now @Alroniks @Mark-H

2018-08-13 14:00 UTC, jonleverrier commented
should be good to go now @Alroniks @Mark-H !

2018-08-13 14:02 UTC, alroniks approved these changes

2018-08-13 15:15 UTC, Mark-H approved these changes

2018-08-13 15:24 UTC, merged