[ReUp] Default media source type
modxcms/revolution pull request #14012
Opened 2018-07-24 14:07 UTC by JoshuaLuckers

### What does it do?
It adds a new system setting to set the Default Media Source Type. It also selects the default media source type automatically when creating a new Media Source. 

### Why is it needed?
It fixes issue #13918

### Related issue(s)/PR(s)
Issue #13918

2018-07-24 14:20 UTC, Alroniks commented on setup/includes/upgrades/common/3.0.0-media-soure-type-system-setting.php
> +    $defaultMediaSourceTypeSystemSetting->set('key','default_media_source_type');
This code can be simplified using `fromArray()` method. It will become more readable.

2018-07-30 13:36 UTC, Alroniks commented
Hi @JoshuaLuckers Did you test it with context/usergroup/user settings?

2018-07-30 13:37 UTC, Alroniks commented
And as it does not brake BC it should be targeted into 2.x.

2018-07-30 14:01 UTC, JoshuaLuckers commented
> Did you test it with context/usergroup/user settings?
No, I will test it in the upcoming days.

> And as it does not brake BC it should be targeted into 2.x.
Since it's a "new" system setting with new lexicons I think it makes more sense to introduce it in 3.x.

2018-07-30 14:32 UTC, Alroniks commented
By SemVer 2.7 also is opened for new features and it's an easier to avoid conflicts during the merging in the future when some functionality crossing.

2018-07-30 15:00 UTC, JoshuaLuckers commented
Fair enough! I will also retarget the PR.

2018-08-09 19:54 UTC, Mark-H commented
@JoshuaLuckers I don't think you need the upgrade script you added in that last commit - when installing, it will already create new settings from the source in _build/data/.

2018-08-09 20:43 UTC, JoshuaLuckers commented
Even when upgrading?

2018-08-09 20:48 UTC, Mark-H commented
Yeah. [All settings are put into the transport package](https://github.com/modxcms/revolution/blob/2.x/_build/transport.core.php#L258-L267). Because `UPDATE_OBJECT` is set to false it doesn't update anything that's already there (identified by the key), but it will create stuff that isn't already there.

2018-08-10 07:28 UTC, JoshuaLuckers commented
Thanks @Mark-H. I will remove the upgrade script.

2018-08-13 12:58 UTC, Mark-H submitted a review, later dismissed
Excellent!

2018-08-13 13:09 UTC, alroniks approved these changes
It works, that's I would like to say. 👍

2018-08-13 13:31 UTC, Alroniks commented on setup/lang/en/upgrades.inc.php
> +$_lang['media_source_type_system_setting_success'] = 'System Setting `Default Media Source Type` added.';
Looks like this lexicon strings no needed anymore too.

2018-08-13 13:34 UTC, alroniks requested changes
Need to add lexicons for new system setting.

2018-08-13 13:34 UTC, Alroniks commented on _build/data/transport.core.system_settings.php
> +$settings['default_media_source_type']= $xpdo->newObject('modSystemSetting');
And also lexicons for this new system setting are missed.

2018-08-14 07:38 UTC, Alroniks commented
Hi @JoshuaLuckers Please, have a look at my comments. Lexicons definitely should be added.

2018-08-14 07:43 UTC, JoshuaLuckers commented
When I have some time I will do so.

2018-08-14 13:03 UTC, alroniks approved these changes

2018-08-14 13:11 UTC, Alroniks commented
@Mark-H Could you have a look again? The missed code was added, now it looks fine.

2018-08-14 13:16 UTC, Mark-H approved these changes

2018-08-14 14:37 UTC, merged