Actual versions of PHP in Travis
modxcms/revolution pull request #14047
Opened 2018-08-15 23:24 UTC by Alroniks

### What does it do?
It removes hhvm as unsupported from Travis builds. As well it adds actual 7.2 version of PHP.

### Why is it needed?
HHVM build always failed so it makes sense just remove it to do not load Travis by useless tasks. Also, the current actual and latest version of PHP is 7.2 and we need to be sure that MODX works on the actual version of PHP as well.

### Related issue(s)/PR(s)
None

2018-08-16 06:49 UTC, JoshuaLuckers requested changes
PHP 5.4 and 5.5 are end of life and no longer supported by PHP. The MODX server requirements also recommend PHP 5.6 or higher (PHP 5.5 as minimum. However I don't think we should support End of Life versions of PHP).

2018-08-16 07:22 UTC, alroniks commented
@JoshuaLuckers It was discussed many times, while MODX can work on old versions PHP, we will support it. But if some new functions will require more modern version, we'll drop support. So now config based on composer file, that requires 5.4 as a minimum. 
@Mark-H has nice charts with the actual state of using PHP versions across MODX installations and it says that still a lot of people use old versions.

2018-08-16 07:23 UTC, JoshuaLuckers commented
I remember the discussion, good point!

2018-08-16 07:23 UTC, JoshuaLuckers approved these changes

2018-08-16 09:04 UTC, Jako approved these changes

2018-08-17 16:51 UTC, Mark-H commented
@opengeek Were you looking at this the other day?

2018-08-17 17:29 UTC, opengeek commented
@Mark-H wrote:
> @opengeek Were you looking at this the other day?

No. This looks good to me though.

2018-08-17 17:29 UTC, opengeek approved these changes

2018-08-17 20:57 UTC, merged