changed resource query to group only by id
modxcms/revolution pull request #14065
Opened 2018-08-28 12:35 UTC by wholegroup

### What does it do?
It changes groping fields to make the query faster.

### Why is it needed?
It generates a faster resource query.

### Related issue(s)/PR(s)
It fixes #14064

2018-08-28 13:55 UTC, Jako requested changes
To avoid only_full_group_by issues, the group by has to contain all selected columns. Maybe there is a different possibility to work without any group by.

2018-08-28 15:41 UTC, Jako commented
Thats better. Thanks!

2018-08-28 15:41 UTC, wholegroup commented
@Jako 
I've removed `GROUP BY` and made counting children via subqueries. Now it works even much faster.

2018-08-30 09:50 UTC, Jako approved these changes

2018-08-30 09:53 UTC, Jako commented
Checked, works fine.

2018-08-30 17:10 UTC, opengeek approved these changes

2018-08-30 20:35 UTC, Alroniks commented
I'll merge it tomorrow.

2018-08-31 10:11 UTC, merged