Fixing Double-click of image in Media Browser goes to blank page
modxcms/revolution pull request #14076
Opened 2018-09-07 10:00 UTC by Jako

### What does it do?
Make sure that MODx.Media.onSelect is not executed. This method hides `this.config.animEl || null`, which means that MODx.Media is hidden accidentally.

### Why is it needed?
Double-click of image in Media Browser goes to blank page.

### Related issue(s)/PR(s)
#14075

2018-09-07 11:54 UTC, jonleverrier commented
I've tested this PR and it works as described.

2018-09-07 17:24 UTC, JoshuaLuckers reviewed
Can the unreachable code be removed?

2018-09-07 18:40 UTC, Jako commented
I really don’t know where it was used, so yes.

2018-09-07 21:13 UTC, alroniks requested changes

2018-09-07 21:13 UTC, Alroniks commented on manager/assets/modext/widgets/media/modx.browser.js
>          console.log('MODx.Media#onSelect', data);
I guess console.log call should be definitely removed.

2018-09-11 07:08 UTC, Jako commented
I have removed all not needed 'make sure this is never used' code and the logging in those methods. The only part where a double click in the media browser leads to an action still works (doubleclick a file during editing a file selecting template variable or a file insert in the RTE. I did not find another place where the double click is used.

2018-10-13 10:10 UTC, gpsietzema commented
Works as expected.

2018-10-17 02:01 UTC, merged