Remove outdated classes for converting evo tags to revo
modxcms/revolution pull request #14133
Opened 2018-11-08 20:46 UTC by Alroniks

### What does it do?
It removes outdated and deprecated in 2.7 classes `modParser095`, `modTranslate095` and `modTranslator`.

### Why is it needed?
It used for migration Evo sites to Revo, but as Evo does not on a support any more officially and it is an independent project, it does not make sense to keep this functionality in the third version.

### Related issue(s)/PR(s)
#14131

2018-11-23 10:41 UTC, Mark-H approved these changes

2018-12-20 07:26 UTC, JoshuaLuckers requested changes
Is it possible to solve the "merge conflicts"? :)

2018-12-20 09:24 UTC, alroniks commented
@JoshuaLuckers This files should be deleted at all so absolutely no make sense to resolve conflicts. It can be done during the merging process. I can handle this if you will approve it.

2018-12-20 09:29 UTC, JoshuaLuckers approved these changes

2018-12-20 09:59 UTC, merged