Add some deprecated logging
modxcms/revolution pull request #14136
Opened 2018-11-12 19:41 UTC by Jako

### What does it do?
Add $modx/$xpdo->deprecated calls.

### Why is it needed?
Log deprecated methods/classes

### Related issue(s)/PR(s)
#13199

2018-11-12 22:33 UTC, Mark-H requested changes

2018-11-12 22:33 UTC, Mark-H commented on core/model/modx/processors/system/clearcache.class.php
> +        $this->modx->deprecated('2.1.4', 'Use a dedicated cache partition rather than specifying paths.', 'modSystemClearCacheProcessor clearByPaths');
This method is called on each request, better to place this inside the `if (!empty($paths))` below so it only logs when the processor is called with paths to clear.

2018-11-13 13:24 UTC, Jako commented on core/model/modx/processors/system/clearcache.class.php
> +        $this->modx->deprecated('2.1.4', 'Use a dedicated cache partition rather than specifying paths.', 'modSystemClearCacheProcessor clearByPaths');
This is fixed.

2018-11-13 13:31 UTC, Mark-H approved these changes
Thanks :)

2018-11-13 13:31 UTC, alroniks approved these changes

2018-11-13 13:37 UTC, merged