Add required and suggested PHP extensions to composer.json
modxcms/revolution pull request #14150
Opened 2018-11-23 11:11 UTC by JoshuaLuckers

### What does it do?
This adds required and suggested PHP extensions to composer.json.

### Why is it needed?
We want to check and suggest the system requirements when installing MODX via composer.

### Related issue(s)/PR(s)
Issue #14048

2018-11-26 14:12 UTC, Mark-H submitted a review, later dismissed

2018-11-26 14:27 UTC, alroniks submitted a review, later dismissed

2018-12-03 22:14 UTC, opengeek requested changes
I don't think ext-imagick is required for MODX is it? Is this a new requirement? Because I've not installed this extension in quite some time and am now blocked from installing. :P

2018-12-03 22:25 UTC, alroniks commented
Jason is right. Imagick can be replaced (and it does) by php-gd. It works better but it is not installed everywhere so we can not lock MODX to use this extension. I suggest moving it to recommended section @JoshuaLuckers

2018-12-04 05:52 UTC, JoshuaLuckers commented
It’s listed as one of the [server requirements in the docs](
https://docs.modx.com/revolution/2.x/getting-started/server-requirement).

I will do the suggested changes later today. 👍

2018-12-04 07:38 UTC, Alroniks commented
But php-gd is really required for thumbnails and imagick is missed in recommended section.

2018-12-04 07:42 UTC, JoshuaLuckers commented
> But php-gd is really required for thumbnails and imagick is missed in recommended section.

My misunderstanding!

2018-12-05 14:37 UTC, Alroniks commented
Not sure, but maybe it does not make sense to install imagic in travis.

2018-12-06 20:21 UTC, alroniks approved these changes

2018-12-06 20:22 UTC, Alroniks commented
Now it looks better. @opengeek

2018-12-29 01:06 UTC, Mark-H approved these changes
Not sure if this can be merged with a `changes requested` review from the other code owner.. but LGTM.

2018-12-29 08:24 UTC, alroniks commented
@Mark-H We have to wait for approval from @opengeek in this case.

2019-01-09 19:29 UTC, JoshuaLuckers commented
@opengeek I made the suggested changes.

2019-01-24 15:52 UTC, opengeek approved these changes

2019-01-25 11:10 UTC, merged