Update config.js.php processor to be class based
modxcms/revolution pull request #14161
Opened 2018-11-28 21:23 UTC by Mark-H

### What does it do?
In #14160 I made the deprecated message a bit more useful for identifying offending processors, which immediately pointed to the config.js.php which is called on each manager request as loading the config into a JS object. So, I wrapped it into a modProcessor class to resolve that, and added a migration to remove the old processor file when running the 2.7.1 setup. 

### Why is it needed?
The deprecated log message on each manager request will not only get annoying fast, but as it's not very useful until #14160, this particular instance may encourage people to disable the deprecated logging preventing them from seeing other deprecated usages that need to be fixed. 

### Related issue(s)/PR(s)
#14160

2018-11-28 21:40 UTC, JoshuaLuckers requested changes

2018-11-28 21:40 UTC, JoshuaLuckers commented on setup/includes/upgrades/common/2.7.1-cleanup-script.php
> + * Common upgrade script for 2.5 to clean up legacy files for download distributions.
I don’t think this is the right description for this file 😋

2018-11-29 10:06 UTC, Jako approved these changes

2018-12-03 22:07 UTC, opengeek approved these changes

2018-12-05 07:24 UTC, merged