Some code inspection fixes
modxcms/revolution pull request #14178
Opened 2018-12-03 20:57 UTC by JoshuaLuckers

### What does it do?
It fixes some issues/suggestions after running the code inspection.

### Why is it needed?
To improve the quality of the code

### Related issue(s)/PR(s)
None that I'm aware of.

2018-12-03 21:27 UTC, Mark-H requested changes

2018-12-03 21:27 UTC, Mark-H commented on manager/controllers/default/context/update.class.php
> +            return $this->failure(sprintf($this->modx->lexicon('context_err_load_data'), $this->context->toArray()));
This doesn't seem right - either `$this->context->toArray()` should be the second param to `$this->modx->lexicon` if it's meant to add information to the error message, or the context should be returned in a different way if it's expected to be in the failure response... my guess is it should be the first.

2018-12-03 22:12 UTC, JoshuaLuckers commented on manager/controllers/default/context/update.class.php
> +            return $this->failure(sprintf($this->modx->lexicon('context_err_load_data'), $this->context->toArray()));
I think you are right. Will check it tomorrow.

2018-12-06 18:03 UTC, JoshuaLuckers commented on manager/controllers/default/context/update.class.php
> +            return $this->failure(sprintf($this->modx->lexicon('context_err_load_data'), $this->context->toArray()));
Do I also need to change the lexicon when I pass `$this->context->toArray()` as second parameter in `$this->modx->lexicon`?

2018-12-07 09:22 UTC, Mark-H commented on manager/controllers/default/context/update.class.php
> +            return $this->failure(sprintf($this->modx->lexicon('context_err_load_data'), $this->context->toArray()));
I'm not sure what's supposed to happen in that line, but if the lexicon string uses [[+placeholders]], no. Perhaps it's not using the context in which case it could also be removed.

2018-12-28 21:31 UTC, Mark-H approved these changes

2018-12-29 08:14 UTC, alroniks approved these changes

2019-01-02 15:35 UTC, merged