Don't remove static files if automated static files are turned off
modxcms/revolution pull request #14228
Opened 2018-12-31 17:04 UTC by Jako

This really fixes the issue where old static files where removed even if the automate static files system setting was turned off for that element type. It was only partly fixed in #14208, which added a check for removing the file, when the static file path was changed.

### What does it do?
A check for the automatic static files system setting is added to the modElementRemoveProcessor class.

### Related issue(s)/PR(s)
Issue: #14206, #140206
PR that created the issue: #14135

2019-01-01 14:28 UTC, JoshuaLuckers requested changes

2019-01-01 14:28 UTC, JoshuaLuckers commented on core/model/modx/processors/element/remove.class.php
> +            $pathinfo = pathinfo($this->staticFilePath);
```suggestion
            $dirname = pathinfo($this->staticFilePath, PATHINFO_DIRNAME);
```

2019-01-01 14:28 UTC, JoshuaLuckers commented on core/model/modx/processors/element/remove.class.php
> +            if (!empty($pathinfo['dirname'])) {
To me it would make more sense to check for things like this in the `cleanupStaticDirectories` method to prevent code duplication.

2019-01-01 14:28 UTC, JoshuaLuckers commented on core/model/modx/processors/element/remove.class.php
> +                $this->cleanupStaticDirectories($pathinfo['dirname']);
```suggestion
                $this->cleanupStaticDirectories($dirname);
```

2019-01-01 16:52 UTC, Jako commented
@JoshuaLuckers I agree with your review, but code changes that are not bugfixes should be done in 3.x.

2019-01-02 16:06 UTC, JoshuaLuckers approved these changes

2019-01-09 11:14 UTC, Mark-H approved these changes
👍

2019-01-12 22:01 UTC, merged