Make working Preview menu option in the recent edited resources widget
modxcms/revolution pull request #14234
Opened 2019-01-03 07:45 UTC by Alroniks

### What does it do?
It fixes the wrong behavior of the preview button in recent edited resources widget. 

### Why is it needed?
Make a menu option (button) working as expected.

### Related issue(s)/PR(s)
#14142 point 1.1

2019-01-03 14:32 UTC, Mark-H submitted a review, later dismissed

2019-01-03 19:53 UTC, JoshuaLuckers requested changes

2019-01-03 19:53 UTC, JoshuaLuckers commented on manager/assets/modext/widgets/security/modx.grid.user.recent.resource.js
> +        window.open(this.menu.record.link);
The value of `this.menu.record.link` is `undefined`.

2019-01-03 20:05 UTC, Alroniks commented
Sorry, my bad. Added array element into the wrong place. Fixed. @Ruslan-Aleev @JoshuaLuckers @Mark-H

2019-01-03 20:12 UTC, JoshuaLuckers approved these changes

2019-01-08 13:27 UTC, alroniks commented
@Mark-H Please, have a look at the fixed code.

2019-01-08 13:35 UTC, Mark-H approved these changes
👍

2019-01-08 13:46 UTC, merged