Change system setings user_settings_desc #6282
modxcms/revolution pull request #14249
Opened 2019-01-09 07:12 UTC by Ibochkarev

### Why is it needed?
Change the description of the system settings `user_settings_desc`  for clarity

### Related issue(s)/PR(s)
#6282

2019-01-09 11:06 UTC, Mark-H submitted a review, later dismissed

2019-01-09 14:49 UTC, alroniks submitted a review, later dismissed

2019-01-09 17:18 UTC, Jako requested changes
I suggest `available for this user`, but I am not a native speaker.

And please change `available System --> System Settings menu` to something that does not depend on a click path i.e. to `You can override any of the modx system settings on a per-user base`

2019-01-09 19:00 UTC, Ibochkarev commented
@Jako i am fix.

2019-01-09 19:03 UTC, JoshuaLuckers requested changes

2019-01-09 19:03 UTC, JoshuaLuckers commented on core/lexicon/en/user.inc.php
> +$_lang['user_settings_desc'] = 'You can override any of the modx system settings on a per-user base, or you can create new settings available only to this user';
```suggestion
$_lang['user_settings_desc'] = 'You can override any of the MODX system settings on a per-user base, or you can create new settings available only to this user';
```

2019-01-09 20:20 UTC, JoshuaLuckers approved these changes

2019-01-09 22:18 UTC, Jako approved these changes

2019-01-24 16:10 UTC, opengeek approved these changes

2019-01-25 08:07 UTC, merged