Fix Vertical Tabs explode if TV names longer than 169px #14240
modxcms/revolution pull request #14247
Opened 2019-01-09 06:31 UTC by Ibochkarev

### Why is it needed?
Change width Vertical Tabs explode if TV names longer from 169px to auto

### Related issue(s)/PR(s)
#14232

2019-01-09 07:38 UTC, JoshuaLuckers requested changes
Thanks for taking time to submit this PR and make MODX better. 

~~Since this is your first time contributing you have to sign the CLA first. For more info:~~
~~- [Becoming a Contributor](https://docs.modx.com/community/contribute/becoming-a-contributor)~~
~~- [Fill out and send in a Contributor License Agreement (CLA)](http://develop.modx.com/contribute/cla/)~~

2019-01-09 07:38 UTC, JoshuaLuckers commented on _build/templates/default/sass/_tabs.scss
> +  /*margin-left: -1px*/
Now that this line has been edited it makes more sense to be completely removed.

2019-01-09 07:38 UTC, JoshuaLuckers commented on _build/templates/default/sass/_tabs.scss
> +    width: auto !important; /* aligns the vertical tabs with the TVs tab left edge, will not work that nicely with non-english langs */
The comment for this line is no longer valid after this change.

2019-01-09 07:38 UTC, JoshuaLuckers commented on _build/templates/default/sass/_tabs.scss
> +            width: auto; /* make the active li 1px more wide to cover the containers right border, this makes the right border on inactive tabs necessary as the whole tab-strip wrap gets wider */
Is the comment still valid?

2019-01-09 11:10 UTC, Mark-H commented
One thing to check before this gets merged is how the vertical tabs behave in modal windows. I seem to recall some of the `#hacky` was to make them behave nicely in such contexts... that said, I can't think of any places in the core that uses vtabs in modals, so that may just be extras (like ContentBlocks).

2019-01-24 10:27 UTC, Ruslan-Aleev commented
<del>I can't reproduce this bug.</del>
My mistake, you had to set a name larger than 169px in ONE WORD.

2019-01-31 13:45 UTC, Ibochkarev commented
Found a better solution to correct this error in the PR #14317

2019-01-31 13:45 UTC, closed without merging