Bugfix for thumbnails not rendering for s3 image URL's with spaces.
modxcms/revolution pull request #14301
Opened 2019-01-22 23:23 UTC by gregcrown

### What does it do?
Updates file source URL's with encoded spaces.

### Why is it needed?
Media sources with spaces in URL's (example: s3) were unable to generate thumbnails.

### Related issue(s)/PR(s)
No related issues.

2019-01-23 06:14 UTC, Jako reviewed
urlencode or rawurlencode is not an option?

2019-01-23 10:59 UTC, Jako commented
Will S3 media sources be deprecated in 3.x? The API has changed for a lot of new buckets and the current code does not work anymore.

2019-01-23 11:01 UTC, JoshuaLuckers commented
> Will S3 media sources be deprecated in 3.x? The API has changed for a lot of new buckets and the current code does not work anymore.

Doesn't Filesystem cover this in 3.x?

2019-01-23 11:04 UTC, Jako commented
Flysystem supports this, but it has to be configured.

There is an extra available for new S3 buckets.

2019-01-23 15:16 UTC, gregcrown commented
> urlencode or rawurlencode is not an option?

I explored this option however the variables that are affected already contained full URL's. To use urlencode or rawurlencode would require breaking up the complete URL's into segments and then rebuilding the URL. Explicitly replacing the spaces removes the extra steps.

Please suggest a more elegant approach if you have one though. 👍

2019-01-25 10:29 UTC, Jako submitted a review, later dismissed

2019-01-25 14:14 UTC, gregcrown commented
I needed to amend my commit to include a check for URL match in:

core/model/phpthumb/phpthumb.class.php

I should have done this to begin with. This will allow filesystem images to be handled without the URL fix.

2019-01-25 15:28 UTC, JoshuaLuckers requested changes

2019-01-25 15:28 UTC, JoshuaLuckers commented on core/model/phpthumb/phpthumb.class.php
> +		if (preg_match('#^[a-z0-9]+://#i', $sourceFilename)) {
Please add a comment with an explanation to indicate what this does and why it's needed.

2019-01-25 15:52 UTC, gregcrown commented on core/model/phpthumb/phpthumb.class.php
> +		if (preg_match('#^[a-z0-9]+://#i', $sourceFilename)) {
This is the same URL checking logic that exists on lines 581 and 906. Should we add comments to all of these instances as well?

2019-01-25 16:00 UTC, JoshuaLuckers commented on core/model/phpthumb/phpthumb.class.php
> +		if (preg_match('#^[a-z0-9]+://#i', $sourceFilename)) {
Only here is fine with me.

2019-01-26 17:01 UTC, Jako requested changes

2019-01-26 17:01 UTC, Jako commented on core/model/phpthumb/phpthumb.class.php
> +		if (preg_match('#^[a-z0-9]+://#i', $sourceFilename)) {
That class is external code and can't be changed.

2019-02-05 13:04 UTC, Ibochkarev commented
@gregcrown Please continue to work on this PR. Thanks

2019-02-05 23:25 UTC, gregcrown commented
This PR has been updated by reseting the original phpThumb and making the required changes to the MODx managed modPhpThumb class. I've also added a comment above the URL detection for clarity.

2019-02-06 17:04 UTC, Jako approved these changes

2019-02-09 11:33 UTC, JoshuaLuckers approved these changes

2019-03-05 23:51 UTC, Mark-H approved these changes

2019-03-06 01:02 UTC, Mark-H commented
Hey @gregcrown, I was about to merge this but it looks like you haven't signed the MODX CLA yet. Could you please fill out the form at https://develop.modx.com/contribute/cla/ and let me know when you've done so? 

Thanks!

2019-03-06 01:22 UTC, gregcrown commented
Accepted! Thanks for the heads up!

On Tue, Mar 5, 2019, 7:02 PM Mark Hamstra <notifications@github.com> wrote:

> Hey @gregcrown <https://github.com/gregcrown>, I was about to merge this
> but it looks like you haven't signed the MODX CLA yet. Could you please
> fill out the form at https://develop.modx.com/contribute/cla/ and let me
> know when you've done so?
>
> Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/modxcms/revolution/pull/14301#issuecomment-469923011>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AUDmOkXLO7v-KTaKbJe-f85eYkveuj_qks5vTxO6gaJpZM4aNuQJ>
> .
>

2019-03-06 18:03 UTC, merged