Fixed long dropdown submenu #11939
modxcms/revolution pull request #14300
Opened 2019-01-20 11:34 UTC by GulomovCreative

### What does it do?
1. Add new system setting `topmenu_submenu_max_items`
2. Check this setting and moves remainings items to new item with label "More"
3. Add right arrow/triangle for menu items that have children

**Process gif**

![ux](https://user-images.githubusercontent.com/20814058/51438670-bddb5c80-1ce1-11e9-8f15-f2ac1bc3011f.gif)

![screenshot-revolution-2019 01 20-18-23-00](https://user-images.githubusercontent.com/20814058/51438637-4f969a00-1ce1-11e9-969e-5a45c0e96196.png)

### Why is it needed?
Description from #11939

> When there's a long Extras dropdown menu, and not enough screen space, the bottom items get cut off. It's not possible to scroll down or access them.

### Related issue
Closes #11939

2019-01-20 11:41 UTC, JoshuaLuckers commented
PR’s with new functionality should target the 3.x branch

2019-01-20 11:49 UTC, Ruslan-Aleev commented
@JoshuaLuckers This problem is not relevant for 3.x. I think better in 2.x

2019-01-21 19:29 UTC, JoshuaLuckers requested changes

2019-01-21 19:29 UTC, JoshuaLuckers commented on manager/controllers/default/header.php
> +    public function processSubMenus(&$output, array $menus = array(), int $maxItems)
```suggestion
    public function processSubMenus(&$output, array $menus = array(), $maxItems = false)
```

MODX should be compatible with PHP 5.6 and higher, scalar type hints are available in PHP 7+ only. 
A default value should be used to maintain backwards compatibility.

2019-01-21 19:29 UTC, JoshuaLuckers commented on manager/controllers/default/header.php
> +		if(!empty($moreMenu)) {
```suggestion
		if (!empty($moreMenu)) {
```

2019-01-21 19:29 UTC, JoshuaLuckers commented on manager/controllers/default/header.php
>                  $this->processSubMenus($smTpl, $menu['children']);
The maximum amount of items should also apply to child submenu's.

2019-01-21 19:29 UTC, JoshuaLuckers commented on manager/controllers/default/header.php
> +			$this->processSubMenus($output, $moreMenu);
The maximum amount of items should also apply here.

2019-01-21 19:31 UTC, JoshuaLuckers commented on manager/controllers/default/header.php
> +		if($maxItems && count($menus) > $maxItems) {
```suggestion
		if ($maxItems && count($menus) > $maxItems) {
```

2019-01-21 19:33 UTC, Jako commented
It should be relevant for 3.x, too. Scrolling in menus should be made avoidable, if possible.

2019-01-21 20:04 UTC, Ruslan-Aleev commented
@Jako Yes, literally a couple of hours found the same problem in MODX3, although I had not noticed before. Therefore, it is not clear what to do with PR.

2019-01-21 20:13 UTC, GulomovCreative commented on manager/controllers/default/header.php
> +    public function processSubMenus(&$output, array $menus = array(), int $maxItems)
You're right

2019-01-21 20:22 UTC, GulomovCreative commented on manager/controllers/default/header.php
>                  $this->processSubMenus($smTpl, $menu['children']);
Do you think that the amount of items in the third level of the menu will be so much that you need to hide it?

2019-01-21 20:39 UTC, JoshuaLuckers commented on manager/controllers/default/header.php
>                  $this->processSubMenus($smTpl, $menu['children']);
It's possible, if it requires too much change it would be good to do that in 3.x instead.

2019-01-24 20:42 UTC, Mark-H commented
So, I see 2 scenarios for this (really cool!) improvement.

We either approve it for 2.x, in its current form, and then when 2.x gets merged into 3.x that'll likely cause weird conflicts that need to be manually resolved.

Or, this PR is updated to target 3.x instead. That probably means a bit more work to get things looking just as nice, but it'll avoid that responsibility falling on the integrators doing a merge (which is typically complicated enough, and those integrators may not always know all the intricacies of individual PRs when doing that). 

So (for completely selfish reasons :D), my vote would go to making it ready for 3.x instead. That then also adds another great reason to hurry with finishing that up for a proper release, and we could add a sensible default (maybe 10?) to the setting that controls it so it kicks in automatically :)

2019-01-25 04:58 UTC, GulomovCreative commented
> So, I see 2 scenarios for this (really cool!) improvement.
> 
> We either approve it for 2.x, in its current form, and then when 2.x gets merged into 3.x that'll likely cause weird conflicts that need to be manually resolved.
> 
> Or, this PR is updated to target 3.x instead. That probably means a bit more work to get things looking just as nice, but it'll avoid that responsibility falling on the integrators doing a merge (which is typically complicated enough, and those integrators may not always know all the intricacies of individual PRs when doing that).
> 
> So (for completely selfish reasons :D), my vote would go to making it ready for 3.x instead. That then also adds another great reason to hurry with finishing that up for a proper release, and we could add a sensible default (maybe 10?) to the setting that controls it so it kicks in automatically :)

@Mark-H I got it. I will make it ready for 3.x. Thx!

2019-05-05 10:31 UTC, JoshuaLuckers commented
@GulomovCreative is this still on your radar? If you need any help please let us know.

2019-09-01 14:29 UTC, Mark-H commented
Closing as the consensus is to recreate this for 3.

2021-09-23 14:00 UTC, Ruslan-Aleev commented
Guys, maybe it's worth merge this fix into the 2.x after all? On some projects it is not possible to work with the menu in principle.

2021-09-24 11:10 UTC, closed without merging