Don't log deprecated methods during package install
modxcms/revolution pull request #14303
Opened 2019-01-23 06:48 UTC by Jako

### What does it do?
Define a constant, that does allow to bypass the $this->log call in the install/uninstall processors.

### Why is it needed?
Don't log deprecated methods during package install, since the log entry is visible in red in the installation logs and the deprecated message is often triggered by a previous installed package.

### Related issue(s)/PR(s)
#14302

2019-01-24 20:32 UTC, Mark-H commented
I'm not entirely convinced this is necessary.. is it really a problem that the package installation shows which packages need to be updated from modAction?

2019-01-24 20:34 UTC, opengeek commented
I concur with Mark. This seems helpful to know.

2019-01-24 21:51 UTC, Jako commented
As BobRay stated in his issue, the warnings are often caused by other previous installed packages.

2019-02-05 14:27 UTC, Mark-H commented
I understand it shows the message for unrelated packages, but I still don't personally consider that a real problem. When updating packages, I find the messages useful to see what other packages will also need attention. As it will likely take a little time for all packages to catch up, it's a useful periodic reminder.

I'm probably a 3 on the [SSOGAF](http://blog.capwatkins.com/the-sliding-scale-of-giving-a-fuck) though, so if this is truly bothering others more than not having it bothers me, then I'm okay with giving it a thumbs up.

2019-02-05 21:12 UTC, Jako commented
The deprecated issues should be logged only once a day. At the moment I switch them off everywhere to be not pissed off, because there are too much extras that use i.e. modAction.

2019-02-11 13:08 UTC, Jako commented
The last change restrict the logging of modAction deprecation to the current package during install/uninstall.

2019-02-13 15:27 UTC, opengeek requested changes
I do not feel a define is a good choice here. Perhaps a static variable would be better?

2019-02-14 11:44 UTC, Jako commented
@opengeek Now it uses a modX/xPDO class option.

2019-03-05 23:50 UTC, Mark-H commented
This seems pretty nasty to me.. does it have to be an array? I think the code would be a lot cleaner if it were just a simple string.

2019-03-06 08:00 UTC, Jako commented
I introduced the array, because a package could install another package inside. I can't remember where, but I have seen this in a theme package.

2019-03-06 10:00 UTC, Alroniks commented
Tickets extra installs two packages, for example: since this line https://github.com/bezumkin/Tickets/blob/master/_build/resolvers/resolve.setup.php#L135

2020-02-05 16:44 UTC, opengeek approved these changes

2020-02-05 17:04 UTC, merged