Change the default request_method_strict and friendly_alias_restrict_chars
modxcms/revolution pull request #14327
Opened 2019-02-03 19:29 UTC by Ibochkarev

### What does it do?
- FURL Alias Character Restriction Method (`friendly_alias_restrict_chars`) - `pattern` changed to `alphanumeric`. 
- Strict Request Method (`request_method_strict`) - `no` changed to `yes`. 

### Why is it needed?

1. FURL Alias Character Restriction Method (`friendly_alias_restrict_chars`). Because It happens that in the current variant can stay incorrect characters in url, but with `alphanumeric` there is no such problem and this option will is suitable for most users.
2. Strict Request Method (`request_method_strict`). Because in the current version, if FURL is enabled, then the url opens with both index.php and sef-url, which is bad for search engines.

### Related issue(s)/PR(s)
#14273

2019-02-04 09:59 UTC, JoshuaLuckers requested changes
A few Unit Tests are failing because of these changes.

2019-02-04 13:35 UTC, Ibochkarev commented
> A few Unit Tests are failing because of these changes.
@JoshuaLuckers  Please help me with troubleshooting.

2019-02-04 19:42 UTC, JoshuaLuckers commented
This test fails: https://github.com/modxcms/revolution/blob/13c6b22b8abfeb8e3436eaaff6fa5e67041068f2/_build/test/Tests/Model/Request/modRequestTest.php#L102-L122

It's testing this method:
https://github.com/modxcms/revolution/blob/1e4a45c1b0e412c46fe4b8880a6e939ed222f23c/core/model/modx/modrequest.class.php#L144-L163

Caused by the new default setting for `request_method_strict`.

2019-02-05 10:23 UTC, Jako commented
Changing `friendly_alias_restrict_chars` is ok, but activating `request_method_strict` could cause infinite redirect loops in some situations (i.e. in CustomRequest). That part has to be checked.

2019-12-09 16:24 UTC, Mark-H commented
Past the feature/breaking change cut-off for alpha1, so pushing further.

2020-01-26 12:15 UTC, JoshuaLuckers commented
@Mark-H @Jako do we approve changing `friendly_alias_restrict_chars` from `pattern` to `alphanumeric`?

2020-01-26 12:35 UTC, Jako commented
I favor a better iconv based solution than the current. The current solution transliterates from unicode to unicode if it works the same as 2.x, it should transliterate from unicode to ascii.

2020-02-16 13:13 UTC, JoshuaLuckers commented
> I favor a better iconv based solution than the current. The current solution transliterates from unicode to unicode if it works the same as 2.x, it should transliterate from unicode to ascii.

How can we accomplish this?

2020-02-16 13:18 UTC, Jako commented
Maybe #13932 covers this. But I did not check a lot of transliteratons.

2020-06-26 00:03 UTC, closed without merging