Combine system settings the categories "Friendly URL" and "Gateway"
modxcms/revolution pull request #14332
Opened 2019-02-05 21:48 UTC by Ibochkarev

### What does it do?
Combine system settings the categories "Friendly URL" and "Gateway" into one general group Friendly URL & Gateway

### Why is it needed?
In the category "Gateway" of 4 settings 3 are associated with FURL.
![2019-02-06_03-42-26](https://user-images.githubusercontent.com/2138260/52306389-01acb200-29c2-11e9-83f3-993e331f8063.png)

### Related issue(s)/PR(s)
#14227

2019-02-06 07:58 UTC, alroniks requested changes

2019-02-06 07:58 UTC, Alroniks commented on core/lexicon/en/setting.inc.php
> +$_lang['settings_furls_gateway'] = 'Friendly URL & Gateway';
```suggestion
$_lang['settings_furls_gateway'] = 'Friendly URLs & Gateway';
```
Plural variant more correct here.

2019-02-06 10:49 UTC, Mark-H commented
Please correct me if I'm wrong, but I don't think upgrading an existing site will automatically adjust the categories for existing settings. That's okay (I don't think it's needed to write an upgrade script for that), but as the furls and gateway lexicons are removed, I think that may mean those categories will no longer be translated after applying this change.

To deal with that, I'd suggest not creating a new area (`furls_gateway`), but instead adjust the lexicon for `furls` and change the settings that are in `gateway` to `furls`. Then if you also leave in the `gateway` lexicon entry, that should make a better upgrade experience. 

Does that make sense?

2019-02-06 15:39 UTC, opengeek commented
I don't understand why this is needed?

2019-02-06 15:40 UTC, opengeek commented
The gateway settings are not all friendly URL related.

2019-02-06 15:45 UTC, opengeek commented
If anything, why not change it to "Routing" if we are going to merge them all together?

2019-02-06 16:53 UTC, Ruslan-Aleev commented
The settings in the "Gateway" section on 3/4 refer to the "Friendly URL" settings, i.e. they are related.
And for seo it’s not correct, if urls like "/contacts.html" and "/index.php?id=5" are available on the site at the same time.
About the name "Routing" - it is not clear for a simple user.
In the name "Friendly URL & Gateway" there is a "Friendly URL" in the title, which is a little easier to understand :)

2019-02-06 16:55 UTC, opengeek commented
In that case, I'm going to say no to this one. I think they need to remain separate since the gateway is a different issue than Friendly URLs. Even though some of the gateway settings relate to Friendly URLs, they are still a separate group of settings that someone not using Friendly URLs might be looking for. I don't see this as a necessary change.

2019-02-06 17:02 UTC, Ruslan-Aleev commented
Perhaps you are right, in this question the statistics of using or not using FURLs in MODX would help.

2019-02-08 08:54 UTC, JoshuaLuckers commented
Instead of doing work for changes that might or might not be approved it's better to create issues for changes like this where it can be discussed first and be implemented when reached a consensus.

2019-02-08 09:00 UTC, Ibochkarev commented
@JoshuaLuckers H. This improvement has been made by Issue #14227 . In it only Ivan answered. Therefore, I decided to make this PR.

**If he is not accepted, life will not end there =)**

2019-02-09 05:16 UTC, closed without merging