Update phpThumb 1.7.15-201902101903
modxcms/revolution pull request #14366
Opened 2019-02-11 20:00 UTC by Ibochkarev

### What does it do?
Update phpThumb 1.7.15-201902101903
Add support image format WebP

### Why is it needed?
To solve the issue in #14365 #14355 #14356 

### Related issue(s)/PR(s)
#14365 #14355 #14356

2019-02-11 21:16 UTC, opengeek requested changes
I believe we exclude the phpThumb.php file—can anyone else confirm this? Also, do not change the file permissions on files when submitting PRs like this. I realize it is most likely a result of the source repository, but in this case, you can simply change the permissions before submitting the PR. All the PHP files modified in this PR are attempting to change permissions from 100644 -> 10755.

2019-02-11 21:38 UTC, Ibochkarev commented
@opengeek I fixed the permissions on the files on 644 and deleted the phpThumb.php file

2019-02-11 22:31 UTC, Jako approved these changes

2019-02-12 07:02 UTC, alroniks approved these changes

2019-02-12 17:04 UTC, opengeek approved these changes

2019-02-12 18:21 UTC, merged