Feature 14114
modxcms/revolution pull request #14374
Opened 2019-02-13 13:02 UTC by mvoevodskiy

### What does it do?
Added list of protected directories, that can not be renamed or removed from manager:

- MODX_ASSETS_PATH
- MODX_BASE_PATH
- MODX_CONNECTORS_PATH
- MODX_CORE_PATH
- MODX_MANAGER_PATH
- MODX_PROCESSORS_PATH
- XPDO_CORE_PATH

Renaming or removing this directories will cause error with message "Access Denied".

Also, this PR contain 2 small fixes in processor browser/directory/rename

### Why is it needed?
Description from issue:
`Right click on any of these folders, rename or delete them and you are in trouble.
Could also reduce impact of malicious actions by people with low morals or a short temper.`

### Related issue(s)/PR(s)
#14114

2019-02-13 13:07 UTC, JoshuaLuckers commented
Thanks for taking time to create this PR and help make MODX better. It seems that you are a first-time contributor. To prevent us from merging this PR it's important that you sign the [Contributor License Agreement (CLA)](https://docs.modx.com/community/contribute/becoming-a-contributor).

If you have signed the CLA already please let us know. If you have any questions feel free to post them.

2019-02-13 13:10 UTC, mvoevodskiy commented
@JoshuaLuckers thanks for link to CLA. I have already signed today.

2019-02-13 15:34 UTC, alroniks requested changes
I would love to see a more descriptive error message with an explanation of why user can to do such action.

2019-02-15 07:56 UTC, mvoevodskiy commented
> I would love to see a more descriptive error message with an explanation of why user can to do such action.

Added.

2019-02-15 10:13 UTC, JoshuaLuckers reviewed
Please only include the English lexicon entries. Lexicons in other languages are managed via CrowdIn and they might get overwritten when translations are imported.

2019-02-15 10:16 UTC, alroniks requested changes

2019-02-15 10:16 UTC, Alroniks commented on core/lexicon/ru/file.inc.php
> +$_lang['file_folder_err_rename_protected'] = 'Переименование защищенного системного каталога не допускается.';
All translations should be done via Crowdin, so, please, remove Russian strings from the pull request.

2019-02-15 19:28 UTC, Jako commented on core/model/modx/processors/browser/directory/rename.class.php
>   * Renames a file
one 'file' is left

2019-02-15 19:37 UTC, mvoevodskiy commented on core/model/modx/processors/browser/directory/rename.class.php
>   * Renames a file
Fixed

2019-02-16 09:31 UTC, JoshuaLuckers approved these changes

2019-02-16 09:46 UTC, Jako approved these changes

2019-02-26 15:57 UTC, Ruslan-Aleev approved these changes
Everything works as described

2019-02-26 20:27 UTC, Alroniks commented on core/model/modx/processors/browser/browser.class.php
> +    public function getProtectedPathDirectories() {
Does it make sense to make it static as it returns constants? Not a request, but just a question for discussion.

2019-02-26 20:28 UTC, alroniks approved these changes
The code seems OK for me and works as expected.

2019-02-28 21:23 UTC, Mark-H approved these changes

2019-03-01 08:45 UTC, merged