Prevent Google Chrome translations from the admin panel
modxcms/revolution pull request #14414
Opened 2019-02-20 12:07 UTC by Ibochkarev

### What does it do?
Prevent Google Chrome translations from the admin panel 
+ Refactoring

### Why is it needed?
To specify a meta Tag to prevent Google translation to translate text in admin panel

### Related issue(s)/PR(s)
#13201

2019-02-20 19:42 UTC, JoshuaLuckers requested changes
Please only commit the change with the newly add meta tag. I do see some new formatting and other code changes that should not be part of this PR.

2019-02-21 10:15 UTC, Ibochkarev commented
@JoshuaLuckers fixed

2019-02-21 12:31 UTC, JoshuaLuckers approved these changes

2019-02-21 12:37 UTC, Mark-H approved these changes

2019-02-25 10:39 UTC, merged