Alter modUserProfile gender field to tinyint from int
modxcms/revolution pull request #14412
Opened 2019-02-20 08:27 UTC by Alroniks

### What does it do?
Changes type of gender field to `tinyint` instead of `int` as this field shouldn't contain a lot of information.

### Why is it needed?
- to take less place and memory for storing this data
- to keep consistency between different database drivers (sqlsrv uses `tinyint` as well).

### Related issue(s)/PR(s)
#11902

2019-02-20 08:29 UTC, Alroniks commented
I am wondering, it is strongly required migration script for altering this field during the upgrade?

2019-02-20 16:34 UTC, opengeek requested changes
Yes, you will need to modify the field in the upgrade script. Does this need a similar change for sqlsrv?

2019-02-20 20:05 UTC, JoshuaLuckers commented
What if we want to support [all possible genders](http://genderfluidsupport.tumblr.com/gender/) like Facebook en Tumblr do?

2019-02-20 20:06 UTC, Jako commented
0-9 should be enough for genders

2019-02-25 10:48 UTC, Alroniks commented
@opengeek I've added migration scripts for both: mysql and sqlsrv, because for sqlsrv it was missed too. Please, check.

2019-03-05 23:06 UTC, Mark-H approved these changes

2019-03-06 20:18 UTC, opengeek approved these changes

2019-03-06 20:30 UTC, merged