Improved xtypes and values for system settings
modxcms/revolution pull request #14447
Opened 2019-03-02 15:46 UTC by JoshuaLuckers

### What does it do?
Checked the system settings and changed the value to the right type and also checked if they could use another xtype like `numberfield`.

### Why is it needed?
Improve the code base.

### Related issue(s)/PR(s)
Closes issue #12284

2019-03-04 06:42 UTC, alroniks requested changes
Upgrade script required I guess.

2019-04-02 14:11 UTC, JoshuaLuckers commented
> Upgrade script required I guess.

I agree 👍.

2019-04-02 14:15 UTC, Alroniks commented
I am wondering what if somebody added value that does not fit new xtype, maybe we should check the type and skip them, showing the warning? I think it almost impossible but still.

2019-04-02 14:19 UTC, JoshuaLuckers commented
> I am wondering what if somebody added value that does not fit new xtype, maybe we should check the type and skip them, showing the warning? I think it almost impossible but still.

Good point. There is already a check if the system setting is using the `old_xtype`, I will try to add the check you propose another time. 

If someone else wants to add such a check: feel free to help!

2019-04-02 15:06 UTC, JoshuaLuckers commented
@Alroniks I gave your suggestion some thought and maybe we don't need such a check. The xtype is used when you edit the system setting via the grid. Only if you edit the value it will check if it's a valid value for the defined xtype. 

A warning if the value is invalid for the new xtype would be nice but could be done in another PR. What do you think?

2019-04-25 10:06 UTC, Mark-H requested changes
Spotted one incorrect change, other than that, nice work.

2019-04-25 10:06 UTC, Mark-H commented on _build/data/transport.core.system_settings.php
> +  'xtype' => 'numberfield',
This should be text, can also be `full`, `https`, `abs`, etc.

2019-04-25 10:06 UTC, Mark-H commented on setup/includes/upgrades/common/3.0.0-update-xtypes-system-settings.php
> +        'new_xtype' => 'numberfield',
This one should be removed per other comment.

2019-09-01 13:22 UTC, Mark-H approved these changes

2019-09-09 22:58 UTC, Mark-H approved these changes

2019-09-09 23:02 UTC, merged