3.x bug login lexicon good night
modxcms/revolution pull request #14471
Opened 2019-03-08 05:02 UTC by digitalpenguin

### What does it do?
Changes the English lexicon file for the manager login screen. Good night has been replaced with Good evening.

### Why is it needed?
 Good night is used as a farewell rather than a greeting in contemporary English.

### Related issue(s)/PR(s)
#14470

2019-03-08 05:07 UTC, digitalpenguin commented
Hmm I switched branch for this new PR but it seems to be including the commit from my previous PR. 
What's the best course of action to prevent that?

2019-03-09 12:17 UTC, JoshuaLuckers requested changes

2019-03-09 12:17 UTC, JoshuaLuckers commented on _build/templates/default/sass/_dashboard.scss
> +      max-width:100%;
I don't think this should be part of this PR.

2019-03-09 12:19 UTC, JoshuaLuckers commented
> Hmm I switched branch for this new PR but it seems to be including the commit from my previous PR.
> What's the best course of action to prevent that?
> 
> Edit:
> A bit of research seems to suggest I should've used `git stash` before switching to the new branch. Is that correct?

Always create a new branch (branch from 3.x in this case) for PR's.

2019-03-09 17:01 UTC, JoshuaLuckers commented
If you pull in the latest changes from 3.x you probably don't have to change anything 😄

2019-03-09 18:43 UTC, Jako commented
The following should work:

1. Fetch all changes from all remotes
2. Stash your changes
3. Checkout a new branch on base of 3.x
4. Rebase that branch with upstream/3.x
5. Pop your changes from the stash

```
git fetch --all
git stash
git checkout -b myFeature 3.x 
git rebase upstream/3.x
git stash pop
```

(This depends on that you have set up an upstream remote to modxcms/revolution)

After this, you could commit your stashed changes and create a PR.

2019-03-10 10:48 UTC, digitalpenguin commented
Thanks all, I'm going to re-do this one.

2019-03-10 10:48 UTC, closed without merging