Minor bug fixes styles
modxcms/revolution pull request #14492
Opened 2019-03-16 21:51 UTC by Ibochkarev

### What does it do?
Changed / added styles:
- Fixed `font-weight` property from 700 to 500 in menu and headers
- Improves consistency of green color when you hover over the menu items and in the progress bar
- Removed two color variables that are no longer used and are left over from 2.x
- Fixed bug with adaptability of images in panels on the start page
- Fixed u padding `.x-panel-body `
- Added styles when hovering over the buttons on the installer page
- Fixed the position of the icons in the panels `.dashboard-buttons` and the icon in the pop-up window
- Stylized scrollbar
- Fixed the background color of the Help page in the panels

### Why is it needed?
Fixes minor bugs and improves the appearance of the admin panel

### Related issue(s)/PR(s)
NA

2019-03-17 08:49 UTC, JoshuaLuckers requested changes
There are too many changes in one single commit. This doesn't help understand why a certain piece of code was changed when someone looks at the changes in the future (or without reading this PR).

For this PR it makes more sense to have multiple commits, maybe 1 commit per change listed in the PR.

2019-03-17 09:04 UTC, Alroniks commented
Agree with Joshua

2019-03-19 20:14 UTC, Ibochkarev commented
@Alroniks @JoshuaLuckers I broke into different parts

2019-04-25 10:29 UTC, Mark-H approved these changes

2019-04-25 17:16 UTC, JoshuaLuckers approved these changes

2019-04-28 14:15 UTC, merged