Allow in-line editing in FC sets grid
modxcms/revolution pull request #14529
Opened 2019-04-03 03:12 UTC by DettRoxx

### What does it do?
Adds ability to edit as inline fields in grid in FC sets as in FC Profiles gird

### Why is it needed?
Increase productivity

### Related issue(s)/PR(s)
#5225

2019-04-03 07:42 UTC, Alroniks commented on core/model/modx/processors/security/forms/set/updatefromgrid.class.php
> +return 'modFormCustomizationSetUpdateFromGridProcessor';
Better to write `return modFormCustomizationSetUpdateFromGridProcessor::class` here.

2019-04-03 07:43 UTC, Alroniks commented
This RP will be on hold before Jason finish his refactoring.

2019-04-25 10:51 UTC, Mark-H approved these changes

2019-08-17 13:04 UTC, JoshuaLuckers commented
@DettRoxx thanks for the patience, is it possible for you to refactor this PR?

2019-09-01 12:47 UTC, Mark-H commented
The processor needs to be redone in the new way. If someone wants to pitch in here to help that would be awesome.

2019-09-09 23:14 UTC, Mark-H requested changes
Processor needs to be redone after the processor refactor.

2019-10-08 09:34 UTC, theboxer commented
The processor already exists in the 3.x codebase, to make this work only the changed JS file is needed. (Tested and works fine)

2019-10-09 17:21 UTC, opengeek commented
This was incorporated via #14781

2019-10-09 17:21 UTC, closed without merging