Feature welcome widget
modxcms/revolution pull request #14569
Opened 2019-04-25 08:04 UTC by sdrenth

### What does it do?
Added a new welcome widget for the dashboard page showing a welcome message and current time. The background image can be changed by the newly added system setting `widget_welcome_background`.

### Why is it needed?
Displays a neat welcome message when visiting the dashboard page.

![Screenshot 2019-04-25 at 10 03 17](https://user-images.githubusercontent.com/7802465/56719608-60700500-6741-11e9-858f-32055736b343.png)

2019-04-25 08:34 UTC, Electrica commented
You are seriously? )))

2019-04-25 08:50 UTC, Mark-H commented
Two things:

- Where is that image from and under what license is it available?
- Style changes should be made in the sass files (in `_build/templates/default/`), not the output css file.

2019-04-25 09:03 UTC, gpsietzema commented
The image is from Unsplash.

2019-04-25 11:30 UTC, sdrenth commented
@Mark-H I moved to css changes to the sass files

2019-04-25 12:06 UTC, Ibochkarev requested changes

2019-04-25 12:06 UTC, Ibochkarev commented on _build/templates/default/sass/_dashboard.scss
> +      color: #fff;
Please change to the variable `$white`

2019-04-25 12:06 UTC, Ibochkarev commented on _build/templates/default/sass/_dashboard.scss
> +        color: #fff;
Please change to the variable `$white`

2019-04-25 12:08 UTC, Ibochkarev requested changes

2019-04-25 12:08 UTC, Ibochkarev commented on manager/templates/default/css/index-min.css
> -/*! normalize-scss | MIT/GPLv2 License | bit.ly/normalize-scss */html{line-height:1.15;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,footer,header,nav,section{di
Please don't commit the compiled CSS. The integrator who merges the PR will compile the final CSS.

2019-04-25 12:08 UTC, Ibochkarev commented on manager/templates/default/css/login.css
>    padding: 0 1.5625rem; }
Same

2019-04-25 12:08 UTC, Ibochkarev commented on manager/templates/default/css/index.css
Same

2019-04-25 13:03 UTC, Ibochkarev submitted a review, later dismissed

2019-04-25 18:14 UTC, JoshuaLuckers commented
I don't think that a non-functional dashboard widget like this should be in the core. 

1. It's wasting to much useful space
2. It's showing the time on the server which might confuse users if it deviates from the users time. This can be useful if properly presented to the user. 
3. Do we really want to load more assets like this image in the manager?

2019-04-26 06:13 UTC, gpsietzema commented
1. The point is to make this dashboard prettier. That's an important function. Make people happier to use the system.
2. Sure, any ideas?
3. Yes. It's needed for this.

2019-04-26 09:40 UTC, JoshuaLuckers commented
> * The point is to make this dashboard prettier. That's an important function. Make people happier to use the system.

Fair enough! The functions provided by the widget in its current state, in my opinion, doesn't justify the amount of space it uses.  I suggest to provide additional functionality personalised for the current user. 
I'll propose some ideas later. 

> * Sure, any ideas?
Not right now.

> * Yes. It's needed for this.
Haha 🤣. It would be nice to mention the source/link of the image in the code as comment for future reference.

2019-04-26 09:59 UTC, Alroniks commented
It would be nice to collect those nice widgets in the separated extra. It will allow us to have them updated separately and more frequently and do not waste the time of core integrations for such small improvements. 
It nice and I like it, of course,  but from a common perspective and long term view these things will have to be maintained later in case of changes and this will take time away.

2019-04-26 10:02 UTC, Alroniks commented
@gpsietzema @sdrenth I can help with creating such extra and I can maintain it if you agree.
Also, as it was described in other issues, a bunch of extras can be suggested user for installation on new setup interface and this extra would be the best candidate for such list.

2019-04-26 10:05 UTC, gpsietzema commented
Sounds like a good idea @Alroniks - I really like it.

2019-04-26 11:01 UTC, sdrenth commented
I've added the source URL of the default image in: transport.core.system_settings.php

2019-05-24 07:02 UTC, sdrenth commented
@Alroniks Any progress on this one? 

Also any thoughts about which widgets should be extracted from the core into an Extra and which should stay in the core?

I feel like most widgets should stay in the core and this one should be added into an extra. But for the extra to also add some more value I feel like there should be some more enhanced dashboard widgets added into that extra. But that could also be something which we could expand later on.

2019-05-24 07:54 UTC, Alroniks commented
I would like to leave only top buttons, security check and feeds (I don't like them but they probably needed).
Others should be and can be moved to the extra. 
I have not started anything yet, but it should be done at the same time with adding additional screen for an installer with suggested add-ons. To have it preinstalled and keep a good user experience.

2019-06-07 06:28 UTC, gpsietzema commented
@Alroniks You can already start with the dashboard-widgets extra; it doesn't need to depend on the additional installer screen. Is anyone working on that by the way? I know @Mark-H made a mockup once.

2019-08-20 12:23 UTC, Mark-H commented
Closing as there's consensus to move additional widget types into extras.

2019-08-20 12:23 UTC, closed without merging