Minor design tweaks and fixes for MODX3
modxcms/revolution pull request #14572
Opened 2019-04-25 14:45 UTC by joeke

### What does it do?

1. Removed box-shadow on most of the panels / tabs.
2. Slightly darken main background color (from #f2f2f2 to #f1f1f1) for a bit more contrast between tabs and background.
3. Fix panel collapse toggle arrow to correctly align in center
4. Decrease padding on `modx-action-buttons` element to better align with rest of elements, and prevent overlapping on pages without tabs
5. Make use of `$mainBg` sass variable where hardcoded background with same value was used.
6. Set `.panel-desc` background to white for more consistency with other panels.

### Why is it needed?
To give MODX3 a bit more modern look, and fix some inconsistencies in the sass files.

### Related issue(s)/PR(s)
None

2019-04-25 15:17 UTC, Ruslan-Aleev commented
Can you make screenshots to make the changes clearer?
See also https://github.com/modxcms/revolution/issues/14499 :)

2019-04-25 15:21 UTC, joeke commented
@Ruslan-Aleev Yes I will add some screenshots.

2019-04-25 15:26 UTC, joeke commented
@Mark-H @opengeek Please wait with reviewing / merging, somehow the modxcms/3.x got merged into this. Will fix it.

2019-04-26 03:06 UTC, Ibochkarev requested changes

2019-04-26 03:06 UTC, Ibochkarev commented on manager/templates/default/css/index.css
>            flex-wrap: nowrap;
Please don't commit the compiled CSS. The integrator who merges the PR will compile the final CSS.

2019-05-04 11:29 UTC, JoshuaLuckers commented
@joeke if you need any help let us know 👍

2019-05-05 14:38 UTC, joeke commented
@Mark-H @JoshuaLuckers @opengeek  PR is fixed now, I've reverted the 3.x merge comment so the correct file changes remain. The 3.x merge and it's commits is however still in the commit list, but the `Files changed` shows the correct changes. So reviewing can commence :).

2019-05-14 11:51 UTC, Ibochkarev commented
@joeke Please fix conflicts

2019-05-14 12:02 UTC, joeke commented
@Ibochkarev Conflicts should be solved now.

2019-05-14 12:03 UTC, Ibochkarev approved these changes

2019-05-14 13:32 UTC, JoshuaLuckers commented
I like the manager better with box-shadows and I'm not _yet_ convinced that removing them is an improvement. Can you elaborate why removing them gives the manager a more modern look? 

Screenshot with box-shadows:
<img width="1436" alt="modx3-manager-box-shadows" src="https://user-images.githubusercontent.com/1268085/57701994-67fa3e00-765d-11e9-8e28-d52390f26941.png">

Screenshot without box-shadows:
<img width="1436" alt="modx3-manager-box-shadows-removed" src="https://user-images.githubusercontent.com/1268085/57702011-70527900-765d-11e9-8110-790e2147ad48.png">

2019-05-14 13:37 UTC, Ruslan-Aleev commented
@JoshuaLuckers Subjectively :) I like more without shadows

2019-05-14 13:37 UTC, rthrash commented
The resource/element/file tree interior looks far better without the box shadows, but I prefer them elsewhere. Perhaps they could be more subtle/less offset, though?

2019-05-14 15:15 UTC, Ibochkarev commented
I am for leaving box-shadow. I missed this change ...

2019-05-14 16:15 UTC, Ruslan-Aleev commented
@kolbykruger Participate in the discussion? Maybe you have any suggestions?

2019-05-14 20:55 UTC, Ruslan-Aleev commented
In my opinion, without a gray background, the description of the section does not attract attention and "hangs in the void", see the picture below.

![after](https://user-images.githubusercontent.com/12523676/57731615-1c22b580-76ac-11e9-9e62-dd0d5204bc76.png)

2019-05-14 23:52 UTC, kolbykruger commented
I agree. I think it needs a grey background to add some depth. 

On another note, why do these show by default? They're helpful for the first time user of MODX, but for most people I think they're unnecessary. They should realistically be moved to a question mark icon that displays a tooltip on hover in my opinion.

2019-05-15 00:03 UTC, rthrash commented
And likely rewritten to streamline them a lot. "Here you can…" is a useless introductory clause.

For example on the above screenshot, the following would be a more concise and clearer description:

> Configure your MODX installation by double-clicking the values to edit inline or right-clicking for more options. Settings are available via their respective `[[++key-name]]` placeholders.

IMO descriptions should be shown by default, with `show/hide descriptions` button above the grids (depending on if they're showing or not).

2019-05-15 04:58 UTC, kolbykruger commented
As for the box-shadow vs no box-shadow, I prefer the flat version. However it does create some conflict with the sidebar elements. They would probably have to be changed to a different shade of grey. 

I personally still think the interface is too busy with clutter.

2019-05-15 07:36 UTC, joeke commented
Hi everybody! Nice to see I've stirred up some conversation 😉. Here are some of our thoughts behind the changes:

The drop-shadows are not very pretty on a lot of places (especially sidebar / tree) and make the interface look more cluttered. Admittedly on some places they don't look all that bad, but for the sake of consistency we dropped (😄) them on all the elements.

The white background on the description field is added to make the active tab + tab contents look more connected. The main reason is the resource editing page, where for example the 'Document' and 'Settings' tabs, when active, are white with also white background on the tab contents. But if you look at the 'Resource Groups' tab it just looks weird, look at these screenshots.

![Screen Shot 2019-05-15 at 09 19 43](https://user-images.githubusercontent.com/2332231/57756781-45673400-76f4-11e9-92d7-598720c6d340.png)

![Screen Shot 2019-05-15 at 09 19 53](https://user-images.githubusercontent.com/2332231/57756792-4a2be800-76f4-11e9-908b-298950e94c2b.png)

Also the gray color of the description (#F0F0F0) is not the same (but very close to) the main body background color (#FAFAFA), which looks weird when they're next to each other (as you can see in the screenshot).

2019-05-15 08:01 UTC, Ruslan-Aleev commented
@joeke Maybe it is worth making gray brighter, different from the background or choose a different color?

2019-05-15 18:47 UTC, kolbykruger commented
Knowing @joeke 's description I would argue that the textblock gets the same margining as the below fields, and that it get a different background treatment. Either a different grey color, or something that makes it defined as a 'tip' or 'section description'

2019-06-07 06:26 UTC, gpsietzema commented
I'd first go with this PR for fixing the weirdness and then create a new one for @kolbykruger 's (imho good) ideas.

2019-06-07 07:04 UTC, JoshuaLuckers approved these changes

2019-06-26 11:37 UTC, Mark-H requested changes
This PR needs to be rebased (or recreated if that's easier) to prevent including unrelated commits.

2019-07-31 11:05 UTC, Ibochkarev commented
@joeke please make rebase

2019-09-09 21:17 UTC, Mark-H commented
I've gone ahead and rebased the 2 relevant commits. There was an additional change related to the leftbar setting a minimum width which I removed from the PR as that was already addressed in another recent PR.

2019-09-09 21:22 UTC, Mark-H approved these changes

2019-09-09 21:22 UTC, merged

2019-09-09 21:25 UTC, Mark-H commented
For the record @joeke, to resolve this sort of issue where unrelated commits are included in a PR, use an interactive rebase instead of merge:

```
git rebase -i upstream/3.x
```

In the edit that pops up, start lines with `pick` that you want to include, and `drop` with PRs to remove. Then save (`esc` + type `:wq`) and the rebase will start applying your commits one-by-one onto `upstream/3.x`. 

When it conflicts, resolve the conflict and `git add` the conflicted files, and continue rebasing by typing `git rebase --continue`. When done rebasing, force push `git push --force origin branch-name` and the PR will be updated and clean.