Check if modx-content is defined before calling doLayout
modxcms/revolution pull request #14593
Opened 2019-05-22 01:18 UTC by jscaltreto

I have been having an issue where occasionally widgets would fail to load properly in the manager. I tracked it down to the call to doLayout() and found that sometimes when the listener gets called getCmp('modx-content') returned undefined. If I had to guess I'd say it's a race condition wherein sometimes the listener fires too early. Adding a check has resolved the issue entirely and I haven't encountered any ill effects.

### What does it do?
Adds a check to verify modx-content is defined before calling doLayout

### Why is it needed?
Intermittent issue of certain widgets not loading in the manager

2019-05-26 10:04 UTC, JoshuaLuckers commented on manager/assets/modext/widgets/core/modx.grid.js
> +                        if(cmp !== undefined) {
```suggestion
                        if(typeof cmp !== "undefined") {
```

2019-05-28 14:48 UTC, JoshuaLuckers submitted a review, later dismissed

2019-06-11 20:19 UTC, jscaltreto commented
@opengeek @Mark-H Can you have a look at this and  give feedback/merge as necessary? Thanks!

2019-06-26 11:02 UTC, Mark-H commented on manager/assets/modext/widgets/core/modx.grid.js
> +                        cmp = Ext.getCmp('modx-content');
Bit nitpicking, but this should be `var cmp = ...`; it's implicitly creating the variable now.

2019-06-26 11:02 UTC, Mark-H commented on manager/assets/modext/widgets/core/modx.grid.js
> +                        cmp = Ext.getCmp('modx-content');
Same here ^

2019-06-26 11:02 UTC, Mark-H requested changes
Variables should be explicitly defined, see inline comments.

2019-06-26 16:53 UTC, JoshuaLuckers commented on manager/assets/modext/widgets/core/modx.grid.js
> +                        cmp = Ext.getCmp('modx-content');
```suggestion
                        var cmp = Ext.getCmp('modx-content');
```

2019-06-26 16:53 UTC, JoshuaLuckers commented on manager/assets/modext/widgets/core/modx.grid.js
> +                        cmp = Ext.getCmp('modx-content');
```suggestion
                        var cmp = Ext.getCmp('modx-content');
```

2019-06-26 16:55 UTC, jscaltreto commented
Good catch @Mark-H.

2019-06-26 16:59 UTC, JoshuaLuckers approved these changes

2019-08-20 12:06 UTC, Mark-H approved these changes

2019-08-22 18:16 UTC, merged