Fix the system actions related to the database widgets
modxcms/revolution pull request #14629
Opened 2019-06-28 15:21 UTC by JoshuaLuckers

### What does it do?
Call the driver specific processors in the system database widget(s)

### Why is it needed?
There are no generic actions for some processors with driver specific processors after the refactor.

This is a quick fix. 

### Related issue(s)/PR(s)
Closes issue #14616

2019-06-28 19:00 UTC, opengeek commented
Why are these generic processors missing?

2019-06-30 11:37 UTC, JoshuaLuckers commented
I have no idea, I can reimplement them if that's more preferred.

2019-07-11 20:32 UTC, opengeek requested changes
I think it would be preferable to restore the generic processors for these actions.

2019-07-20 13:07 UTC, JoshuaLuckers commented
@opengeek done!

2019-07-24 22:03 UTC, merged