Check permissions for locked elements
modxcms/revolution pull request #14723
Opened 2019-09-07 13:37 UTC by JoshuaLuckers

### What does it do?
When editing a locked snippets, templates, template variables, and plugins make sure the user has the right permissions to do so

### Why is it needed?
To make sure only users with the `edit_locked` permissions can edit locked elements.

### Related issue(s)/PR(s)
Fixes issue #14702

2019-09-09 13:06 UTC, Mark-H commented
Is the PR missing new lexicons for snippets/chunks/tvs or were they already there (but not used)?

2019-09-09 13:36 UTC, opengeek commented
I think there is some confusion. Locked refers to the locking mechanism associated with Resources only.

2019-09-09 14:10 UTC, Mark-H commented
Elements can also be locked, though that is indeed a different mechanism than resource locks (and it didn't really work as they could still be edited).

2019-09-09 14:54 UTC, opengeek commented
@Mark-H they can, but it is a much simpler mechanism and has never been related to ACLs. The "lock" mechanism on elements is simply to prevent non-administrators from being able to edit it.

2019-09-09 18:54 UTC, opengeek commented
Ok, I'm wrong about the ACLs, but I thought the mechanism has always been to prevent saving, not to prevent loading the element into the edit view. The check is in modElementUpdateProcessor::beforeSave().

2019-09-09 19:40 UTC, opengeek requested changes
After a discussion with @Mark-H, we have determined that the issue is that the lock test in modElementUpdateProcessor::beforeSave() is happening after the `locked` property is set/unset from the request. 🤦‍♂The `locked` property was never intended to prevent loading the edit view for an element, but only to prevent saving changes to it. There are other ACL permissions for blocking access altogether. So, the test for locked needs to happen before the property is set/unset from the request, AND, if chunks are already being prevented from loading via this permission, that needs to be reverted.

2019-09-18 16:12 UTC, Mark-H commented
I've created a new PR #14739 that fixes this in the processors, rather than the controllers, so am closing this one. Let me know if you disagree @JoshuaLuckers.

2019-09-18 16:12 UTC, closed without merging