Fixed triangle submenu styles
modxcms/revolution pull request #14778
Opened 2019-10-01 17:10 UTC by Ruslan-Aleev

### What does it do?
Changed styles to %:

![1](https://user-images.githubusercontent.com/12523676/65984023-dbc3a880-e48f-11e9-8918-03cea7c4ed2a.png)

![2](https://user-images.githubusercontent.com/12523676/65984025-dc5c3f00-e48f-11e9-91a8-6a335c5fba55.png)

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/14777

2019-10-01 19:18 UTC, Ibochkarev approved these changes

2019-10-01 20:17 UTC, Jako requested changes

2019-10-01 20:17 UTC, Jako commented on _build/templates/default/sass/_navbar.scss
> +    top: 40%;
Maybe you could use `top:50%; transform:translateY(-50%)` to make it vertical centered.

2019-10-03 17:05 UTC, JoshuaLuckers approved these changes

2019-10-03 21:17 UTC, Jako approved these changes

2019-10-19 12:00 UTC, merged