Fixed a bug with appearance of save animation over logo
modxcms/revolution pull request #14787
Opened 2019-10-11 18:00 UTC by Ruslan-Aleev

### What does it do?
If you edit a resource and drag the same resource in the tree, a save animation appears next to the logo.

![save-anim](https://user-images.githubusercontent.com/12523676/66673838-85661f00-ec72-11e9-920d-0dccc5b0d920.gif)

This PR fixes this bug through increasing `z-index`.

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/14428

2019-10-12 10:03 UTC, JoshuaLuckers commented
I believe it's better to fix the actual issue, the animated element being in the wrong place. It looks to be related to the animated effect you get when, for example, you drag and drop resources in the tree.

2019-10-12 10:35 UTC, Ruslan-Aleev commented
I do not think that someone will correct this differently, because work will take more than profit :) I tried to find out why this happens, but I did not find it.
The element appears before `</body>`, here is the GIF:

![save-anim-2](https://user-images.githubusercontent.com/12523676/66700036-61035480-ecfd-11e9-9a36-64f32ef21186.gif)

2019-10-15 08:01 UTC, JoshuaLuckers approved these changes
> I do not think that someone will correct this differently, because work will take more time than possible profit :)

I agree and the actual underlying issue can always be fixed later down the road.

2019-10-15 10:26 UTC, Mark-H requested changes
This has worked in the past so should be fixed properly. A z-index of 99999 also sounds arbitrary and not based on any particular other z-index that we're trying to +1.

2019-10-15 10:42 UTC, Ruslan-Aleev commented
> This has worked in the past so should be fixed properly

This bug is also relevant for 2.x, i.e. this did not work in the past :)
And z-index can be set **35001**, if it matters, because z-index 35000 stands at the div with animation, see gif above.

2019-10-15 13:14 UTC, JoshuaLuckers commented
> I do not think that someone will correct this differently, because work will take more time than possible profit :)

It took a few hours but I think I found the root cause of this issue!

2019-10-15 13:37 UTC, Ruslan-Aleev commented
@JoshuaLuckers Thank for your time, a little later I will test your PR and close my :)

2019-10-15 14:09 UTC, closed without merging