fix php7.4 compatibility. Remove curly braces syntax
modxcms/revolution pull request #14863
Opened 2019-12-02 14:09 UTC by catsmeatman

In php7.4 Deprecated: Array and string offset access syntax with curly braces is deprecated

### What does it do?
change {} to []

### Why is it needed?
for compatibility with php7.4

2019-12-02 18:23 UTC, Jako commented
Thanks for taking time to create this PR and help make MODX better. Since this is your first time contributing the first step is to [fill out and send in a Contributor License Agreement (CLA)](https://docs.modx.com/community/contribute/becoming-a-contributor).

If you did sign the CLA please let us know by providing your MODX username 😄.

2019-12-02 19:15 UTC, opengeek requested changes
This cannot be accepted as is since it makes changes to the xPDO dependency directly here. The changes to the core/xpdo files will need to be made to the xpdo project.

2019-12-02 22:06 UTC, Jako commented
Sure, but the PR itself is valid. @catsmeatman could you create a PR with your xpdocachemanager changes in https://github.com/modxcms/xpdo/blob/2.x/xpdo/cache/xpdocachemanager.class.php in the 2.x branch of the xPDO Repository?

2019-12-02 22:09 UTC, opengeek commented
@Jako it will be valid once the changes to the xPDO files are removed from the commit, sure.

2019-12-02 22:12 UTC, Jako commented
This leads to the question: Do we need/want to make Revo 2.x compatible with PHP 7.4?

@opengeek Please don't nitpick about the use of 'valid' with a not native speaker.

2019-12-02 22:15 UTC, opengeek commented
@jako I'm not nitpicking. I'm just stating what needs to happen to make sure these important changes get into all of the right places (xPDO 2.x and 3.x), as well as the next patch release of MODX 2.x and 3.x. I'm not sure where you get the idea that I am nitpicking. I'm trying to make sure the issue is clear. It truly sucks that we have to separate the changes to files that are actually committed to the 2.x repository because of the way we handled dependencies historically, but I am just trying to avoid any confusion on the integration team on how this can get adopted.

2019-12-02 22:17 UTC, opengeek commented
And yes, IMO, we need to get this into 2.x because PHP 7.4 is already released and 3.x is not.

2019-12-02 22:20 UTC, Jako commented
Ok. Sorry for beeing over-sensitive.

2019-12-03 08:41 UTC, JoshuaLuckers commented
As long as it doesn't break backwards compatibility I see no reason not to support a newer version of PHP.

2019-12-03 19:22 UTC, catsmeatman commented
> fill out and send in a Contributor License Agreement (CLA)

Done. Just send the CLA.

> This cannot be accepted as is since it makes changes to the xPDO dependency directly here. The changes to the core/xpdo files will need to be made to the xpdo project.

> Sure, but the PR itself is valid. @catsmeatman could you create a PR with your xpdocachemanager changes in https://github.com/modxcms/xpdo/blob/2.x/xpdo/cache/xpdocachemanager.class.php in the 2.x branch of the xPDO Repository? Edit: And remove these changes here afterwards, please.

ОК. I split my commit into 2 part's for MODx and xPDO repo.

2019-12-04 17:02 UTC, opengeek commented
@catsmeatman I have not seen a PR in the xPDO repository, nor have you updated this PR yet. Were you still planning to push those changes?

2019-12-07 11:17 UTC, JoshuaLuckers commented
@catsmeatman if you need help let us know!

2019-12-12 03:10 UTC, merged