Bug reset event returned values
modxcms/revolution pull request #15057
Opened 2020-04-09 18:52 UTC by mvoevodskiy

### What does it do?
Fixed reset of returned values by next plugins.

### Why is it needed?
It is needed to use $modx->event->returnedValues in sequence plugins.

### Related issue(s)/PR(s)
#15056 15056

2020-04-14 18:46 UTC, opengeek commented
1. You seem to have merged an extraneous pull request into the branch you used to create this PR. We will not be able to accept this PR with this history.

2. I do not understand the problem you are solving and attempted to describe in the linked issue. Can you provide some examples that better explain the problem you are trying to solve?

2020-04-14 18:48 UTC, opengeek requested changes
The commit fbdaa80 needs to be removed from this. In addition, a better description of the problem being solved needs to be provided.

2020-04-29 20:37 UTC, mishantrop commented on core/src/Revolution/modSystemEvent.php
> +        }
Раньше данные сбрасывались всегда, а теперь по умолчанию они сбрасываются только если явно передать `true`. Вижу здесь проблемы с обратной совместимостью, хотя в коде MODX вижу только один вызов этого метода.

2020-04-30 00:10 UTC, mvoevodskiy commented on core/src/Revolution/modSystemEvent.php
> +        }
Совершенно верно, вызов во всем ядре MODX только в одном месте. Об обратной совместимости думал, но здесь она не нарушается. 

Но, кстати, спасибо за мысль. Для точного сохранения обратки можно сделать наоборот.

2021-04-04 06:39 UTC, Ibochkarev commented
@mvoevodskiy Thanks for your work. Due to lack of activity, I close in favor of PR #15577

2021-04-04 06:39 UTC, closed without merging