Added allowBlank for TV with Image and File type
modxcms/revolution pull request #15075
Opened 2020-05-07 13:00 UTC by Ruslan-Aleev

### What does it do?
Added allowBlank for TV with Image and File type

![files-req](https://user-images.githubusercontent.com/12523676/81297269-b200de80-907b-11ea-8ef8-15b4e926695a.gif)

### Why is it needed?
For some reason, allowBlank is not for all TVs, which is strange

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/6521 - Image and File
https://github.com/modxcms/revolution/pull/15074
https://github.com/modxcms/revolution/pull/15073

2020-05-10 09:29 UTC, JoshuaLuckers commented
> I can also display a message that the field is required, but it will disappear only after saving (since the value has not yet been set to the hidden field)

Could this be solved by adding a listener that fires `MODx.fireResourceFormChange` when the `change` event happens instead of the `keydown`? I believe the date TV works similar: https://github.com/modxcms/revolution/blob/f64b6063bd6256106c9a2db89d9febfa850a82ac/manager/templates/default/element/tv/renders/input/date.tpl#L32

2020-05-10 16:30 UTC, Ruslan-Aleev commented
Unfortunately, there is no difference.

The value of the hidden field changes, but `listeners: {'change': {fn: MODx.fireResourceFormChange, scope: this}}` will work if the value is changed directly in the field (as I understand it), but since If the field is hidden, then the error does not disappear.

Here's what it looks like if the hidden field is displayed:
![img-req-3](https://user-images.githubusercontent.com/12523676/81504793-f0a0ce00-92f3-11ea-950e-222a86867a72.gif)

Initially, the problem is that the TV with the output of the file browser (image and file) does not have validation, it does not work, and you have to catch the hidden field validation.

_By the way, on TV with the date type error messages are also not shown :)_

2020-05-11 13:44 UTC, Jako commented
The hidden field needs the onchange listener then.

2020-05-20 15:14 UTC, Ruslan-Aleev commented
I changed PR, it works, but I still have the idea that it can be done more literally and simply :)

![tv-files-req](https://user-images.githubusercontent.com/12523676/82463534-9f4bc800-9ac5-11ea-8ec7-a77c5b87f5ae.gif)

2020-05-24 22:37 UTC, Jako requested changes
Yes, it could be solved a lot simpler: The PR should contain an additional `,msgTarget: 'under'` in the in the defaults section and the already made `,allowBlank: config.allowBlank` addition to FileTV/ImageTV in `modx.panel.tv.renders.js` and no changes in `/renders/input/*.tpl`

2020-05-25 12:49 UTC, Ruslan-Aleev commented
@Jako It doesn’t work, your variant adds a message below to select files, which is useful.
But `allowBlank: false` does not work for selecting files, it saves in any case. Therefore, we will need to create a 2nd hidden field.

![tv-files-nreq](https://user-images.githubusercontent.com/12523676/82814210-55852800-9e9f-11ea-84fc-88e4915ec0c3.gif)

2020-05-25 13:41 UTC, Ruslan-Aleev commented
@Jako @JoshuaLuckers I updated the PR, redid it easier, but without a hidden field I can’t do it anyway.

2020-05-25 15:26 UTC, Jako commented
Ok, I forgot to check if the resource could be saved without the requirement.

2020-05-29 07:33 UTC, Jako commented
The file/image tv already contains a hidden field in `manager/assets/modext/widgets/element/modx.panel.tv.renders.js`, but this field seems not to trigger the validation of the resource form.

2020-05-29 09:08 UTC, Jako commented
I have changed the code for the image tv
- add the field to the resource form (https://github.com/modxcms/revolution/pull/15075/files#diff-a71262af33263e3041a682eddb38f566R72)
- add a validation for the image tv (https://github.com/modxcms/revolution/pull/15075/commits/458a73da0b6f65484a46c7607e2dcbd085fd373f#diff-a71262af33263e3041a682eddb38f566R58)

The validation could be maybe moved to a method in the xtype.

The same change has to be done for the file tv.

2020-05-29 09:10 UTC, Jako requested changes
I have changed the code for the image tv. It has to be done for the file tv.

2020-05-29 09:12 UTC, Ruslan-Aleev commented
@Jako Thanks for the help, it looks great. I will test and make for the file TV.

2020-05-29 14:17 UTC, Ruslan-Aleev commented
@Jako have you tested your variant? It does not work for me (js and css compression is disabled, tested in incognito mode):

- **Does not save the resource, even if the TV is not empty**
- No * next to the name of required field

![files-req-5](https://user-images.githubusercontent.com/12523676/83269695-24269800-a1d0-11ea-916f-c87f2699c825.gif)

2020-05-29 17:39 UTC, Jako commented
Now it gets the right value.

2020-05-30 10:39 UTC, Jako commented
And now the asterisk is shown on required TVs. This MODx component is a big mess.

2020-05-30 10:42 UTC, Ruslan-Aleev commented
As a result, after many edits, we returned almost to what it was :)
It's cool that it works, this functionality is extremely lacking.

2020-05-30 13:12 UTC, Jako commented
I tried to remove the annoying MODx.load just to get the asterisk shown on the TV label. It works fine here, but please do a cross check on your installation too.

2020-05-30 15:10 UTC, Jako approved these changes

2020-06-09 07:40 UTC, JoshuaLuckers approved these changes
Great work!

2020-06-11 15:06 UTC, merged