Remember the filter properties of the system setting grid in the browser url
modxcms/revolution pull request #15086
Opened 2020-06-02 06:13 UTC by Jako

### What does it do?
Add the selected settings filter properties in the browser url

### Why is it needed?
Allow to copy/paste the state of the filter with the browser url i.e. for support sessions 

### Related issue(s)/PR(s)
#14086

2020-06-02 07:28 UTC, Ruslan-Aleev commented
Very useful feature.
After implementation, for example, it allows developers to make links to package settings in the menu (and not just "System Settings", as it is now).

2020-06-02 07:56 UTC, Jako commented
You could link to a namespace before this PR even in 2.7.x with i.e.
`manager/?a=system/settings&ns=pdotools`. But now the browser url is changed and could be copied.

But I prefer an own namespaced system settings grid in the CMP of my extras like in CustomRequest:
<img width="1122" alt="CMP with namespaced system settings" src="https://user-images.githubusercontent.com/148371/83494872-2f6f1180-a4b7-11ea-85f3-a3f42306a892.png">

2020-06-02 08:03 UTC, Ruslan-Aleev commented
> You could link to a namespace before this PR even in 2.7.x with i.e.
manager/?a=system/settings&ns=pdotools

I did not know this, it is strange that almost no one does this :)

2020-06-03 07:45 UTC, Ruslan-Aleev approved these changes
Great PR!

2020-06-03 07:52 UTC, sergant210 commented
> You could link to a namespace before this PR even in 2.7.x with i.e.
manager/?a=system/settings&ns=pdotools.

Yep, and with the area parameter

```
manager/?a=system/settings&ns=core&area=mail
```

2020-06-03 08:15 UTC, Ruslan-Aleev commented
> Yep, and with the area parameter

After implementing this PR, this will become more obvious + filter by key in the URL :)

2020-06-09 10:24 UTC, JoshuaLuckers commented
This makes me happy! It would be nice to have this functionality for all components that extend `MODx.grid.Grid`. Is it possible to make this reusable in some way and prevent (a lot of) code duplication?

2020-06-09 11:07 UTC, Jako commented
It could be added with some work. First we have to create a new property i.e. `urlFilters: ["ns","area","search"]` to the `MODx.grid.Grid` and make the URL generation/change active, when this property is filled with an array. And we need a trigger method to change the baseParams of the store (maybe a listener would work too), which would trigger the url generation/change method.

2020-06-09 16:03 UTC, theboxer requested changes

2020-06-09 16:03 UTC, theboxer commented on manager/assets/modext/widgets/core/modx.grid.settings.js
> +            window.history.replaceState(s.baseParams, document.title, this.makeUrl());
I'd vote for checking if `window.history.replaceState` exists.

2020-06-09 16:03 UTC, theboxer commented on manager/assets/modext/widgets/core/modx.grid.settings.js
> +            window.history.replaceState(s.baseParams, document.title, this.makeUrl());
I'd vote for checking `window.history.replaceState`

2020-06-09 16:03 UTC, theboxer commented on manager/assets/modext/widgets/core/modx.grid.settings.js
> +            window.history.replaceState(s.baseParams, document.title, this.makeUrl());
I'd vote for checking `window.history.replaceState`

2020-06-09 16:03 UTC, theboxer commented on manager/assets/modext/widgets/core/modx.grid.settings.js
> +            window.history.replaceState(s.baseParams, document.title, this.makeUrl());
I'd vote for checking `window.history.replaceState`

2020-06-09 18:54 UTC, theboxer approved these changes

2020-06-11 18:58 UTC, merged

2020-06-15 11:19 UTC, theboxer commented
@Jako This PR messed up user management. If you edit any user, the URL changes right after the load from ?a=security/user/update&id=1` to `/?a=security/user%2Fupdate&ns=core`.

Would you be able to provide a quick fix? We'll have to revert this PR otherwise...

2020-06-15 14:59 UTC, Jako commented
Better revert this. I create a new approach with `urlFilters: ["ns","area","search"]` enabling the url modification only for grids that have this property set. There could be other places, where the `modx-grid-settings` is used. Those will be messed uptoo.

2020-06-15 15:31 UTC, theboxer commented
I like the new approach, thanks :)

2020-06-15 17:51 UTC, Jako commented
Those lines have to be commented out for a quick fix: 
```window.history.replaceState(s.baseParams, document.title, this.makeUrl());```

2020-06-15 18:37 UTC, Jako commented
I am quite finished with the patch.