Resize static fields on statick checkbox toggle
modxcms/revolution pull request #15100
Opened 2020-06-10 14:13 UTC by theboxer

### What does it do?
It resizes `Static File` and `Media Source for Static File` inputs on the `Is Static` checkbox toggle. I'm not sure if this is the best approach for the resize, but it does the trick.

### Why is it needed?
Without this change, both combo boxes are tiny :)

### Related issue(s)/PR(s)
Closes #14986

2020-06-11 19:44 UTC, Ibochkarev requested changes
Chunks - OK
![image](https://user-images.githubusercontent.com/2138260/84431955-f6206980-ac4d-11ea-9da5-0a2c346115bd.png)

Templates - not OK
![image](https://user-images.githubusercontent.com/2138260/84432083-1cdea000-ac4e-11ea-8be8-e6084f2a5090.png)

Snippet - OK
![image](https://user-images.githubusercontent.com/2138260/84432140-367fe780-ac4e-11ea-9623-aed2e062b944.png)

Plugin - OK
![image](https://user-images.githubusercontent.com/2138260/84432175-4992b780-ac4e-11ea-8f40-6009dbca85a0.png)

TV - Not OK
![image](https://user-images.githubusercontent.com/2138260/84432372-8d85bc80-ac4e-11ea-8cfb-12a21b81ba2c.png)

2020-06-12 06:58 UTC, Jako approved these changes

2020-06-12 07:03 UTC, Jako commented
Maybe the file combos in TV and Template don't have an anchor set or something else is not extended to the maximum width.

2020-06-12 07:53 UTC, theboxer commented
@Ibochkarev Could you please try and few refreshes / clear browser cache etc. on the TVs and Templates? They seems fine on my local...

@Jako They all have anchors set :)

2020-06-29 07:10 UTC, Ibochkarev approved these changes
![image](https://user-images.githubusercontent.com/2138260/85983764-e654a380-ba09-11ea-8b42-a4e41bd8ad7c.png)
![image](https://user-images.githubusercontent.com/2138260/85983793-f1a7cf00-ba09-11ea-9096-230fe3b26dca.png)

2020-07-04 12:37 UTC, JoshuaLuckers approved these changes

2020-07-04 12:39 UTC, merged