Added a localization link in the Help section
modxcms/revolution pull request #15138
Opened 2020-06-26 17:37 UTC by Ruslan-Aleev

### What does it do?
Added a localization link in the Help section:

Before
![local_1](https://user-images.githubusercontent.com/12523676/85885259-b67c8480-b7ec-11ea-91cb-77847e51d1e3.png)

After
![local_2](https://user-images.githubusercontent.com/12523676/85885262-b7151b00-b7ec-11ea-922b-110750e3cace.png)

### Why is it needed?
Not many people know where you can correct an inaccuracy in a translation, or add a translation.

### Related issue(s)/PR(s)
None

2020-06-26 17:40 UTC, Ibochkarev approved these changes

2020-06-26 18:44 UTC, JoshuaLuckers requested changes

2020-06-26 18:44 UTC, JoshuaLuckers commented on core/lexicon/en/about.inc.php
> +$_lang['localization_link'] = 'https://crowdin.com/project/modx';
```suggestion
$_lang['localization_link'] = 'https://crowdin.com/project/modx-revolution';
```

2020-06-27 08:31 UTC, JoshuaLuckers commented
Looks good to me, I would like to see if @jaygilmore has any thoughts on this as well 😄.

2020-06-27 14:09 UTC, rthrash commented
Jay’s our until mid-week, but I can comfortably say that we both love this. Great PR.

2020-06-27 16:15 UTC, JoshuaLuckers approved these changes

2020-06-28 10:03 UTC, merged