Clean up JS files
modxcms/revolution pull request #15161
Opened 2020-07-18 11:07 UTC by JoshuaLuckers

### What does it do?
Remove unnecessary comments and uncommented code in JS files and remove some extra whitespaces at some places.

### Why is it needed?
Currently contributors remove unnecessary comments and uncommented code when they encounter it when fixing/changing the file. This is great and but creates unnecessary noise and/or make it difficult to see actual changes in a PR.

Doing it all at once cleans up the code base and reduces the noise. 

### Related issue(s)/PR(s)
n/a

2020-07-18 11:08 UTC, JoshuaLuckers commented
Please let me know if I missed any!

2020-07-18 21:06 UTC, opengeek commented
I like this, but isn't this going to conflict with every outstanding PR that affects JS?

2020-07-18 21:14 UTC, JoshuaLuckers commented
> I like this, but isn't this going to conflict with every outstanding PR that affects JS?

Most likely yeah. A small annoyance for contributors affected by it but in the long term both contributors and reviewers will benefit from it. By doing it once we have less noise in other PR's and make diffs easier to read.

2020-07-19 09:11 UTC, JoshuaLuckers commented
I also wouldn't mind if the other existing PRs would go first and that I resolve the conflicts.

2020-07-20 08:41 UTC, Ruslan-Aleev commented
Great!
It would be useful, before the official release of 3.x, to implement this PR too - https://github.com/modxcms/revolution/issues/14311

2020-07-22 11:23 UTC, theboxer requested changes

2020-07-22 11:23 UTC, theboxer commented on manager/assets/modext/core/modx.js
> +        });w
Seems like the `w` shouldn't be there :)

2020-07-22 11:24 UTC, theboxer commented
@opengeek I wouldn't be too concerned about conflicts, as all changes are only around removing comments and new lines here and there, so all conflicts (if they occur) should be fairly simple to resolve.

Good job @JoshuaLuckers

2020-07-22 17:43 UTC, theboxer approved these changes

2020-07-26 08:13 UTC, Ruslan-Aleev approved these changes

2020-08-01 09:59 UTC, closed without merging

2020-08-01 13:10 UTC, opengeek commented
@JoshuaLuckers — why did we close this?

2020-08-03 16:46 UTC, opengeek commented
@JoshuaLuckers — did this just get merged in a way that did not show it as merged? I'm confused as to what happened here.

2020-08-04 08:33 UTC, JoshuaLuckers commented
@opengeek yes, I did a squash merge but GitHub didn't recognize it for some reason..

2020-08-04 14:11 UTC, opengeek commented
Ok, yeah, if you squash it yourself, you have to force push it to the PR branch first. Squash only works with the buttons here in the UI otherwise.

2020-08-04 14:29 UTC, JoshuaLuckers commented
Good to know, thanks!