Register woff2 format in system settings
modxcms/revolution pull request #15160
Opened 2020-07-17 15:53 UTC by Ibochkarev

### What does it do?
Registers the woff2 format in the default settings to allow downloads.

### Why is it needed?
Registration of woff2 format in the Types of downloaded images setting upload_files for working with formats out of the "box"

### Related issue(s)/PR(s)
NA

2020-07-19 20:57 UTC, Jako requested changes

2020-07-19 20:57 UTC, Jako commented on _build/data/transport.core.system_settings.php
> +  'value' => 'txt,html,htm,xml,js,css,zip,gz,rar,z,tgz,tar,mp3,mp4,aac,wav,au,wmv,avi,mpg,mpeg,pdf,doc,docx,xls,xlsx,ppt,pptx,jpg,jpeg,png,tiff,svg,svgz,gif,psd,ico,bmp,odt,ods,odp,odb,odg,odf,md,ttf
I would sort the list by type (scss, less css.map after css, webp after bmp and woff2 after woff)

2020-07-21 11:25 UTC, JoshuaLuckers approved these changes
This also needs to be done in 3.x

2020-08-18 07:51 UTC, Jako approved these changes

2020-08-18 07:55 UTC, Ruslan-Aleev commented
@Jako maybe it's better to arrange the groups of files in the order of frequency of use? For example, images are more often downloaded than archives. And dock files are more often than video, etc.

2020-08-18 07:59 UTC, Ruslan-Aleev commented
For example:
`'value' => 'html,htm,xml,js,js.map,css,scss,less,css.map,jpg,jpeg,png,tiff,svg,svgz,gif,psd,ico,bmp,webp,txt,pdf,doc,docx,xls,xlsx,ppt,pptx,odt,ods,odp,odb,odg,odf,md,zip,gz,rar,z,tgz,tar,mp3,mp4,aac,wav,au,wmv,avi,mpg,mpeg,ttf,woff,woff2,eot',`

2020-08-18 08:23 UTC, Jako commented
I just grouped them because then not wanted groups are easier to remove from the system setting.

2020-08-25 14:27 UTC, merged