Language switcher now remembers the page
modxcms/revolution pull request #15174
Opened 2020-07-29 18:48 UTC by Ruslan-Aleev

### What does it do?
When changing the language, the language switch opened the manager home page, which is inconvenient. The language switcher now remembers the page.

Unfortunately, caching does not update the `&page` (change language page) parameter and I have no idea how to fix this problem.

If you comment out this line - https://github.com/Ruslan-Aleev/revolution/blob/20eb1adb899a43d52fa8a7888e3bec564ee1b60f/core/src/Revolution/modMenu.php#L69, then the switch works as desired.

![switch_lang](https://user-images.githubusercontent.com/12523676/88840454-2794ca80-d1e5-11ea-89e5-9823c8eb9b18.gif)

### Why is it needed?
Now the language switcher remembers the page on which the language was changed.

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/pull/14046

2020-07-29 18:53 UTC, Ruslan-Aleev commented
@Jako @JoshuaLuckers @Alroniks Any ideas on how to fix the caching problem?
p.s. I understand that the user will not switch the language often, but the way the switch works now is not very convenient. Especially when testing PR.

2020-07-29 20:43 UTC, Jako requested changes

2020-07-29 20:43 UTC, Jako commented on core/src/Revolution/modMenu.php
> +        if (!empty($_SERVER['QUERY_STRING'])) {
$_SERVER['QUERY_STRING'] could contain more than the page request parameter.

Maybe you could use `$params = $this->modx->request->getParameters` to access the values, add the switch parameter and `str_replace('%2F', '/', $this->modx->toQueryString($params))` as params value. Then a CMP would be open after the switch etc.

2021-10-12 09:51 UTC, theboxer commented
@Ruslan-Aleev you still planning to work on this as it's still marked as draft?

2021-10-12 10:03 UTC, Ruslan-Aleev commented
@theboxer I'm not sure if this can be fixed with this menu implementation.
I can close PR, maybe you have a smart solution.

2021-10-12 10:06 UTC, theboxer commented
@Ruslan-Aleev I don't have any solutions, just going through PRs that are left in void.

2021-11-08 20:54 UTC, alroniks commented
@Ruslan-Aleev I've created a proper solution in the #15895 and this one I am closing if you don't mind.

2021-11-08 20:54 UTC, closed without merging