3.x Added check that the file exists when uploading it
modxcms/revolution pull request #15264
Opened 2020-09-22 10:40 UTC by Ruslan-Aleev

### What does it do?
Same as in https://github.com/modxcms/revolution/pull/15232 but for the 3.x branch.

Added a check for the existence of a file when uploading it.
In the current version, **if the file names match, then the file will be overwritten.**

![files_check](https://user-images.githubusercontent.com/12523676/93872652-22319900-fcd9-11ea-8b45-e08dbb026a3d.gif)

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/pull/15232
https://github.com/modxcms/revolution/issues/8371
https://github.com/modxcms/revolution/issues/14641

2020-09-22 10:51 UTC, Ibochkarev approved these changes

2020-09-23 13:03 UTC, theboxer approved these changes

2020-10-13 10:18 UTC, JoshuaLuckers requested changes
Please add the system setting that's introduced in PR #15285.

2021-02-13 15:02 UTC, Ruslan-Aleev commented
@JoshuaLuckers I forgot about PR completely, added a setting, check :)

2021-02-15 10:18 UTC, JoshuaLuckers submitted a review, later dismissed

2021-02-15 10:18 UTC, JoshuaLuckers commented on _build/data/transport.core.system_settings.php
> +), '', true, true);
```suggestion
$settings['upload_file_exists']->fromArray([
  'key' => 'upload_file_exists',
  'value' => true,
  'xtype' => 'combo-boolean',
  'namespace' => 'core',
  'area' => 'file',
  'editedon' => null,
], '', true, true);
```

2021-02-15 10:19 UTC, JoshuaLuckers commented
I believe it's better to have the markup be part of the lexicon.

2021-03-02 21:04 UTC, merged