JsonGrid fixes
modxcms/revolution pull request #15346
Opened 2020-12-04 17:15 UTC by Jako

### What does it do?
- Change the record value of the currently edited field on keyup
- Don't use the context menu for deleting a record.
- Remove the column menu for the grid.

### Why is it needed?
- When the user clicks on save before the currently edited field loses the focus, the changes in the current field are not saved.
- The context menu does not make sense, since there is only one delete entry in that menu.
- The column menu does not make sense, since the columns are not sortable (the grid is sortable by drag & drop).

### How to test
Create a new system setting with the field type JSON Grid and save that setting. The JSON grid is visible during editing the the setting in the edit window at the bottom.

### Related issue(s)/PR(s)
None known

2021-01-25 09:17 UTC, JoshuaLuckers approved these changes

2021-02-11 12:05 UTC, theboxer requested changes
I still see the context menu on the JsonGrid. I believe you'll have to remove the getMenu method to nuke it.

2021-02-13 06:18 UTC, Jako commented
Thanks, the description of the fix was a bit wrong. I meant 'require' instead of 'use'. If someone is used to right click on the row, this is possible too.

2021-02-13 20:06 UTC, theboxer approved these changes

2021-02-24 19:19 UTC, merged