Update modLexicon.php
modxcms/revolution pull request #15377
Opened 2021-02-06 21:23 UTC by BobRay

Sanity check to prevent PHP error if $_SESSION is not set

### What does it do?
Make sure $_SESSION variable exists before it's referenced

### Why is it needed?
Existing code breaks automated acceptance tests (and possibly unit tests) where $_SESSION isn't necessarily set.

### Related issue(s)/PR(s)
Issue: #15373

2021-02-06 21:25 UTC, BobRay commented
@cla-bot check

On Sat, Feb 6, 2021 at 4:23 PM cla-bot[bot] <notifications@github.com>
wrote:

> Thank you for your contribution! Before your pull request can be reviewed,
> please sign the MODX Contributor License Agreement (CLA)
> <https://modx.com/community/contribute/cla/>. This is to make sure MODX
> has your written permission to distribute projects containing your
> contributions under the appropriate license.
>
> Please make sure the CLA has been signed for GitHub user(s): @BobRay
> <https://github.com/BobRay>
>
> Once you've signed, please reply with @cla-bot check to verify and update
> the status of this pull request.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/modxcms/revolution/pull/15377#issuecomment-774546042>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACRZIUQBBEQH3G44M2IU33S5WXNRANCNFSM4XGVXNNA>
> .
>

2021-02-07 12:10 UTC, JoshuaLuckers approved these changes

2021-02-09 10:44 UTC, JoshuaLuckers approved these changes

2021-02-19 08:19 UTC, alroniks requested changes, later dismissed

2021-02-19 08:19 UTC, alroniks commented on core/src/Revolution/modLexicon.php
> +            $_SESSION = isset($_SESSION) ? $_SESSION : [];
As we support PHP 7.0+ for MODX 3, I suggest using null coalescing operator.

2021-02-19 08:19 UTC, alroniks commented on core/src/Revolution/modLexicon.php
>              $defaultLanguage = $this->modx->getOption('manager_language', $_SESSION,
```suggestion
            $defaultLanguage = $this->modx->getOption('manager_language', $_SESSION ?? [],
```

And check above is not needed.

2021-02-20 20:45 UTC, BobRay commented
Using the null coalescing operator is fine with me.

2021-03-02 21:15 UTC, opengeek commented
I modified this to use the null coalescing operator rather than setting the global variable $_SESSION. Though chances are slim this would ever have a real-world consequence, setting the value of a PHP superglobal to avoid an error seemed like the wrong approach.

2021-03-02 21:19 UTC, merged

2021-03-03 16:32 UTC, BobRay commented
> I modified this to use the null coalescing operator rather than setting the global variable $_SESSION. Though chances are slim this would ever have a real-world consequence, setting the value of a PHP superglobal to avoid an error seemed like the wrong approach.

It regularly crashed Codeception acceptance tests of the MODX Manager, so I'm glad it's fixed.  Using the null coalescing operator is a much better approach than mine.