Fix chunk/snippet blank page with <script><!--
modxcms/revolution pull request #15395
Opened 2021-02-17 15:16 UTC by theboxer

### What does it do?
It insert's `"-->"` at the end of the `snippetArray`/`chunkArray`.

The tricky question here is why it works. My humble opinion is that this is some kind of a browser issue. The edit snippet/chunk page's controller converts the object to JSON and passes it to `MODx.load` as `record` prop. The JSON itself is valid, but when it's placed in the source code of the page, it somehow breaks. Seems like the browser don't understand that the `<script>` to the JSON, makes the browser think that everything is OK and it renders the page correctly. The JS is able to read the whole JSON without an issue.

### Why is it needed?
For unknown reason people tried to save a snippet or chunk with `<script><!--` which is obviously invalid for snippets and for html as well. So if you do this twisted thing, the edit snippet/chunk page will blank after reload.

### How to test
Described here: #15222 + try in chunk as well

### Final note
I'm not sure if we want to merge this, it seems like it fixes the related issue, but it's weird. I've spent so much time on this and I'm not willing to explore more. Feel free to submit other ideas.

### Related issue(s)/PR(s)
#15222

2021-02-17 15:24 UTC, Jako commented
Would it help to wrap that part in `<![CDATA[`?

2021-02-17 15:31 UTC, theboxer commented
It's already there
```php
$this->addHtml('
        <script type="text/javascript">
        // <![CDATA[
        MODx.onSnipFormRender = "'.$this->onSnipFormRender.'";
        Ext.onReady(function() {
            MODx.load({
                xtype: "modx-page-snippet-update"
                ,id: "'.$this->snippetArray['id'].'"
                ,record: '.$this->modx->toJSON($this->snippetArray).'
            });
        });
        // ]]>
        </script>
');
```

2021-02-17 15:37 UTC, Jako commented
If quickedit of those elements still works, I would not merge this.

2021-02-17 15:38 UTC, theboxer commented
Quick edit works, because it doesn't load data through controller, but directly via XHR request. But that doesn't mean that blank page is a correct state :), even though  you can go back in history and use quick edit to fix it.

2021-02-17 15:44 UTC, Jako commented
For me it would be better to not allow those invalid tags during saving the element and/or create a FAQ entry with:
Blank page on editing, try quickedit and remove `<script><!--`

2021-02-17 16:10 UTC, Ruslan-Aleev commented
Thanks for your participation! Interesting solution :)
I would merge it if this fix doesn't add bugs.

2021-02-17 16:19 UTC, Jako commented
Yes, thats the issue. You can't be sure, that it does not create a bug. It closes something that in most cases does not have to be closed.

2021-02-17 16:22 UTC, theboxer commented
It's not closing anything real, it's adding a string `"-->"` to the JSON data :) It probably just tricks the browser

2021-02-17 18:39 UTC, JoshuaLuckers commented
> It's not closing anything real, it's adding a string `"-->"` to the JSON data :) It probably just tricks the browser

The text inside the HTML comment must not start with the string ">", nor start with the string "->", nor contain the strings "<!--", "-->", or "--!>", nor end with the string "<!-".


Source: https://html.spec.whatwg.org/multipage/syntax.html#comments

2021-02-18 08:00 UTC, JoshuaLuckers commented
I agree with @Jako.

2021-02-18 09:52 UTC, JoshuaLuckers commented
At first I agreed with @Jako but then I looked into the details, it doesn't add any data to the chunk itself. It ads a new property `__fix_for_15222` with the value `-->` to the JSON.

That looks harmless to me. But still an interesting browser bug/feature. 

This is the generated javascript:
```javascript
// <![CDATA[
Ext.onReady(function() {
    MODx.load({
        xtype: "modx-page-chunk-update"
        ,chunk: "1"
        ,record: {"id":1,"source":1,"property_preprocess":false,"name":"TestChunk","description":"","editor_type":0,"category":0,"cache_type":0,"snippet":"<script><!-- \n\nThis is a test that breaks without this fix","locked":false,"properties":[],"static":false,"static_file":"","content":"<script><!-- \n\nThis is a test that breaks without this fix","__fix_for_15222":"-->","openTo":"\/"}
    });
});
MODx.onChunkFormRender = "";
MODx.perm.tree_show_element_ids = 1;
MODx.perm.unlock_element_properties = 1;
// ]]>
```

2021-02-18 13:55 UTC, Jako commented
@JoshuaLuckers Thanks for the clarification. It looks a bit like this browser issue could be misused to create a blank page everywhere. Can't the code be changed to load the record value by XHR?

2021-02-24 11:08 UTC, JoshuaLuckers commented
> @JoshuaLuckers Thanks for the clarification. It looks a bit like this browser issue could be misused to create a blank page everywhere. Can't the code be changed to load the record value by XHR?

I don't think it's that big of an issue to change the way we load our values everywhere this particular input will trigger a parsing error in the browser. 
As soon as the output contains two script tags with the comment open elements the browser will show an empty page. This also includes the front-end. 

If you edit a resource (without rich text) and use the example code as value it will also break the manager and front-end page.

2021-02-24 11:08 UTC, JoshuaLuckers approved these changes

2021-02-28 18:16 UTC, Jako approved these changes

2021-02-28 18:48 UTC, Mark-H requested changes
Sorry, but this is so hacky.. can't this be added into the script tags instead of whatever array may be encoded to JSON?

2021-02-28 19:00 UTC, Mark-H commented
Maybe something like this in the addHtml?

```
// <![CDATA[ <!--

// --> ]]> 
```

2021-02-28 19:48 UTC, sottwell commented
It already is https://github.com/modxcms/revolution/pull/15395#issuecomment-780636392

2021-02-28 19:52 UTC, Jako commented
No, Mark wants to insert additional html comments inside of the CDATA section.

2021-02-28 21:33 UTC, theboxer commented
@Mark-H https://github.com/modxcms/revolution/pull/15395#issuecomment-780636392

2021-03-02 09:45 UTC, JoshuaLuckers commented
> Maybe something like this in the addHtml?
> 
> ```
> // <![CDATA[ <!--
> 
> // --> ]]> 
> ```

That means we can't add any HTML comments using `addHtml`. Nested comments are not possible and will probably break the parser.

After thinking about it, the current solution will also break parsers or cause unintended behavior since the browser will still parse the JSON as text and end any HTML comment that was started when encountering the `-->` added in the JSON string.

I hope it makes sense what I try to say here haha.

2021-10-12 16:20 UTC, theboxer commented
@JoshuaLuckers no, the proposed solution doesn't break the parser. The JSON is valid, it's not closing not-existing comment. Like I mentioned, it seems to only trick the browser to render. I'm fine closing the PR as it really is a weird & hacky solution.

2022-01-18 13:19 UTC, theboxer commented
I'm going to close this one, it's a hacky solution and didn't gain enough support :)

2022-01-18 13:19 UTC, closed without merging