Updating url in system setting base_help_url
modxcms/revolution pull request #15411
Opened 2021-02-24 07:29 UTC by Ibochkarev

### What does it do?
Updating url in system setting `base_help_url`

### Why is it needed?
Fixes invalid address error when navigating

### Related issue(s)/PR(s)
NA

2021-02-24 10:44 UTC, JoshuaLuckers requested changes

2021-02-24 10:44 UTC, JoshuaLuckers commented on setup/includes/upgrades/common/3.0.0-update-base_help_url.php
> +));
```suggestion
use MODX\Revolution\modSystemSetting;

/** @var modSystemSetting $base_help_url */
$base_help_url = $modx->getObject(modSystemSetting::class, [
    'key' => 'base_help_url',
    'value' => '//docs.modx.com/display/revolution20/',
]);
```

2021-03-07 07:25 UTC, Ibochkarev commented
Related https://github.com/modxorg/Docs/commit/9d4c72545ba38d51b2d01199d7eb46f1dd911e24

2021-03-07 07:51 UTC, JoshuaLuckers approved these changes

2021-03-07 14:18 UTC, Jako approved these changes

2021-03-09 10:43 UTC, Ibochkarev commented on _build/data/transport.core.system_settings.php
> +  'value' => '//docs.modx.com/3.x/en/index',
@Mark-H Please see if there will be any errors when you click on the link

2021-03-09 16:29 UTC, merged