Removed http:// from empty weblink field on resource create form. Issue #15392
modxcms/revolution pull request #15422
Opened 2021-03-02 04:54 UTC by digitalpenguin

Removed http:// from empty weblink field on resource create form. Updated weblink_help lexicon entry to be more descriptive.

### What does it do?
Removed the default protocol value of `http://` on the create weblink resource form.

### Why is it needed?
Discussed in issue #15392 it's outdated now that everything should be https:// and is more useful blank.

### How to test
Use the tree context menu to create a new weblink.

### Related issue(s)/PR(s)
#15392

2021-03-02 10:12 UTC, JoshuaLuckers requested changes
Thanks for taking time to submit this PR! I have one small request:
The default value in the "quick create resource" functionality is also set to `http://`. 
https://github.com/modxcms/revolution/blob/e393cb36042c28f8979741101b3bd29c351be68a/manager/assets/modext/widgets/resource/modx.tree.resource.js#L1053 

If you would be so kind to change it there as well that would be great!

2021-03-02 11:02 UTC, digitalpenguin commented
> Thanks for taking time to submit this PR! I have one small request:
> The default value in the "quick create resource" functionality is also set to `http://`.
> 
> https://github.com/modxcms/revolution/blob/e393cb36042c28f8979741101b3bd29c351be68a/manager/assets/modext/widgets/resource/modx.tree.resource.js#L1053
> 
> If you would be so kind to change it there as well that would be great!

Sure thing - I'll get that added tomorrow!

2021-03-03 03:44 UTC, digitalpenguin commented
Should be good to go. Let me know if anything else needs changing.

2021-03-05 13:57 UTC, JoshuaLuckers approved these changes

2021-03-07 14:13 UTC, Jako approved these changes

2021-03-09 17:00 UTC, merged