Bug 15129
modxcms/revolution pull request #15460
Opened 2021-03-05 10:33 UTC by wax100

### What does it do?
fix downloding file name (earlier was index)
fix upload file window (destroy and create new instead of creating, creating, creating...)
fix deleting more then 1 file

### Related issue(s)/PR(s)
issue #15129

2021-03-05 10:37 UTC, Ibochkarev requested changes

2021-03-05 10:37 UTC, Ibochkarev commented on core/src/Revolution/Processors/Browser/File/Download.php
> +                $name = $data['basename'];//preg_replace('#[^\w-.]#ui', '_', $data['basename']);
```suggestion
                $name = $data['basename'];
```

2021-03-05 10:46 UTC, Mark-H commented
Can you please try to use descriptive descriptions in commit messages and PRs? What it changes is much more important than the related issue number ;)

2021-03-05 11:46 UTC, Ibochkarev approved these changes
https://user-images.githubusercontent.com/2138260/110111547-b3ee1800-7dda-11eb-99dd-bcc979765888.mp4

2021-03-05 11:56 UTC, Ruslan-Aleev commented
If you delete a file and immediately load another (or create a file / category), the file manager breaks down.

![file_del](https://user-images.githubusercontent.com/12523676/110112546-f277d880-7dc2-11eb-91ef-8f7e9d3c3e82.gif)

There are errors in the browser console:

```
Uncaught TypeError: Cannot read property 'getSelectionModel' of null
    at Ext.tree.AsyncTreeNode.removeChild (ext-all.js:21)
    at MODx.tree.TreeLoader.load (ext-all.js:21)
    at MODx.tree.Directory.refreshActiveNode (modx.tree.js:712)
    at MODx.tree.Directory.fn (modx.tree.directory.js:589)
    at y.Event.fire (ext-all.js:21)
    at MODx.window.CreateDirectory.fireEvent (ext-all.js:21)
    at MODx.window.CreateDirectory.success (modx.window.js:249)
    at Object.callback (ext-all.js:21)
    at constructor.afterAction (ext-all.js:21)
    at Ext.form.Action.Submit.success (ext-all.js:21)
```

2021-03-05 11:58 UTC, Ibochkarev commented
> If you delete a file and immediately load another (or create a file / category), the file manager breaks down.
> 
> ![file_del](https://user-images.githubusercontent.com/12523676/110112546-f277d880-7dc2-11eb-91ef-8f7e9d3c3e82.gif)
> 
> There are errors in the browser console:
> 
> ```
> Uncaught TypeError: Cannot read property 'getSelectionModel' of null
>     at Ext.tree.AsyncTreeNode.removeChild (ext-all.js:21)
>     at MODx.tree.TreeLoader.load (ext-all.js:21)
>     at MODx.tree.Directory.refreshActiveNode (modx.tree.js:712)
>     at MODx.tree.Directory.fn (modx.tree.directory.js:589)
>     at y.Event.fire (ext-all.js:21)
>     at MODx.window.CreateDirectory.fireEvent (ext-all.js:21)
>     at MODx.window.CreateDirectory.success (modx.window.js:249)
>     at Object.callback (ext-all.js:21)
>     at constructor.afterAction (ext-all.js:21)
>     at Ext.form.Action.Submit.success (ext-all.js:21)
> ```

I confirm. Didn't look

2021-03-15 06:58 UTC, Ibochkarev requested changes
You must remove the commit Merge branch 'bug-15129' of https://github.com/wax100/revolution into ...

2021-03-27 13:58 UTC, Ruslan-Aleev commented
@wax100 The error with uploading a file after deleting is no longer reproducible (https://github.com/modxcms/revolution/pull/15460#issuecomment-791373650), but persists when trying to create a category after deleting a file:

![media_bug_cat](https://user-images.githubusercontent.com/12523676/112723036-a8939580-8f1d-11eb-8464-5eb53e5398cf.gif)

2021-10-07 12:18 UTC, theboxer commented
@wax100 any plans on resolving the issues reported here so we can merge?

2022-02-17 19:33 UTC, closed without merging