Skip files with specified extensions
modxcms/revolution pull request #15479
Opened 2021-03-05 14:15 UTC by wax100

### What does it do?
Do not show files with extensions that are set in **skipExtensions** property in media Source

### Why is it needed?
If You  automatically convert files to webp on you server You can get such problem: 
![Screenshot_8](https://user-images.githubusercontent.com/4846064/110126065-16441a00-7dd5-11eb-9476-f154e65badbf.jpg)

And with this setting You will see this
![Screenshot_9](https://user-images.githubusercontent.com/4846064/110126907-fd883400-7dd5-11eb-8bc6-daca3feec7d6.jpg)

### How to test
Upload .webp to mediabrowser and set skipExtensions to 'webp'

2021-03-09 09:09 UTC, meshkov commented
disabling the webp is not a solution to the problem with the webp format

2021-03-09 09:56 UTC, Ruslan-Aleev commented
@meshkov As I understand it, this PR solves the problem of SKIPING EXTENSIONS, and webp is indicated here as an example.
The webp display problem is not relevant to this PR.

2021-03-09 10:19 UTC, wax100 commented
Yes, U can use or not use this setting

2021-03-09 12:43 UTC, JoshuaLuckers requested changes
I think `skipExtensions` is a good addition. Some notes:
- Skipping `webp` by default isn't something I prefer.
- We should add `skipExtensions` to `modFTPMediaSource` and `modS3MediaSource`.

2021-03-09 12:43 UTC, JoshuaLuckers commented on core/src/Revolution/Sources/modFileMediaSource.php
> +                'value' => 'webp',
This will make media sources hide `webp` files by default.

2021-03-16 08:18 UTC, JoshuaLuckers approved these changes

2021-03-17 05:11 UTC, Ibochkarev requested changes
![изображение](https://user-images.githubusercontent.com/2138260/111418203-6eeaaf80-8711-11eb-87f1-867391e78e2d.png)

It is necessary to add a lexicon to describe the parameter

2021-03-21 13:08 UTC, alroniks requested changes, later dismissed
I agree that sometimes it may be useful to skip just one extension instead of enumerating all allowed in `allowedFileTypes`, but it all becomes too complicated in case several rules applied. Also, there is a `skipFiles` setting, which can be improved and empowered to handle the same request about skipping.

But my main change request is to make setting name correlating with `allowedFileTypes`, for example, name it as `deniedFileTypes` or `skippedFileTypes`.

2021-03-21 13:08 UTC, alroniks commented on core/src/Revolution/Sources/modMediaSource.php
> +        if (is_string($skipExtensions)) {
Options always stored as strings, so no need to check the type here. And after the following condition can be simplified.

2021-03-30 06:21 UTC, wax100 commented on core/src/Revolution/Sources/modMediaSource.php
> +        if (is_string($skipExtensions)) {
Denied means that You can't upload it - but it is just skipped (hided)

2021-03-30 07:17 UTC, alroniks commented on core/src/Revolution/Sources/modMediaSource.php
> +        if (is_string($skipExtensions)) {
I agree with denied, but still prefer FileTypes against Extensions, because allowedFileTypes also stores extensions, let's do it in a consistent way.

2021-03-30 07:37 UTC, alroniks commented on core/src/Revolution/Sources/modMediaSource.php
> +        return $skipExtensions;
```suggestion
        return !empty($skipExtensions) ? explode(',', $skipExtensions) : [];
```

And remove `if` statement.

2022-10-18 04:28 UTC, smg6511 commented
Folks - I was taking a look at this and am curious: What is the use-case for allowing certain file types to be _uploaded_, but then have some subset _hidden_ by a skip rule? Or conversely _shown_ by an allow rule? Why would you not just create Sources with corresponding ACLs to control visibility (and ability to upload) for different users/groups? I guess what I'm getting at is if one needs all these settings in a Media Source, perhaps it points to possible design flaws on the end-user/developer side. 

IMO there's a lot of needlessly confusing behavior and ambiguous naming of settings going on here (not referring @wax100's submission here, but the Media Source and file handling area of modx in general).

2023-01-30 19:59 UTC, Mark-H approved these changes

2023-01-30 20:07 UTC, opengeek commented
Can we resolve any unresolved conversations before marking them as ready-for-merging?

2023-01-30 20:33 UTC, Mark-H commented on core/src/Revolution/Sources/modMediaSource.php
> +        if (is_string($skipExtensions)) {
Is this naming important to resolve in your opinion @alroniks?

2023-01-30 20:58 UTC, alroniks commented on core/src/Revolution/Sources/modMediaSource.php
> +        if (is_string($skipExtensions)) {
I still prefer to use proper names. But in this case, I am OK.

2023-01-30 21:10 UTC, merged