Hide dependent forms until items are not selected in tree
modxcms/revolution pull request #15478
Opened 2021-03-05 13:39 UTC by Ruslan-Aleev

### What does it do?
Hide dependent forms until items are not selected in tree.

You can, for example, set value in a property, try to save, and only then understand that you must first select an element in the tree - which is very confusing.

Before:
![forms_hide](https://user-images.githubusercontent.com/12523676/110122736-0b878600-7dd1-11eb-9ab0-f87594e556cd.gif)

After:
![forms_hide_2](https://user-images.githubusercontent.com/12523676/110122899-4984aa00-7dd1-11eb-87c5-2b1b1ec85076.gif)

### Why is it needed?
UI/UX improvement

### Related issue(s)/PR(s)
Logically related to https://github.com/modxcms/revolution/issues/10518

2021-03-09 07:47 UTC, JoshuaLuckers commented
Wouldn't it make more sense to disable the form when nothing is selected so the user understands there is something to edit in the window? If you hide it, you also hide the functionality.

2021-03-09 07:51 UTC, Ruslan-Aleev commented
Yes, it makes sense. If you tell me how to do this, I will correct it :) I did the same as in the "User groups" tree.

2021-03-09 13:02 UTC, JoshuaLuckers commented on manager/assets/modext/widgets/element/modx.panel.property.set.js
> +    Ext.getCmp('right-column').hide();
```suggestion
    Ext.getCmp('right-column').disable();
```

2021-03-09 13:02 UTC, JoshuaLuckers commented on manager/assets/modext/widgets/element/modx.panel.property.set.js
> +        Ext.getCmp('right-column').show();
```suggestion
        Ext.getCmp('right-column').enable();
```

2021-03-09 13:02 UTC, JoshuaLuckers commented on manager/assets/modext/widgets/security/modx.panel.user.js
> +    Ext.getCmp('modx-extended-form').hide();
```suggestion
    Ext.getCmp('modx-extended-form').disable();
```

2021-03-09 13:02 UTC, JoshuaLuckers commented on manager/assets/modext/widgets/security/modx.panel.user.js
> +                                Ext.getCmp('modx-extended-form').show();
```suggestion
                                Ext.getCmp('modx-extended-form').enable();
```

2021-03-09 13:02 UTC, JoshuaLuckers commented on manager/assets/modext/widgets/system/modx.panel.dashboard.widget.js
> +    Ext.getCmp('modx-extended-form').hide();
```suggestion
    Ext.getCmp('modx-extended-form').disable();
```

2021-03-09 13:02 UTC, JoshuaLuckers commented on manager/assets/modext/widgets/system/modx.panel.dashboard.widget.js
> +                            Ext.getCmp('modx-extended-form').show();
```suggestion
                            Ext.getCmp('modx-extended-form').enable();
```

2021-03-09 14:29 UTC, Ruslan-Aleev commented
@JoshuaLuckers That's a lot better. Thanks!

![forms_d](https://user-images.githubusercontent.com/12523676/110485710-faa28180-80fc-11eb-81ec-509f269e5797.gif)

2021-03-09 14:32 UTC, JoshuaLuckers approved these changes

2021-03-15 06:53 UTC, Ibochkarev approved these changes

2021-03-16 22:36 UTC, alroniks requested changes
On the widget page, it fails with the following error:

```
modx.panel.dashboard.widget.js:10 Uncaught TypeError: Cannot read property 'disable' of undefined
    at new MODx.panel.DashboardWidget (modx.panel.dashboard.widget.js:10)
    at Object.create (ext-all.js:21)
    at MODx.load (modx.js?v=36a40c61:86)
    at MODx.page.UpdateDashboardWidget._loadComponents (modx.component.js:68)
    at MODx.page.UpdateDashboardWidget.MODx.Component [as constructor] (modx.component.js:10)
    at new MODx.page.UpdateDashboardWidget (update.js:36)
    at Object.create (ext-all.js:21)
    at MODx.load (modx.js?v=36a40c61:86)
    at ?a=system/dashboards/widget/update&id=6:27
    at ext-all.js:21
```

2021-03-28 20:13 UTC, alroniks approved these changes

2021-03-28 20:16 UTC, alroniks commented
@Ruslan-Aleev Works fine, but what I found and I guess it can be improved in a new PR. It actual for user and dashboard widget code.
When I selected a value it removed disabled flag from the form, but when I selected, for example, container (category) it stays on the previous value, but if it loses focus, maybe it makes sense to remove values from the form, clean it and make disable again.

2021-03-28 20:20 UTC, merged