Corrected untranslated lines
modxcms/revolution pull request #15537
Opened 2021-03-11 15:35 UTC by Ruslan-Aleev

### What does it do?
Corrected untranslated lines:
- Removed untranslated description from Base Template
The Base Template description says "Template", but it is not useful.
- Added lexicon for `site_unavailable_message` setting
The lexicon will be replaced with the correct string depending on the `cultureKey` setting.

We can also display other settings through lexicons, for example, `phpthumb_nohotlink_text_message`, but these are technical messages and translation is not particularly needed.

### Why is it needed?
For unification in translation

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/6092

2021-03-19 03:25 UTC, Ibochkarev approved these changes
LGTM 👍 

![изображение](https://user-images.githubusercontent.com/2138260/111727294-d41ade00-8894-11eb-990e-d92090f93aeb.png)

![изображение](https://user-images.githubusercontent.com/2138260/111727379-fca2d800-8894-11eb-9dc1-032886549f82.png)

2021-03-19 07:55 UTC, JoshuaLuckers approved these changes

2021-03-21 12:54 UTC, alroniks commented
Technically it OK, but what I see, that having a system setting with just lexicon entry does not make a lot of sense. 
I would like to remove such a setting at all and replace it with lexicon directly. 
I can imagine that somebody can use the different messages for different contexts or maybe even user groups or users (as the system setting allows), but it also does not make a lot of sense. This message is a technical notice that something wrong with a site and should be nothing more.

What do you think @opengeek and @Mark-H. Maybe I missed important use cases and I am wrong.

2021-04-05 16:06 UTC, opengeek requested changes
I'd prefer not to automatically update this setting. Existing users may have customized this setting already and this would undo their customization. New users can have the lexicon value on installation as a default, but changing existing values should not be done, in my opinion.

2021-04-06 12:06 UTC, Ruslan-Aleev commented
@opengeek Yes, I agree. I corrected the PR.

2021-04-09 06:17 UTC, alroniks approved these changes

2021-04-09 06:21 UTC, merged