Added checks for pages specified in 'error_page' and 'site_unavailable_page' settings
modxcms/revolution pull request #15579
Opened 2021-03-23 12:19 UTC by Ruslan-Aleev

### What does it do?
The resource that is specified in the system settings as `site_start` cannot be unpublished from the context menu in tree - an error will appear. But at the same time, the editing of this resource can be unpublished trough chekbox in resource form.

The resources specified in `error_page` and `site_unavailable_page` could be deleted / unpublished both through the tree and through the resource form.

**In general, I added checks for these resources.**

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/14509

2021-03-23 12:41 UTC, Ruslan-Aleev commented
In the process of working on PR, strange key names are annoying! :)

I would like to have more logical names:
```
site_index (instead of site_start);
site_404 (instead of error_page);
site_503 (instead of site_unavailable_page).
```

2021-03-23 13:22 UTC, sottwell commented
What about resource fields and database field names, like "introtext" and "summary"? I nagged about that one in the beginning until (introtext) was added next to the field label.

2021-03-23 13:34 UTC, Ruslan-Aleev commented
@sottwell Yes, it looks strange too.

2021-04-08 21:07 UTC, Ibochkarev approved these changes
![изображение](https://user-images.githubusercontent.com/2138260/114096233-46a13b80-98e0-11eb-9caa-6a2bfffefbc8.png)

![изображение](https://user-images.githubusercontent.com/2138260/114096312-5f115600-98e0-11eb-898d-a29bcb663b02.png)

![изображение](https://user-images.githubusercontent.com/2138260/114096501-997af300-98e0-11eb-839e-969a8b79baf3.png)

![изображение](https://user-images.githubusercontent.com/2138260/114096526-a697e200-98e0-11eb-8d27-4746973573bb.png)

2021-09-30 14:47 UTC, theboxer requested changes

2021-09-30 14:47 UTC, theboxer commented on core/src/Revolution/Processors/Resource/Update.php
> +        $result = true;
Unnecessary variable

2021-09-30 14:47 UTC, theboxer commented on core/src/Revolution/Processors/Resource/Update.php
> +        return $result;
Change to `return true;`

2021-09-30 14:47 UTC, theboxer commented on core/src/Revolution/Processors/Resource/Update.php
> +            $result = $this->modx->lexicon('resource_err_delete_sitestart');
Follow return early pattern.

replace with `return $this->modx...`

2021-09-30 14:47 UTC, theboxer commented on core/src/Revolution/Processors/Resource/Update.php
> +        } else if ($isSiteStart && $published == 0) {
Replace all `else if` with a regular `if` and follow return early pattern.

`return $this->modx...`

2021-09-30 14:47 UTC, theboxer commented on core/src/Revolution/Processors/Resource/Delete.php
> +    }
This calls for some abstraction as you are redefining these checks 3 times.

2021-11-04 12:52 UTC, Ruslan-Aleev commented
@theboxer Any thoughts?

2022-01-06 15:19 UTC, Ruslan-Aleev commented
@theboxer Please check PR.

2022-01-07 12:30 UTC, theboxer approved these changes

2022-01-07 12:30 UTC, theboxer commented
Seems good to me, thanks!

2022-01-10 19:32 UTC, opengeek approved these changes

2022-01-10 19:32 UTC, merged