Minor update styles packages manager
modxcms/revolution pull request #15588
Opened 2021-03-24 15:17 UTC by Ibochkarev

### What does it do?
Updated styles for package manager

### Why is it needed?
Improves the visual perception of text information

Before:
![Снимок экрана 2021-03-24 в 21 06 16](https://user-images.githubusercontent.com/2138260/112335290-4ef55600-8ce6-11eb-8390-6e406a05d24b.png)

After:
![Снимок экрана 2021-03-24 в 21 09 52](https://user-images.githubusercontent.com/2138260/112335304-51f04680-8ce6-11eb-8a34-972689d0fb0f.png)

### How to test
Rebuild assets

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/15564

2021-03-29 20:53 UTC, alroniks approved these changes

2021-03-31 22:19 UTC, rthrash requested changes
I think we need to look at slightly more contrast. I love the way it looks, so great job, but some with lesser vision may struggle to read it.

2021-03-31 22:19 UTC, rthrash commented on _build/templates/default/sass/_package-management.scss
> +    color: #808080;
For normal text, this doesn't pass accessibility, see: https://webaim.org/resources/contrastchecker/?fcolor=808080&bcolor=FFFFFF

To get it to pass would require going to #595959 for the text, and that would also probably need a darker color for the headline for visual balance.

2021-05-29 14:21 UTC, Ruslan-Aleev approved these changes

2021-10-12 09:53 UTC, theboxer commented
@Ibochkarev any plans on updating this PR with the requested changes?

2021-10-12 10:36 UTC, Ibochkarev commented
> @Ibochkarev any plans on updating this PR with the requested changes?

I can offer to accept it as it is (since the branch was deleted from me and I cannot make changes), and then make these changes in the next request.

2021-10-12 10:45 UTC, theboxer commented
@Ibochkarev you can either restore the branch following this tutorial: https://garrytrinder.github.io/2020/05/recover-pr-after-accidentally-deleting-source-branch
or if you have [github cli](https://cli.github.com/) tool (highly recommended), you can checkout to the PR branch by `gh pr checkout 15588` and try to push it to your repo
or cherry pick commits from this PR to a new branch and create a new PR
or create a new branch and copy & paste changes

I don't think that merging unfinished PR and then waiting for a new one to finish the work is a good approach.

2021-10-24 06:19 UTC, Ibochkarev commented
Closed in favor of #15862

2021-10-24 06:19 UTC, closed without merging

2021-10-24 06:28 UTC, Ibochkarev commented
> @Ibochkarev you can either restore the branch following this tutorial: https://garrytrinder.github.io/2020/05/recover-pr-after-accidentally-deleting-source-branch or if you have [github cli](https://cli.github.com/) tool (highly recommended), you can checkout to the PR branch by `gh pr checkout 15588` and try to push it to your repo or cherry pick commits from this PR to a new branch and create a new PR or create a new branch and copy & paste changes
> 
> I don't think that merging unfinished PR and then waiting for a new one to finish the work is a good approach.

@theboxer 

``` shell
➜  revolution git:(3.x) gh pr checkout 15588
GraphQL error: Could not resolve to a PullRequest with the number of 15588.
```

``` shell
➜  revolution git:(3.x) git checkout -b package-browser e06e917f429ace4442d24a042b1301fed5d4fa3f
fatal: there is no such link in the village: e06e917f429ace4442d24a042b1301fed5d4fa3f
```