Increases the basic required version of php
modxcms/revolution pull request #15589
Opened 2021-03-25 04:19 UTC by Ibochkarev

### What does it do?
Increases the basic required version of php

### Why is it needed?

https://docs.modx.com/3.x/en/getting-started/server-requirements

The documentation states that minimum version = 7.1. This fix upgrades the version to the required

### Related issue(s)/PR(s)
NA

2021-03-25 04:33 UTC, sergant210 commented
7.1 and 7.2 are not supported now. [Supported versions](https://www.php.net/supported-versions.php).

2021-03-25 05:52 UTC, Ibochkarev commented
> 7.1 and 7.2 are not supported now. [Supported versions](https://www.php.net/supported-versions.php).

I can change to 7.3 and remove the old version of php in the ci.yml, but this needs the approval of the integrators

2021-03-25 13:50 UTC, opengeek commented
We will not be removing support for 7.1/7.2 at this time. They are still in widespread use regardless of what the core PHP maintainers say.

2021-03-25 13:51 UTC, opengeek commented
This needs the check for 7.0 removed.

2021-03-25 13:52 UTC, opengeek requested changes
This needs the check for 7.0 removed.

2021-03-25 13:53 UTC, Ibochkarev commented
> This needs the check for 7.0 removed.

I will submit a commit with the 7.0 checkout removal in the Github action tests

2021-03-26 14:05 UTC, opengeek approved these changes

2021-03-26 14:06 UTC, merged

2021-03-26 17:28 UTC, JoshuaLuckers commented
Don't forget to change it here: https://github.com/modxcms/revolution/blob/0acc0d92fcea3fc97ab5692a8d3b55648fd6ef2c/setup/provisioner/requirements.php#L11

2021-03-26 17:42 UTC, opengeek commented
Why do we have all of this duplicated there?

2021-03-26 18:00 UTC, opengeek commented
What I mean to say is, I wonder if we can find a way to use the composer declarations in setup rather than duplicating it all.

2021-03-26 19:08 UTC, JoshuaLuckers commented
> What I mean to say is, I wonder if we can find a way to use the composer declarations in setup rather than duplicating it all.

Yes that would be great, but is the composer.json in the downloadable build?

2021-03-26 20:08 UTC, opengeek commented
> > What I mean to say is, I wonder if we can find a way to use the composer declarations in setup rather than duplicating it all.
> 
> Yes that would be great, but is the composer.json in the downloadable build?

It certainly should be.

2021-03-30 09:06 UTC, JoshuaLuckers commented
> > > What I mean to say is, I wonder if we can find a way to use the composer declarations in setup rather than duplicating it all.
> > 
> > 
> > Yes that would be great, but is the composer.json in the downloadable build?
> 
> It certainly should be.

I've downloaded the alpha-2 release from [modx.com/download](http://modx.com/download), composer.json is not included.