Fix incorrect version is displayed in the welcome window
modxcms/revolution pull request #15613
Opened 2021-03-30 15:17 UTC by Ibochkarev

### What does it do?
Fix incorrect version is displayed in the welcome window

### Why is it needed?
Fix path for preview the page in system settings

### How to test
Install clean build

### Related issue(s)/PR(s)
Resolves #15412

2021-03-30 19:40 UTC, alroniks approved these changes

2021-04-01 07:54 UTC, sergant210 approved these changes

2021-04-01 09:04 UTC, theboxer approved these changes

2021-04-01 10:18 UTC, alroniks commented
@Ibochkarev What about the upgrading script?

2021-04-01 10:19 UTC, Ibochkarev commented
> @Ibochkarev What about the upgrading script?

if you need it, I will do it without problems

2021-04-01 10:51 UTC, alroniks requested changes

2021-04-01 10:51 UTC, alroniks commented on setup/includes/upgrades/common/3.0.0-update-sys-setting_welcome_screen_url.php
> +$welcome_screen_url = $modx->getObject(modSystemSetting::class, [
Please, use PSR-12 for the new code.

2021-04-01 21:21 UTC, Ibochkarev commented on setup/includes/upgrades/common/3.0.0-update-sys-setting_welcome_screen_url.php
> +$welcome_screen_url = $modx->getObject(modSystemSetting::class, [
Done

2021-04-05 06:00 UTC, alroniks approved these changes

2021-04-05 15:54 UTC, merged