Added sorting by all fields in grids
modxcms/revolution pull request #15660
Opened 2021-04-09 08:38 UTC by Ruslan-Aleev

### What does it do?
Added sorting by all fields in grids.
In some grids, not all fields were sorted, which is inconvenient, this PR fixes this.

### Why is it needed?
UX improvement

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/12299

2021-04-09 08:42 UTC, Ibochkarev approved these changes

2021-04-11 15:57 UTC, Mark-H requested changes
I cannot review changing for 35 grids at once. There may be good reasons for columns to be not marked as sortable, for example it may not be an indexed column or it's a joined/dynamically added column in a processor that cannot be sorted directly. 

While I also don't want 35 individual PRs for this, this absolutely needs a thorough review of every single changed grid to avoid grids being broken if a certain column is clicked and I'm making it as needing changes to avoid it being quickly merged without such a thorough test.

2021-04-11 16:09 UTC, Mark-H commented
There's no need to close the PR, I just want to make sure this gets thoroughly reviewed and not merged on a whim. :)

2021-04-11 16:13 UTC, Ruslan-Aleev commented
To be honest, I thought that PR is not very useful :) Especially if after the merger, difficulties may arise, like:

> There may be good reasons for columns to be not marked as sortable, for example it may not be an indexed column or it's a joined/dynamically added column in a processor that cannot be sorted directly.

2021-10-12 13:42 UTC, theboxer requested changes
I'm not a huge fan by enabling sorting by `description` fields. I don't think it's useful. I didn't comment on those cause they don't break anything.

I have a strange feeling that you didn't test your own PR at all and just randomly submitted a bunch of changes. This is really not a way to go. While I really appreciate any contribution, submitting untested code is a waste of resources we have for reviews.

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/widgets/element/modx.grid.tv.security.js
> +        ,sortable: true
This doesn't work. Access is  computed property in the processor.

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/widgets/fc/modx.grid.fcprofile.js
> +            ,sortable: true
You can't sort by usergroups

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/widgets/resource/modx.panel.resource.schedule.js
> +            ,sortable: true
Adding `sortable` for columns in this grid will result on local sorting only (will sort only the visible page). The processor uses `mode` property to sort by either a publish or unpublish date. I'd vote for removing the sortable params from all columns here.

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/widgets/security/modx.grid.access.context.js
> +            ,sortable: true
Sorting in this grid is only local - for the current page. You could add `remoteSort: true` to enable remote sorting (if you do that, you can't sort by `principal_name`). If you decide not to add the `remoteSort`, I'd be for removing the sortable props from all columns.

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/widgets/security/modx.grid.access.policy.js
> +            ,sortable: true
You can't sort by this.

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/widgets/security/modx.grid.message.js
> +            ,sortable: true
Similar to others, this grid doesn't use remoteSort. If you decide to add it, you can't sort by Sender & Recipient (out of the box), otherwise remove the sortables.

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/widgets/security/modx.grid.role.js
> +            ,sortable: true
Grid is missing `remoteSort`

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/widgets/security/modx.grid.user.group.category.js
> +            ,sortable: true
Can't sort by authority_name

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/widgets/security/modx.grid.user.group.context.js
> +            ,sortable: true
You can't sort by authority_name.

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/widgets/security/modx.grid.user.group.js
> +            ,sortable: true
Sorting doesn't work in this grid at all.

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/widgets/security/modx.grid.user.group.namespace.js
> +            ,sortable: true
You can't sort by this.

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/widgets/security/modx.grid.user.group.resource.js
> +            ,sortable: true
You can't sort by this.

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/widgets/security/modx.grid.user.group.source.js
> +            ,sortable: true
You can't sort by this.

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/widgets/security/modx.grid.user.online.js
> +    config = config || {};
This whole grid is deprecated and not used anymore.

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/widgets/security/modx.grid.user.recent.resource.js
> +            ,sortable: true
Only local sorting, remove sortables.

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/widgets/source/modx.grid.source.access.js
> +            ,sortable: true
Sorting doesn't work in this grid at all.

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/widgets/source/modx.panel.sources.js
> +            ,sortable: true
Sorting doesn't work in this grid at all.

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/widgets/system/modx.grid.manager.log.js
> +            ,sortable: true
You can't sort by this column.

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/widgets/system/modx.grid.system.event.js
> +            ,sortable: true
Sort doesn't work here - missing remoteSort & is a grouping view

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/widgets/system/modx.panel.dashboard.widget.js
> +            ,sortable: true
Sorting doesn't work in this grid.

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/workspace/package.browser.panels.js
> +            ,sortable: true
Sorting is handled differently in this grid. Remove sortables.

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/workspace/package.grid.js
> +        ,fields: ['signature','name','version','release','created','updated','installed','state','workspace','provider','provider_name','disabled','source','attributes','readme','menu','install','tex
Sorting doesn't work in this grid, revert changes.

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/workspace/provider.grid.js
> +            ,sortable: true
Missing `remoteSort:true`

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/workspace/lexicon/lexicon.grid.js
> +            ,sortable: true
Only local sort

2021-10-12 13:42 UTC, theboxer commented on manager/assets/modext/workspace/package/package.versions.grid.js
> +        ,fields: ['signature','name','version','release','created','updated','installed','state','workspace','provider','provider_name','disabled','source','readme','menu']
Sorting doesn't work here, revert.

2021-10-12 14:26 UTC, Ruslan-Aleev commented
> I have a strange feeling that you didn't test your own PR at all and just randomly submitted a bunch of changes. This is really not a way to go.

I closed this PR, as a lot of things do not work in it and sorting is not very important. But @Mark-H opened this PR again, all questions to him :)

> While I really appreciate any contribution, submitting untested code is a waste of resources we have for reviews.

You can do it right, I'll be glad to test it.

2022-01-18 12:57 UTC, theboxer commented
Closing this one, seems like you're not going to fix the reported issues. Feel free to reopen with commits that will lead to a working PR.

2022-01-18 12:57 UTC, closed without merging