FIX update preview
modxcms/revolution pull request #15731
Opened 2021-05-29 20:01 UTC by tanzirev

Если выбранные изображения имеют одинаковые названия, но при этом это разные изображения, то превью таких изображений не обновляются на разных страницах, т.к. браузер кеширует прошлое изображение. 
(If the selected images have the same name, but they are different images, then the previews of such images are not updated on different pages, because the browser caches the previous image.)

2021-06-07 18:20 UTC, tanzirev commented
@cla-bot check

2021-06-26 07:49 UTC, JoshuaLuckers approved these changes

2021-06-26 07:51 UTC, Ibochkarev approved these changes

2021-06-29 09:45 UTC, Jako requested changes
If I understand the issue correctly, the preview for images with the same path and source is the same on different MODX sites.

I suggest using a hash of the MODX site_id instead of a random string. Then the thumbnail can be cached for the same site. Is this suitable?

2021-06-29 09:51 UTC, Ruslan-Aleev commented
As I understand it, here is about the fact that the cache of the old image is displayed in the manager when replacing the image with a new one, but with the same name. Those MODX site_id will not help with this issue.

2021-06-30 11:14 UTC, Jako commented
I have changed the code to use a file based hash value (if the file exist).

2021-06-30 11:17 UTC, Jako approved these changes

2021-07-01 06:47 UTC, JoshuaLuckers approved these changes

2021-09-16 19:31 UTC, merged