Fix modManagerLog MySQL > 5.7.8
modxcms/revolution pull request #15736
Opened 2021-06-16 14:48 UTC by catsmeatman

### What does it do?
Add right default value for datatime-type column in modx_manager_log table

### Why is it needed?
Beginning with MySQL > 5.7.8  added strict modes ERROR_FOR_DIVISION_BY_ZERO, NO_ZERO_DATE,  NO_ZERO_IN_DATE. Because datatime default value cannot be NULL and must be > '0000-00-00'.

### How to test
When setup modx In MySQL 5.7.8 not create index user_occurred at  modx_manager_log table.

Try to add index in console
`create index user_occurred ON modx_manager_log (user, occurred)`

Result
`ERROR 1067 (42000): Invalid default value for 'occurred'`

2021-06-26 07:42 UTC, JoshuaLuckers approved these changes

2021-07-28 10:03 UTC, Ibochkarev approved these changes

2021-07-29 09:19 UTC, Jako commented
There could be an update script to modify that table column for existing installations too.

2021-09-23 18:22 UTC, opengeek requested changes
This needs an update script to correct existing installations before being accepted.

2022-02-01 09:10 UTC, JoshuaLuckers commented
@catsmeatman would it be possible for you to create an upgrade script?

2022-02-01 10:17 UTC, catsmeatman commented
@JoshuaLuckers where can I read how to do this?

2022-02-01 17:50 UTC, Jako commented
This can be done like this: https://github.com/modxcms/revolution/blob/2.x/setup/includes/upgrades/mysql/2.0.4-pl.php

You have to create a file 2.8.4-pl.php with some ALTER TABLE code.

2022-02-17 07:37 UTC, catsmeatman commented
@Jako Thx, I'll do it this weekend

2022-04-15 11:22 UTC, Ibochkarev commented
@catsmeatman Please make the suggested edits @Jako

2024-02-10 11:45 UTC, Mark-H commented
As this PR has gone stale I've re-created it for 3.x in #16520.

2024-02-10 11:45 UTC, closed without merging

2024-02-16 22:10 UTC, rthrash commented
@Mark-H will you back port this for 2.8.7?

2024-02-16 22:56 UTC, opengeek commented
> @Mark-H will you back port this for 2.8.7?

@rthrash — I will handle it. I'm going to make some changes to the PR anyway.

2024-02-20 10:38 UTC, Jako commented
The following sql commands are working fine here to solve some similar issues. The date changes are not 100% correct but normally a date in 1970 does not exist in those columns in MODX.

```
UPDATE `modx_system_settings` SET `editedon` = "1970-01-02 00:00:00" WHERE `editedon` < "1970-03-01 00:00:00";
ALTER TABLE `modx_system_settings` CHANGE `editedon` `editedon` TIMESTAMP  NULL  DEFAULT NULL;
UPDATE `modx_system_settings` SET `editedon` = NULL WHERE `editedon` < "1970-03-02 00:00:00";
UPDATE `modx_context_setting` SET `editedon` = "1970-01-02 00:00:00" WHERE `editedon` < "1970-03-01 00:00:00";
ALTER TABLE `modx_context_setting` CHANGE `editedon` `editedon` TIMESTAMP  NULL  DEFAULT NULL;
UPDATE `modx_context_setting` SET `editedon` = NULL WHERE `editedon` < "1970-03-02 00:00:00";
```