[port to 3.x] Changed LOG_LEVEL for cache errors
modxcms/revolution pull request #15753
Opened 2021-06-24 09:07 UTC by Ruslan-Aleev

### What does it do?
Same as in https://github.com/modxcms/revolution/pull/15532, but for 3.x branch

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/pull/15532

2021-06-25 10:12 UTC, Ibochkarev approved these changes

2021-06-30 10:01 UTC, Ibochkarev requested changes

2021-06-30 10:01 UTC, Ibochkarev commented on core/src/Revolution/modCacheManager.php
> +                    'Could not retrieve data to cache for resource ' . $obj->get('id'));
```suggestion
                    'Could not retrieve data to cache for resource ' . $obj->get('id')
                );
```

2021-06-30 10:01 UTC, Ibochkarev commented on core/src/Revolution/modCacheManager.php
>                  $this->modx->log(modX::LOG_LEVEL_ERROR,
```suggestion
                $this->modx->log(
                    modX::LOG_LEVEL_ERROR,
```

2021-06-30 10:56 UTC, Ibochkarev approved these changes

2021-07-09 14:37 UTC, JoshuaLuckers approved these changes

2021-07-14 16:03 UTC, merged