[port to 3.x] Fixed display of image in TV through hash
modxcms/revolution pull request #15775
Opened 2021-07-29 13:00 UTC by Ruslan-Aleev

### What does it do?
Same as in https://github.com/modxcms/revolution/pull/15731, but for 3.x branch

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/pull/15731

2021-07-29 13:31 UTC, Ibochkarev requested changes

2021-07-29 13:31 UTC, Ibochkarev commented on core/src/Revolution/Processors/Element/TemplateVar/Renders/mgr/input/image.class.php
> +    public function process($value, array $params = []) {
```suggestion
    public function process($value, array $params = [])
    {
```

2021-08-26 13:48 UTC, JoshuaLuckers approved these changes

2021-08-28 11:35 UTC, Ibochkarev approved these changes

2021-08-30 21:22 UTC, Jako commented
This has to be added too: https://github.com/tanzirev/revolution/commit/aae1ea2329de2712abfb4010afe5e86042e1a11a

2021-09-16 19:32 UTC, merged