Fixing issue with folder names and cleaning up CS errors
modxcms/revolution pull request #15787
Opened 2021-08-04 21:58 UTC by matdave

### What does it do?
Allows special characters in folder names.

### Why is it needed?
ExtJs was having an issue when utilizing special characters, causing the user to be unable to edit a file or folder. 

Additionally added some logic optimization suggestions from CodeSniffer

### How to test
I created a folder named `umlaute (äöü)` and was unable to interact with it until applying the changes. 

### Related issue(s)/PR(s)
Issue #15659

2021-08-08 18:17 UTC, Ibochkarev commented
@cla-bot check

2021-08-26 13:40 UTC, Mark-H commented
Given the actual change is a few lines vs hundreds of lines of code style changes.... not doing that together would've been much more useful ;)

2021-10-07 14:44 UTC, theboxer approved these changes

2021-10-22 22:06 UTC, Ibochkarev approved these changes
Tested. This fix solves the specified problem

2021-11-11 16:29 UTC, opengeek commented
@matdave — has this also been addressed for 3.x?

2021-11-12 19:23 UTC, matdave commented
> @matdave — has this also been addressed for 3.x?

yes

2021-11-12 19:35 UTC, opengeek commented
> > @matdave — has this also been addressed for 3.x?
> 
> yes

Ummm, could you be more specific as to where and when this has been addressed for 3.x? Sigh…

2021-11-22 22:55 UTC, matdave commented
> > > @matdave — has this also been addressed for 3.x?
> > 
> > 
> > yes
> 
> Ummm, could you be more specific as to where and when this has been addressed for 3.x? Sigh…

3.x uses the FlySystem, I'm not sure exactly when but at some point someone added the same `rawurlencode` around the "id" parameter. That is what I ported to 2.x in this update.

2021-11-23 01:54 UTC, opengeek requested changes
There seem to be too many changes besides the folder name here for me to accept this as is. If you could, please undo everything except the folder name change and update the PR.

2021-11-23 01:54 UTC, opengeek commented on core/model/modx/sources/mods3mediasource.class.php
> +            'image' => in_array($fileExtension, $imageExtensions, true),
This is a non-trivial change.

2022-02-01 09:11 UTC, JoshuaLuckers commented
@matdave would it be possible for you to address the change request?

2022-02-01 13:52 UTC, rthrash commented
Mat won't be back until next week, FYI.

2022-02-21 21:45 UTC, closed without merging