Form customization front end fixes/improvements
modxcms/revolution pull request #15836
Opened 2021-10-14 04:29 UTC by smg6511

### What does it do?
Reworks the methods responsible for moving and changing field/tab visibility and labelling. Code optimizations were made and method documentation was added.

### Why is it needed?
Most of these methods were written to receive/process serialized/array data, but there appears to be no reason (any longer at least) to keep them that way—especially given that problems have arisen such as the one referenced by this PR. The changes allow for the use of commas in labels and provides simplification and clarification of the relevant code.

### How to test
Clear your caches and remember to run `grunt build` within the __build/templates/default_ directory to compile the changes into the main js file. Create one or two test TVs, then create a Form Customization profile with at least one rule. Within your rule(s), experiment with re-labelling and hiding various resource fields along with your test TVs. Also create a new tab in Regions tab and verify that assigning your TVs to that tab (or the standard regions) works as expected.

### Related issue(s)/PR(s)
Resolves #15357.

2021-10-14 04:54 UTC, smg6511 commented
REVIEWERS: Note that the unit test for this class will need to be changed for this PR to pass. I'm just not sure _who_ should do that. Basically, the parameters given that are formatted as an array need to be changed to a string. Please advise.

2021-10-14 05:07 UTC, Ibochkarev commented
@smg6511 Please correct errors for passing tests

2021-10-14 14:36 UTC, smg6511 commented
@Ibochkarev OK, the unit test is fixed.

2021-10-15 15:29 UTC, theboxer requested changes
Hey, thank you for your contribution. This is just a quick code review, I'll be testing this PR later on.

2021-10-15 15:29 UTC, theboxer commented on manager/assets/modext/core/modx.js
> +    ,renameLabel: function(containerId, fieldId, newLabel) {
This is quite a simple function, but written in unnecessary complex way - a lot of unnecessary nesting. I propose this approach:
```js
,renameLabel: function(containerId, fieldId, newLabel) {
    if (containerId === 'modx-panel-resource' && fieldId.indexOf('modx-resource-content') !== -1) {
        var container = Ext.getCmp('modx-resource-content');
        if (!container) return;
        
        if (container.setTitle) {
            container.setTitle(newLabel);
            return;
        }
        
        if (container.setLabel) {
            container.setLabel(fieldId, newLabel);
            return;
        }

        container.label.update(newLabel);
        return;        
    }
    
    var container = Ext.getCmp(containerId);
    if (!container) return;
  
    container.setLabel(fieldId, newLabel);        
}
```

2021-10-15 15:29 UTC, theboxer commented on manager/assets/modext/core/modx.js
> +    ,hideRegion: function(containerId, regionId) {
Unnecessary complexity.

```js
,hideRegion: function(containerId, regionId) {
    var tabPanel = Ext.getCmp(containerId);
    if (!tabPanel) return;

    var tabObj = tabPanel.getItem(regionId);
    if (!tabObj) {
        var region = Ext.getCmp(regionId);
        if (!region) return;

        region.hide();
        return;
    }

    var z = tabPanel.hideTabStripItem(regionId);
    var idx = this._getNextActiveTab(tabPanel,regionId);
    
    MODx.hiddenTabs.push(regionId);
    tabPanel.setActiveTab(idx);                    
}
```

2021-10-15 15:29 UTC, theboxer commented on manager/assets/modext/core/modx.js
>          }
```suggestion
        if (targetItem) {
            targetItem.replaceWith(sourceItem);
            return;
       }

        var id = tvId.replace('tv', '');
        console.warn('Attempted to move the TV named "'
            + sourceItem.dom.innerText + '" (id #' + id + ') to the panel with the id "'
            + target.id + '" but the original TV field could not be found. '
            + 'It is likely a conflicting customization rule has already tried to move this TV.'
        );       
```

2021-10-15 16:24 UTC, smg6511 commented
@theboxer - Just a general note as I work on your feedback: The methods I updated were primarily done so with the main purpose in mind (changing the unnecessary array-formatted params to string params), as well as renaming params so they're immediately understandable and providing doc blocks for the methods I worked with. I did not really alter them too much otherwise. As you're pointing out, maybe some re-writing could be done, but that's not what I was looking to address with this PR.

I've found that a lot of reworking needs to be done overall with the element creation and form customization UIs that may not be immediately apparent. See my PR #15773 ... it'll give you a pretty good idea of what I'm referring to. These type of changes are too big to be worthwhile for 2.x and are targeted for 3.x.

2021-10-15 16:31 UTC, theboxer commented
@smg6511 Sorry, I kind of missed that this is not a PR for 3.x, priorly knowing that this is for 2.x I wouldn't care about the complexity :))

Feel free to ignore them all.

I'd love to see the overall code quality to improve for 3.x, that's why I was trying to make these suggestions - as it makes the code more readable and easier to follow.

2021-10-15 16:38 UTC, smg6511 commented
@theboxer - No problem. I'm totally with you on upping the code quality! As I was playing with this I discovered how fragile the form customization is; once you have a conflicting rule (whether in one profile or across multiple ones) unexpected behavior creeps in. That'll be a bigger task for a different day ;-)

2021-10-17 05:32 UTC, smg6511 commented
@theboxer - There's still a change requested flagged, but I can't see where it is. Not sure if I dismiss that (and if so, how) or you do...

2021-10-18 10:51 UTC, theboxer requested changes
Unfortunately the signature changes are not possible for 2.x as they would break a backwards compatibility.

2021-10-18 10:51 UTC, theboxer commented on manager/assets/modext/core/modx.js
> +    ,moveTV: function(tvId, targetId) {
I'm afraid that this change can't go to 2.x as it technically breaks backwards compatibility (changing the array arg to string).

2021-10-18 10:51 UTC, theboxer commented on manager/assets/modext/core/modx.js
> +                    container.label.update(newLabel);
Same as the previous, breaks backwards compatibility by changing array to string.

2021-10-18 10:51 UTC, theboxer commented on manager/assets/modext/widgets/core/modx.panel.js
> +    ,hideField: function(fieldId) {
BC break as well

2021-10-18 10:51 UTC, theboxer commented on manager/assets/modext/widgets/core/modx.panel.js
> +    ,setLabel: function(fieldId, newLabel){
BC break

2021-10-18 14:21 UTC, smg6511 commented on manager/assets/modext/core/modx.js
> +    ,moveTV: function(tvId, targetId) {
Can you tell me how and at what version this would break it? Same with the others. I'd like to try to fix this issue for 2.x if possible, but it'll likely be unfixable if the FC rules were somehow saved in a serialized way at some point. Thx ;-)

2021-10-18 15:50 UTC, theboxer commented on manager/assets/modext/core/modx.js
> +    ,moveTV: function(tvId, targetId) {
Well you changed the signature of the function from accepting array/string and string, to accept string and string. I know you changed all the usages within modx, but if there's an extra out there that's using the array & string signature it'll break. Which is not allowed when following semver.

2021-10-18 17:10 UTC, smg6511 commented on manager/assets/modext/core/modx.js
> +    ,moveTV: function(tvId, targetId) {
Let me ask you this: Would there be any reason for an extra to interact directly with the FC rules/logic? I might be short-sited on this, but I can't imagine an extra utilizing these methods in any way.

On the breaking change/semver point, I get that and am wholeheartedly for following common and strict protocols. For the sake of debate, is it worth _not_ fixing a bug to maintain protocol when a change technically breaks the protocol but has a slim-to-none practical chance of actually breaking functionality? Arguably, the particular issue this PR addresses is low priority as far as bugs go, but addressing it did lead to discovering some seemingly unnecessarily complicated code.

Anyway, regardless of whether we drop this PR for 2.x, should I assume that the BC we're debating will not be an issue if submitted for 3.x?

2021-10-18 17:14 UTC, opengeek commented on manager/assets/modext/core/modx.js
> +    ,moveTV: function(tvId, targetId) {
Is there a specific reason this bug could not be resolved without changing the function signatures?

2021-10-18 17:22 UTC, smg6511 commented on manager/assets/modext/core/modx.js
> +    ,moveTV: function(tvId, targetId) {
Yes, the issue is that right now FC can't handle a comma in a field label because the current code reads that as a separator. I'm not sure there's a way around it _without_ changing the signature.

2021-11-05 23:49 UTC, smg6511 commented
Closing this for 2.x. A port to 3.x has been merged.

2021-11-05 23:49 UTC, closed without merging