[port to 3.x] Configurable extension for static html files
modxcms/revolution pull request #15855
Opened 2021-10-22 22:25 UTC by Ibochkarev

### What does it do?
Same as in #15722, but for 3.x branch

### Related issue(s)/PR(s)
#15722

2021-10-23 13:13 UTC, Mark-H approved these changes

2021-10-24 14:09 UTC, JoshuaLuckers requested changes

2021-10-24 14:09 UTC, JoshuaLuckers commented on _build/data/transport.core.system_settings.php
> +$settings['static_elements_html_extension'] = $xpdo->newObject('modSystemSetting');
```suggestion
$settings['static_elements_html_extension'] = $xpdo->newObject(modSystemSetting::class);
```

2021-10-24 14:09 UTC, JoshuaLuckers commented on _build/data/transport.core.system_settings.php
> +), '', true, true);
```suggestion
$settings['static_elements_html_extension']->fromArray([
    'key' => 'static_elements_html_extension',
    'value' => '.tpl',
    'xtype' => 'textfield',
    'namespace' => 'core',
    'area' => 'static_elements',
    'editedon' => null,
], '', true, true);
```

2021-10-25 16:50 UTC, Mark-H approved these changes

2021-10-26 06:36 UTC, Jako approved these changes

2021-11-05 21:03 UTC, alroniks approved these changes

2021-11-05 21:03 UTC, merged