Removed unused system settings
modxcms/revolution pull request #15881
Opened 2021-10-31 10:59 UTC by Ibochkarev

### What does it do?
Removed unused system settings

### Why is it needed?
These settings are outdated or found only in the "System Settings", do not participate in the remaining code:

- `resource_static_allow_absolute`
- `resource_static_path`
- `upload_check_exist`
- `websignupemail_message`

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/15877
https://github.com/modxcms/revolution/issues/15878

2021-10-31 12:49 UTC, alroniks commented
I am not sure about the two first. There were some security fixes related to it, isn't it @Mark-H?

2021-10-31 12:58 UTC, Ibochkarev commented
> I am not sure about the two first. There were some security fixes related to it, isn't it @Mark-H?



> I am not sure about the two first. There were some security fixes related to it, isn't it @Mark-H?

https://github.com/modxcms/revolution/blob/3.x/core/src/Revolution/modStaticResource.php#L63

Indeed, the setting is in the code and is used. So you need to add lexicons for the name and description of the system setting

2021-10-31 13:35 UTC, JoshuaLuckers commented
Hmm my mistake about those resource settings. I didn't see them in my setup 😅

2021-10-31 17:34 UTC, opengeek requested changes

2021-10-31 17:34 UTC, opengeek commented on setup/includes/upgrades/common/3.0.0-cleanup-system-settings.php
>      'resolve_hostnames',
Need these taken out before merging.

2021-10-31 18:10 UTC, Ibochkarev commented on setup/includes/upgrades/common/3.0.0-cleanup-system-settings.php
>      'resolve_hostnames',
Done

2021-11-02 16:05 UTC, Mark-H commented
Ohhh I completely forgot about porting that security fix to 3.x. The idea was to rewrite static resources a bit more extensively for 3.0 so they could actually use media sources. But at the very least we ought to get the fix in from 2.x which indeed uses those two settings.

2021-11-09 07:28 UTC, alroniks approved these changes

2021-11-09 07:37 UTC, Ruslan-Aleev commented
The question: if the user has a non-default value in the `upload_check_exist setting` in the 2.x branch, then when updating, we need to set the same value for `upload_file_exist`. Or, alternatively, make the keys the same.

2021-11-21 09:29 UTC, JoshuaLuckers commented
> Ohhh I completely forgot about porting that security fix to 3.x. The idea was to rewrite static resources a bit more extensively for 3.0 so they could actually use media sources. But at the very least we ought to get the fix in from 2.x which indeed uses those two settings.

Does this mean we need to port something from 2.x to 3.x and keep these system settings?

2022-01-16 23:55 UTC, Mark-H commented
Yes that's what it means.

2022-03-18 17:46 UTC, rthrash commented
Did the port happen @Mark-H or @JoshuaLuckers ? If so can we close this issue or maybe we close it and open a task to port it (unsure of which issue or I'd link it here).

2022-03-20 08:15 UTC, JoshuaLuckers commented
@rthrash not that I'm aware of

2023-01-26 21:35 UTC, closed without merging