Update default welcome screen url when upgrading from 2.8 to 3.x
modxcms/revolution pull request #15880
Opened 2021-10-31 09:25 UTC by JoshuaLuckers

### What does it do?
Make sure we update the welcome screen url if you upgrade from 2.8 to 3.x

### Why is it needed?
Currently it checks for the 2.7 welcome screen url in 3.x and only then it changes the value to the new one for 3.x

### How to test
Upgrade from 2.8 to 3.x and check the welcome screen url.

### Related issue(s)/PR(s)
Closes #15879

2021-10-31 10:28 UTC, Ibochkarev requested changes

2021-10-31 10:28 UTC, Ibochkarev commented on setup/includes/upgrades/common/3.0.0-update-sys-setting_welcome_screen_url.php
> +        '//misc.modx.com/revolution/welcome.27.html',
```suggestion
        '//misc.modx.com/revolution/welcome.26.html',
        '//misc.modx.com/revolution/welcome.27.html',
```

2021-11-01 14:30 UTC, opengeek commented
The welcome screen should not be showing on upgrades. This is not necessary.

2021-11-02 14:45 UTC, JoshuaLuckers commented
@opengeek Fair enough! Do you want me to delete the current upgrade script in addition to closing this PR?

2021-11-02 14:56 UTC, opengeek commented
> @opengeek Fair enough! Do you want me to delete the current upgrade script in addition to closing this PR?

Well, before we do that, I'd love to know why this became an issue. Is there a bug that is making it show again after upgrade?

2021-11-20 11:04 UTC, JoshuaLuckers commented
@opengeek no there is no bug that's showing the welcome screen after upgrading. Updating the welcome screen link is only for "consistency".

2021-11-30 09:21 UTC, closed without merging