Add ability to return to the same page after language switching
modxcms/revolution pull request #15895
Opened 2021-11-08 20:52 UTC by alroniks

### What does it do?
It fixes the issue when after switching the language user always returns to the main manager page. Now it respects the previous page (via referer header) and sends a redirect to that page if it exists. Otherwise fallback to the manager base URL. 

### Why is it needed?
Improve user experience during manager usage.

### How to test
Apply changes, go to any page inside the manager, and try to switch the language. You have to stay on the same page after language switching.

### Related issue(s)/PR(s)
#15174
#14046

2021-11-08 21:37 UTC, Ruslan-Aleev approved these changes
Works as it should :)

![lang_switcher](https://user-images.githubusercontent.com/12523676/140822122-1d884627-313d-40cc-9565-b01663c4d419.gif)

2021-11-09 01:24 UTC, Mark-H requested changes
This looks like it introduces an [open redirect vulnerability](https://sec.okta.com/articles/2021/02/why-it-so-hard-prevent-open-redirects); the referrer will need to be sanitized or forced to a relative url if we want to use this.

I'd personally feel best if the redirect created the redirect URL itself from a provided &target and &target_namespace and any other properties passed, i.e. something like:

```
$params = $scriptProperties;
$params['a'] = $params['target'] ?? 'welcome';
$params['namespace'] = $params['target_namespace'] ?? 'core';
unset($params['target'], $params['target_namespace']);
$url = MODX_MANAGER_URL . '?' . http_build_query($params);
```

2021-12-21 11:56 UTC, JoshuaLuckers commented
@alroniks do you have time to address the changes @Mark-H requested?

2021-12-31 09:25 UTC, Ruslan-Aleev commented
Deterioration in UX:
If you change the language to another and exit the manager panel, then the login form will display your system language (and not the one selected before exiting the panel), i.e. now you need to select the language again.

2022-02-23 16:12 UTC, Ruslan-Aleev commented
It has been fixed and merged into https://github.com/modxcms/revolution/pull/16069 I will close this PR.

2022-02-23 16:12 UTC, closed without merging