Added missing lexicon key
modxcms/revolution pull request #15931
Opened 2021-12-05 05:17 UTC by Ibochkarev

### What does it do?
Adds a missing lexicon

### Why is it needed?
![изображение](https://user-images.githubusercontent.com/2138260/144734670-2de4774e-8275-4464-b051-9b0152042ceb.png)

### Related issue(s)/PR(s)
#15930 15930

2021-12-05 21:23 UTC, opengeek requested changes
We should not be modifying any translations by hand. If it is not there, then something is wrong upstream via CrowdIn and needs to be addressed.

2021-12-06 00:18 UTC, Jako commented
@Ibochkarev The string was just added in the wrong lexicon.

2021-12-07 17:55 UTC, Ibochkarev commented
> We should not be modifying any translations by hand. If it is not there, then something is wrong upstream via CrowdIn and needs to be addressed.

This section was created in this PR https://github.com/modxcms/revolution/pull/15885, but the lexicon for the name of the system settings section is omitted.

2021-12-07 17:56 UTC, Ibochkarev commented
> @Ibochkarev The string is just added in the wrong lexicon.

In which file should this lexicon be placed?

2021-12-07 17:59 UTC, opengeek commented
The lexicon needs to be added to the en/ lexicon, not the bg/. The en/ lexicons are the source and are the only ones that should be edited directly.

2021-12-07 18:00 UTC, opengeek approved these changes

2021-12-07 18:02 UTC, Ibochkarev commented
> The lexicon needs to be added to the en/ lexicon, not the bg/. The en/ lexicons are the source and are the only ones that should be edited directly.

Sorry, I saw a mistake

2021-12-14 08:37 UTC, Jako approved these changes

2021-12-15 21:37 UTC, merged