Displayed the username in user menu
modxcms/revolution pull request #15973
Opened 2022-01-18 16:38 UTC by Ruslan-Aleev

### What does it do?
Displayed the username in user menu.
The `{$username}` placeholder works in the menu, which allows to display the username.

Before:
![menuBefore](https://user-images.githubusercontent.com/12523676/149979538-e92783cf-7626-433b-a866-952c43e0447d.png)

After:
![menuAfter](https://user-images.githubusercontent.com/12523676/149979536-00fe13ba-bc8d-46a2-a6dd-fbdf4b9f9cbd.png)

### Why is it needed?
In the manager it is not clear what user is logged in.

### How to test
Describe how to test the changes you made.

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/15595

2022-01-19 21:03 UTC, alroniks requested changes
Migration created, that's nice, but it missed [here](https://github.com/modxcms/revolution/blob/3.x/setup/includes/upgrades/mysql/3.0.0-pl.php). It will be run never.

2022-01-20 08:39 UTC, Ruslan-Aleev commented
@alroniks Here is the line - https://github.com/modxcms/revolution/blob/3.x/setup/includes/upgrades/mysql/3.0.0-pl.php#L21
Or what are you talking about?

2022-01-23 08:34 UTC, JoshuaLuckers approved these changes

2022-01-24 10:57 UTC, alroniks approved these changes

2022-01-24 17:19 UTC, merged