Update PHP versions in setup tests
modxcms/revolution pull request #16077
Opened 2022-02-23 21:07 UTC by opengeek

### What does it do?
Updates the required and recommended PHP versions in the setup version check.

### Why is it needed?
The version checks were outdated, allowing the installation of a downloaded distribution on versions that will not work.

### How to test
Try to install a distribution (not from git) on any PHP version prior to 7.2.5 and confirm it fails.

### Related issue(s)/PR(s)
n/a

2022-02-24 01:19 UTC, Ibochkarev approved these changes

2022-02-24 12:09 UTC, theboxer approved these changes

2022-03-01 12:32 UTC, JoshuaLuckers requested changes
The required PHP version needs to be updated here as well:  https://github.com/modxcms/revolution/blob/beed7f890ff7e6d77c2d616fffa0d1d372f9c969/setup/provisioner/requirements.php#L12

2022-03-01 19:54 UTC, opengeek commented
> The required PHP version needs to be updated here as well:
> 
> https://github.com/modxcms/revolution/blob/beed7f890ff7e6d77c2d616fffa0d1d372f9c969/setup/provisioner/requirements.php#L12

Ugh. Why is this stuff duplicated in so many places? (rhetorical—don't answer!)

2022-03-02 21:52 UTC, merged