Fix saving static elements
modxcms/revolution pull request #16091
Opened 2022-03-18 04:47 UTC by muzzwood

### What does it do?
Allows static elements to save regardless of the file extension if on a filesystem media source.

Beyond the changes Mark made, this essentially adds a "static element mode" to `modFileMediaSource` that allows skipping the file extension checks. When the mode is not active, any saving to a media source is still subject to those checks.

### Why is it needed?
See issue https://github.com/modxcms/revolution/issues/15927

This is a blocker for MODX 3.0 being released. This is meant to solve just this issue and be kept simple.

### How to test
Try saving static elements with and without a media source.

### Related issue(s)/PR(s)
This is an extension of the draft PR #16078 by @Mark-H . The first commit is his work, I just copied it. ;)
There's also a more in-depth approach by @smg6511 #16070 but that also involved solving other issues.

2022-03-18 05:10 UTC, muzzwood commented
Ugh. phpcs seems to be finding more issues each time I fix the reported ones.
I'm a tad worried that what was meant to be a straightforward PR is going to be obfuscated be all the syntax alterations. 🥲

2022-03-18 15:56 UTC, opengeek requested changes, later dismissed
I'm still of the opinion that a media source should have no concept of static elements or static resources or anything else internally. Could this be done as a generic option to disable the file type restrictions instead?

2022-03-19 02:20 UTC, muzzwood commented
Hi @opengeek, yeah that should be easy enough. Mark mentioned he'd prefer there be no mode at all, so I've got another approach in testing that does things the same way as 2.x. It only uses the media source to get the base path, concatenates, then writes via the cache manager. This way, there are no changes to media source behaviour, they're just being side-stepped.
I might push that up as a separate PR so everything's clear.

2022-03-19 04:50 UTC, muzzwood commented
Alternative PR is here: #16095

2022-03-21 03:27 UTC, muzzwood commented
Updated to make the mode naming generic, and remove any mention of static elements within the media source. 👍🏻

2022-03-21 19:30 UTC, opengeek reviewed
Okay, this is getting close I think. Another question, though. Why would the ignore_file_type code be limited to modFileMediaSource? Shouldn't this be part of all media sources? Am I missing something obvious?

2022-03-22 10:51 UTC, muzzwood commented
The intention there was so it only worked with a local filesystem media source. But if I misunderstood and it should work for any kind, then moving that to modMediaSource shouldn't break anything.

2022-03-22 13:33 UTC, opengeek commented
> The intention there was so it only worked with a local filesystem media source. But if I misunderstood and it should work for any kind, then moving that to modMediaSource shouldn't break anything.

Unless the selection of media sources for static elements is limited to modFileMediaSources, then I think it must work for any modMediaSource.

2022-03-22 14:24 UTC, muzzwood commented
That sounds fair! I've just restricted the media source combobox on the element panels to only list media sources with the `class_key` of `MODX\Revolution\Sources\modFileMediaSource`.
This was done by adding an optional `filesystemOnly` parameter to the get list request and adding a conditional `where`. e.g.
```
if ($this->getProperty('filesystemOnly')) {
    $c->where([
        'modMediaSource.class_key' => modFileMediaSource::class
    ]);
}
```

2022-03-22 14:41 UTC, opengeek commented
It would be nice to see a couple of reviews/approvals so we can get it merged and release 3.0 ASAP.

2022-03-22 18:15 UTC, opengeek commented
Even the most basic save of a static element with no media source is failing for me.

2022-04-16 08:15 UTC, JoshuaLuckers commented
Is this PR still relevant?

2022-04-29 02:05 UTC, muzzwood commented
> Is this PR still relevant?

Sorry for the delay @JoshuaLuckers ! This and the alternative PR can probably be closed now. Right @opengeek ?

2022-09-24 05:27 UTC, muzzwood commented
No longer needed. Closing!

2022-09-24 05:27 UTC, closed without merging