Change queryParam for typeahead in settings combo for Context/User section
modxcms/revolution pull request #16176
Opened 2022-05-05 11:24 UTC by Ruslan-Aleev

### What does it do?
Change queryParam for typeahead in settings combo for Context/User section.

As suggested @halftrainedharry https://github.com/modxcms/revolution/issues/16172#issuecomment-1114640804

Now the typeahead is working.

![query_combo](https://user-images.githubusercontent.com/12523676/166913612-f965fa37-a259-4d92-b70d-e93e24afa225.png)

### Why is it needed?
Typeahead inside Context/User settings doesn't work.

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/16172

2022-05-23 07:40 UTC, Ibochkarev approved these changes

2022-07-05 04:13 UTC, smg6511 requested changes
This works, but there are a couple things you can do to fine-tune this config:

1. Remove `typeAhead: false`, as it's already set in the parent `MODx.combo.ComboBox` class
2. Remove the `queryParam` property; it's not needed here because the base `Ext.form.ComboBox` class sets it to 'query' by default

2022-07-10 14:15 UTC, Ruslan-Aleev commented
> This works, but there are a couple things you can do to fine-tune this config:
> 
> 1. Remove `typeAhead: false`, as it's already set in the parent `MODx.combo.ComboBox` class
> 2. Remove the `queryParam` property; it's not needed here because the base `Ext.form.ComboBox` class sets it to 'query' by default

@smg6511 You are right, corrected the code, check.

2022-07-10 20:26 UTC, smg6511 approved these changes

2022-08-10 16:04 UTC, merged