Revert copy paths for a directory / file in tree
modxcms/revolution pull request #16180
Opened 2022-05-11 11:43 UTC by Ruslan-Aleev

### What does it do?
- Reverted copy paths for a directory / file in tree.

![file](https://user-images.githubusercontent.com/12523676/167841782-1541e628-ea55-40a9-af5a-2fd098996a05.png)
![folder](https://user-images.githubusercontent.com/12523676/167841786-cde10e0f-547d-4b5c-bb74-fcad8f9b5672.png)

- Deleted unused lexicons. Here it is worth checking carefully, there are suspiciously many unused lexicons.

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/16179

2022-05-17 11:21 UTC, JoshuaLuckers requested changes
Everything works as expected, only the array syntax needs to be changed.

2022-05-17 11:21 UTC, JoshuaLuckers commented on core/src/Revolution/Sources/modMediaSource.php
> +        );
```suggestion
        $menu[] = [
            'text' => $this->xpdo->lexicon('file_folder_copy_path'),
            'handler' => 'this.copyRelativePath',
        ];
```

2022-05-17 11:21 UTC, JoshuaLuckers commented on core/src/Revolution/Sources/modMediaSource.php
> +            );
```suggestion
            $menu[] = [
                'text' => $this->xpdo->lexicon('file_copy_path'),
                'handler' => 'this.copyRelativePath',
            ];
```

2022-05-20 09:33 UTC, JoshuaLuckers approved these changes

2022-05-23 07:37 UTC, Ibochkarev approved these changes

2022-07-07 17:40 UTC, merged