[3.x]-Fix Package Manager handling of API error
modxcms/revolution pull request #16217
Opened 2022-07-02 10:44 UTC by halftrainedharry

### What does it do?
When checking for package updates, the updated code takes into account that the API may return an error.

### Why is it needed?
The function `latest()` of the class `MODX\Revolution\Transport\modTransportProvider` may return an error string if no package release can be found.

https://github.com/modxcms/revolution/blob/cb6f56a19af818ad4d1d62dc0d31b9819aaa876f/core/src/Revolution/Transport/modTransportProvider.php#L226-L234

This can 'crash' the Package Manager when using PHP 8.

### How to test

- In MODX 3.0.1-pl, in the Package Manager download the extra "getDate" (from the default provider `modx.com`).
- Make sure the Package Manager doesn't 'hang' (PHP 8) and there is not PHP warning (PHP 7.x | `count(): Parameter must be an array or an object that implements Countable`).

### Related issue(s)/PR(s)
https://community.modx.com/t/package-manager-crashed-by-loading-getdate-modx-3-0-1-pl/5501

2022-07-03 12:32 UTC, Mark-H approved these changes

2022-07-04 04:01 UTC, smg6511 requested changes
First of all, tested this and it certainly works as written. Also, it fixes the issue of some Extras falsely showing that an update is available when it's not. I'd like to propose a small tweak, partly for brevity, partly to make more immediately clear the type of value expected in $updates. In place of your addition, consider:

`$updates = is_array($updates) ? ['count' => count($updates)] : ['count' => 0] ;`

If you disagree or it seems too nit-picky, I understand and will approve anyway ;-)

2022-07-04 08:53 UTC, halftrainedharry commented
@smg6511 I don't care how exactly this problem is fixed. Please change the code if you like to.

2022-07-16 10:59 UTC, JoshuaLuckers approved these changes

2022-08-10 16:15 UTC, merged

2022-10-12 08:43 UTC, rthrash commented
This pull request has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/upgrade-to-3-0-failed-with-multiple-problems/5890/15

2022-10-12 21:02 UTC, rthrash commented
This pull request has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/upgrade-to-3-0-failed-with-multiple-problems/5890/17

2022-10-14 16:26 UTC, rthrash commented
This pull request has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/upgrade-to-3-0-failed-with-multiple-problems/5890/26

2022-10-17 16:41 UTC, rthrash commented
This pull request has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/upgrade-to-3-0-failed-with-multiple-problems/5890/28

2023-04-30 07:03 UTC, rthrash commented
This pull request has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/dashboard-welcome-page-error/6679/2