Fix only_full_group_by issue in permission processor query
modxcms/revolution pull request #16227
Opened 2022-07-15 05:48 UTC by muzzwood

### What does it do?
Fixes an `only_full_group_by` issue in `MODX\Revolution\Processors\Security\Access\Permission\GetList`

### Why is it needed?
So the permission combobox works when `only_full_group_by` is enabled.

### How to test
Have `only_full_group_by` enabled in MySQL and try to select a permission on either the widget edit panel on the Dashboards page, or create a new permission in a policy template.

### Related issue(s)/PR(s)
Resolves #16226

2022-07-16 15:17 UTC, smg6511 requested changes
This actually causes another problem, in that duplicates show up in the list. What you need to do is change lines 65-71 to:
```
$c->select([
    'id' => 'MIN(modAccessPermission.id)',
    'modAccessPermission.name',
    'modAccessPermission.description',
    'Template.lexicon',
]);
$c->groupby('modAccessPermission.name, modAccessPermission.description, Template.lexicon');
```

2022-09-24 05:55 UTC, muzzwood commented
Thanks @smg6511, you're not wrong! I've updated the PR with your suggestion. 👍🏻

2022-09-25 04:37 UTC, smg6511 commented
@muzzwood - Hey, I put up an alternate PR on this subject after finding an issue while testing this (not an issue caused by your code, but an underlying one that wasn't initially apparent). I tried to think of a way to just suggest the solution I arrived at to add to your PR, but it involved changing other files not present here. Take a look and see what you think (#16273).

2022-10-01 16:08 UTC, Mark-H commented
Question... why is groupby() being used here anyway? I'm not seeing why this is supposedly aggregating rows beyond the (new) `MIN()` select? Wouldn't it be a simpler solution to remove the groupby line?

2022-10-01 19:03 UTC, smg6511 commented
@Mark-H - We only want to group by the `name` so we can generate a unique list for the combo; remember that we don't have a separate table where each permission is defined (once, that is), so the table from which this list is derived will contain multiple rows for the same permission once a user starts adding new ACLs. That is why MIN is used on the id field (or MAX could've been used). If there's a better way, I'm all ears ;-) 

I'd personally rather see the permissions defined in a separate table, but that'd be a somewhat major structural change.

2022-10-01 20:24 UTC, Mark-H commented
Ah, so because it's fetching permissions from different access policies/templates it may have duplicates. Gotcha.

2022-11-04 03:14 UTC, muzzwood commented
Hi @smg6511 ,
Sorry for being unresponsive, it slipped off my radar. 🙈 
I'm more than happy for you to handle the fix in your larger PR.
Nice work, and thanks for looking into it! 
Closing this one for now.

2022-11-04 03:14 UTC, closed without merging