Remove create_function from moddashboardwidget
modxcms/revolution pull request #16290
Opened 2022-10-31 20:58 UTC by matdave

### What does it do?
Remove create_function from the PHP dashboard widget processor, and run the content as a snippet. 

### Why is it needed?
create_function is removed in PHP 8.0

### How to test
Create a PHP Dashboard widget in MODX running on PHP 8+
e.g. 
```
<?php 
echo "Hello world!"
```

### Related issue(s)/PR(s)
#15918

2022-10-31 21:04 UTC, Mark-H commented
It's worth noting this is the fix for this in 3.0:

```
        $closure = function ($scriptProperties) use ($content) {
            global $modx;
            if (is_array($scriptProperties)) {
                extract($scriptProperties, EXTR_SKIP);
            }

            return eval($content);
        };

        return $closure([
            'controller' => $this->controller,
        ]);
```

Yours is better though as it avoids using `eval()` as well. 

Only concern I have is that the generated script might not have a valid filename because the snippet has no ID? Maybe it works fine as the default ID 0, though.

2022-10-31 21:22 UTC, matdave commented
@Mark-H I tested it on a site with quite a few custom dashboard widgets all loading at once and it seems to work fine. :fist_right: :wood:

2022-11-16 09:50 UTC, JoshuaLuckers commented
> Only concern I have is that the generated script might not have a valid filename because the snippet has no ID? Maybe it works fine as the default ID 0, though.

I share a similar concern, when `process` is called it will get the include filename for the script, generating it if it does not exist: https://github.com/modxcms/revolution/blob/8e400704988184f6e396cf19d9047b6a34ad217e/core/src/Revolution/modScript.php#L77

The name of the script/file will use the ID (in this case 0): https://github.com/modxcms/revolution/blob/8e400704988184f6e396cf19d9047b6a34ad217e/core/src/Revolution/modScript.php#L147

I'm not totally sure but later on the cacheManager is used to create a file: https://github.com/modxcms/revolution/blob/8e400704988184f6e396cf19d9047b6a34ad217e/core/src/Revolution/modScript.php#L193

If you have multiple dashboards and they all have a `modSnippet` with id `0` this might cause some conflicts if they try to read/write to the same file at the same time.

2022-11-25 16:26 UTC, matdave commented
> If you have multiple dashboards and they all have a `modSnippet` with id `0` this might cause some conflicts if they try to read/write to the same file at the same time.


It overwrites with each call, so it never double responds with the same widget if that's what your concern is.

2022-12-02 13:51 UTC, opengeek requested changes

2022-12-02 13:51 UTC, opengeek commented on core/model/modx/moddashboardwidget.class.php
> +        $snippet = $this->modx->newObject('modSnippet');
I think it would be good to set the name to something like `md5($this->widget->get('content'))` or similar.

2022-12-05 16:32 UTC, matdave commented
I'm not sure why the GH Compare got so screwed up, but I adjusted Line 317 onward to match the solution for rendering files as snippets in MODX 3.

2022-12-05 16:54 UTC, opengeek commented
> I'm not sure why the GH Compare got so screwed up, but I adjusted Line 317 onward to match the solution for [rendering files as snippets in MODX 3](https://github.com/modxcms/revolution/blob/f2bdbec64b10933146712d21fc8819f43ef334a2/core/src/Revolution/modDashboardWidgetInterface.php#L157).

You changed the line-endings.

2022-12-07 16:25 UTC, opengeek approved these changes

2022-12-07 16:25 UTC, merged

2023-01-06 11:58 UTC, rthrash commented
This pull request has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/custom-dashboard-widget-issue-after-upgrade-php8/6254/2