Include the media source id in MODX media browser data [ReUp]
modxcms/revolution pull request #16311
Opened 2022-11-28 10:17 UTC by muzzwood

### What does it do?
Includes the media source id in the "onSelect" callback data. 

### Why is it needed?
Currently the media source id is missing from that data. It would be useful for custom handling.

### How to test
Check that the correct "source" is now in the data array when listening for the select event.

e.g.
```
let browser = MODx.load({
    xtype: 'modx-browser',
    multiple: true,
    listeners: {
        select: {fn: function(data) {
            console.log(data.source);
    }, scope:this}
...
```

2022-11-28 10:34 UTC, muzzwood commented
Actually that's not reliable. I'll come back with a different approach.

2022-12-26 12:27 UTC, Jako commented
I don't get the reason for this patch. The scope of the callback is `this` and so you can access the source inside with `this.config.scope`. Or am I wrong with that?

2022-12-26 12:35 UTC, Jako requested changes
I don't get the reason for this patch. The scope of the callback is `this` in all cases in MODx.browser and so you can access the source inside with `this.config.source`. Or am I wrong with that?

2022-12-26 20:29 UTC, smg6511 commented
@muzzwood - It would be helpful to know from where and how you are accessing the select callback as, like @Jako points out, the source may also be accessible via `this.config`. I don't think there's anything wrong with explicitly adding the source to the callback's data, but it might not be needed.

2022-12-30 01:15 UTC, muzzwood commented
Thanks for the reviews! IIRC it wasn't available in the callback but I could have missed it. 
I'll double check and report back after the holidays.

2023-01-09 04:36 UTC, muzzwood commented
Happy New Year! :)
I went and had another look. 
You're right @Jako, if the scope isn't specified/overridden on the listener then the scope is the browser and it's available via `this.config.source`.

However, if a different scope is being set on the listener (like it the code I was working with), then it's not available. e.g.

```
            listeners: {
                select: {fn: function(file) {
                    // Not available here as scope is set to outer component
                }, scope: this}
            },
```

```
            listeners: {
                select: {fn: function(file) {
                    // Available here because the scope is the browser
                }}
            },
```

While a developer could just refactor code to make sure the callback scope is always the browser object, I reckon it would still be handy to have the source available via the passed callback object too. e.g. `file.source` in the above example.

2023-01-11 02:27 UTC, Mark-H commented
I'd say in most cases the scope will in fact be overwritten, because you're asking the browser to select an image - you'll be wanting to handle that image in your own code. This gets my approval, but then again, I'm biased having asked Murray to work on this in the first place. 😛 

Just realized this will conflict with #16348 however I'm happy to adjust that PR if needed.

2023-01-13 06:08 UTC, smg6511 requested changes
Mostly fine-tuning here. The one really important change is the addition of default source in both `onSelect` methods:
```javascript
source = this.config.source || MODx.config.default_media_source
```

2023-01-13 06:08 UTC, smg6511 commented on manager/assets/modext/widgets/media/modx.browser.js
> +                data.source = source;
Aside from some minor formatting fixes, just a few substantive changes here:

1. With ES6+, avoid `var` declaration unless there's a specific reason to use it. Use `const`, or when a variable will later be assigned a new value `let`.
2. Added the default source, as the source will not show up in `this.config.source` until it is _changed_ in the tree.
3. Cast the source to Integer when a value is present.

```suggestion
        const selNode = this.view.getSelectedNodes()[0],
              callback = this.config.onSelect || this.onSelectHandler,
              lookup = this.view.lookup,
              scope = this.config.scope,
              source = this.config.source || MODx.config.default_media_source
        ;
        this.hide(this.config.animEl || null, function() {
            if (callback){
                const data = lookup[selNode.id];
                data.source = source ? parseInt(source) : undefined ;
```

2023-01-13 06:08 UTC, smg6511 commented on manager/assets/modext/widgets/media/modx.browser.js
> +            data.source = source;
Same moves as above here plus simplified the reassignment of `data` to match above (there's no need to test for truthiness of `selNode`, as a selection had to have been made for `onSelect` to be called).
```suggestion
        const selNode = this.view.getSelectedNodes()[0],
              callback = this.config.onSelect || this.onSelectHandler,
              lookup = this.view.lookup,
              scope = this.config.scope,
              source = this.config.source || MODx.config.default_media_source
        ;
        if (callback) {
            data = lookup[selNode.id];
            data.source = source ? parseInt(source) : undefined ;
```

2023-01-30 17:52 UTC, Mark-H commented
Closing as this change was also included in #16348 which is now merged.

2023-01-30 17:52 UTC, closed without merging