Remove unnecessary settings for uploaded files
modxcms/revolution pull request #16349
Opened 2023-01-13 23:00 UTC by Ruslan-Aleev

### What does it do?
Remove unnecessary settings for uploaded files. Basically, the file settings are set in the media source, so so many settings are not needed.

Previously, you had to add extensions in 3 places, in the media source settings, and in the `upload_files` and `upload_images/upload_media` system settings, while the extensions were duplicated. Now there are fewer settings, at least 2.

Perhaps in the future it is worth transferring them completely to the media source.

### Related issue(s)/PR(s)
N\A

2023-01-19 16:35 UTC, Mark-H requested changes
I'd like this to make sure on upgrade that anything in the removed settings is copied into `upload_files`, other than that I'm very happy to see these go.

2023-01-19 19:34 UTC, Ruslan-Aleev commented
> I'd like this to make sure on upgrade that anything in the removed settings is copied into upload_files

Is it possible to upload files if they are not set in the `upload_files` setting? I don't think so.

2023-01-20 18:51 UTC, Mark-H commented on setup/includes/upgrades/common/3.0.0-update-sys-setting_upload_files.php
> +    $upload_files_arr_new = array_filter($upload_files_arr_new, fn($value) => !is_null($value) && $value !== '');
[Arrow shorthand functions](https://www.php.net/manual/en/functions.arrow.php) were introduced in php 7.4, officially MODX3 still supports 7.2.

(Bumping that is a good topic to discuss elsewhere.)

2023-01-20 18:53 UTC, Mark-H commented on setup/includes/upgrades/common/3.0.0-update-sys-setting_upload_files.php
> +    $upload_files_arr_new = array_filter($upload_files_arr_new, fn($value) => !is_null($value) && $value !== '');
It also looks like this particular callback could simply be removed as the default filter array_filter does will already filter out empty values.

2023-01-24 17:03 UTC, Mark-H reviewed
Looking good minus the phpcs errors (red).

2023-01-24 18:52 UTC, Ibochkarev commented
> Looking good minus the phpcs errors (red).

Fixed

2023-01-25 19:47 UTC, Mark-H approved these changes

2023-01-25 19:51 UTC, Ibochkarev approved these changes

2023-01-26 16:24 UTC, merged