Add session garbage collector check
modxcms/revolution pull request #16448
Opened 2023-06-18 11:47 UTC by Ruslan-Aleev

### What does it do?
It often happens that the `modx_session` table grows uncontrollably (I have seen up to 5 gigabytes), which sometimes leads to complete non-operation of both the site and the server.

I added session garbage collector check in installer.

![gc_installer_warn](https://user-images.githubusercontent.com/12523676/196445992-6b161c2c-519e-4cc4-bbe4-5ee67e60d150.png)

### Why is it needed?
That there were no problems with overflow of the table `modx_session`.

### How to test
Make the installation from scratch by changing the `session.gc_probability, session.gc_divisor` parameters.

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/pull/16287
https://github.com/modxcms/revolution/issues/16275

2023-08-04 15:44 UTC, Mark-H approved these changes, later dismissed

2023-10-12 12:10 UTC, theboxer requested changes
I'd suggest following changes, it removes some unnecessary ifs and makes it slightly more readable.

2023-10-12 12:10 UTC, theboxer commented on setup/includes/test/modinstalltest.class.php
> +        $success = false;
```suggestion
        $status = 'success';
```

2023-10-12 12:10 UTC, theboxer commented on setup/includes/test/modinstalltest.class.php
> +        }
```suggestion
        }
```

2023-10-12 12:10 UTC, theboxer commented on setup/includes/test/modinstalltest.class.php
> +            $success = $success !== false ? true : false;
```suggestion
            $status = @ini_set('session.gc_probability', 1) !== false ? 'success' : 'fail';
```

2023-10-12 12:10 UTC, theboxer commented on setup/includes/test/modinstalltest.class.php
> +        }
```suggestion
        $this->warn('session_gc', '', $this->install->lexicon("test_session_gc_$status", ['gc_probability' => $gc_probability, 'gc_divisor' => $gc_divisor]));
        
```

2023-10-13 11:38 UTC, theboxer approved these changes
👍

2024-02-10 15:40 UTC, Mark-H commented
Do the lexicons need to be in both default.inc.php and test.inc.php?

2024-02-12 09:48 UTC, Ruslan-Aleev commented
@Mark-H To be honest, I don’t know, I haven’t figured it out. Other keys are present in both files.

2024-03-25 14:44 UTC, merged